/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.PackagingMaterialClassificationCodeReference;
import org.foodauthent.oneworldsync.client.model.PackagingMaterialColourCodeReference;
import org.foodauthent.oneworldsync.client.model.QualifiedValue;
import org.foodauthent.oneworldsync.client.model.QualifiedValues;

/**
 * CompositeMaterialDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class CompositeMaterialDetail {
	@JsonProperty("packagingMaterialClassificationCodeReference")
	private List<PackagingMaterialClassificationCodeReference> packagingMaterialClassificationCodeReference = null;

	@JsonProperty("packagingMaterialColourCodeReference")
	private List<PackagingMaterialColourCodeReference> packagingMaterialColourCodeReference = null;

	@JsonProperty("packagingMaterialCompositionQuantity")
	private QualifiedValues packagingMaterialCompositionQuantity = null;

	@JsonProperty("packagingMaterialThickness")
	private QualifiedValue packagingMaterialThickness = null;

	@JsonProperty("packagingMaterialTypeCode")
	private CodifiedValue packagingMaterialTypeCode = null;

	public CompositeMaterialDetail packagingMaterialClassificationCodeReference(
			List<PackagingMaterialClassificationCodeReference> packagingMaterialClassificationCodeReference) {
		this.packagingMaterialClassificationCodeReference = packagingMaterialClassificationCodeReference;
		return this;
	}

	public CompositeMaterialDetail addPackagingMaterialClassificationCodeReferenceItem(
			PackagingMaterialClassificationCodeReference packagingMaterialClassificationCodeReferenceItem) {
		if (this.packagingMaterialClassificationCodeReference == null) {
			this.packagingMaterialClassificationCodeReference = new ArrayList<PackagingMaterialClassificationCodeReference>();
		}
		this.packagingMaterialClassificationCodeReference.add(packagingMaterialClassificationCodeReferenceItem);
		return this;
	}

	/**
	 * Get packagingMaterialClassificationCodeReference
	 * 
	 * @return packagingMaterialClassificationCodeReference
	 **/
	@ApiModelProperty(value = "")
	public List<PackagingMaterialClassificationCodeReference> getPackagingMaterialClassificationCodeReference() {
		return packagingMaterialClassificationCodeReference;
	}

	public void setPackagingMaterialClassificationCodeReference(
			List<PackagingMaterialClassificationCodeReference> packagingMaterialClassificationCodeReference) {
		this.packagingMaterialClassificationCodeReference = packagingMaterialClassificationCodeReference;
	}

	public CompositeMaterialDetail packagingMaterialColourCodeReference(
			List<PackagingMaterialColourCodeReference> packagingMaterialColourCodeReference) {
		this.packagingMaterialColourCodeReference = packagingMaterialColourCodeReference;
		return this;
	}

	public CompositeMaterialDetail addPackagingMaterialColourCodeReferenceItem(
			PackagingMaterialColourCodeReference packagingMaterialColourCodeReferenceItem) {
		if (this.packagingMaterialColourCodeReference == null) {
			this.packagingMaterialColourCodeReference = new ArrayList<PackagingMaterialColourCodeReference>();
		}
		this.packagingMaterialColourCodeReference.add(packagingMaterialColourCodeReferenceItem);
		return this;
	}

	/**
	 * Get packagingMaterialColourCodeReference
	 * 
	 * @return packagingMaterialColourCodeReference
	 **/
	@ApiModelProperty(value = "")
	public List<PackagingMaterialColourCodeReference> getPackagingMaterialColourCodeReference() {
		return packagingMaterialColourCodeReference;
	}

	public void setPackagingMaterialColourCodeReference(
			List<PackagingMaterialColourCodeReference> packagingMaterialColourCodeReference) {
		this.packagingMaterialColourCodeReference = packagingMaterialColourCodeReference;
	}

	public CompositeMaterialDetail packagingMaterialCompositionQuantity(
			QualifiedValues packagingMaterialCompositionQuantity) {
		this.packagingMaterialCompositionQuantity = packagingMaterialCompositionQuantity;
		return this;
	}

	/**
	 * Get packagingMaterialCompositionQuantity
	 * 
	 * @return packagingMaterialCompositionQuantity
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getPackagingMaterialCompositionQuantity() {
		return packagingMaterialCompositionQuantity;
	}

	public void setPackagingMaterialCompositionQuantity(QualifiedValues packagingMaterialCompositionQuantity) {
		this.packagingMaterialCompositionQuantity = packagingMaterialCompositionQuantity;
	}

	public CompositeMaterialDetail packagingMaterialThickness(QualifiedValue packagingMaterialThickness) {
		this.packagingMaterialThickness = packagingMaterialThickness;
		return this;
	}

	/**
	 * Get packagingMaterialThickness
	 * 
	 * @return packagingMaterialThickness
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValue getPackagingMaterialThickness() {
		return packagingMaterialThickness;
	}

	public void setPackagingMaterialThickness(QualifiedValue packagingMaterialThickness) {
		this.packagingMaterialThickness = packagingMaterialThickness;
	}

	public CompositeMaterialDetail packagingMaterialTypeCode(CodifiedValue packagingMaterialTypeCode) {
		this.packagingMaterialTypeCode = packagingMaterialTypeCode;
		return this;
	}

	/**
	 * Get packagingMaterialTypeCode
	 * 
	 * @return packagingMaterialTypeCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getPackagingMaterialTypeCode() {
		return packagingMaterialTypeCode;
	}

	public void setPackagingMaterialTypeCode(CodifiedValue packagingMaterialTypeCode) {
		this.packagingMaterialTypeCode = packagingMaterialTypeCode;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CompositeMaterialDetail compositeMaterialDetail = (CompositeMaterialDetail) o;
		return Objects.equals(this.packagingMaterialClassificationCodeReference,
				compositeMaterialDetail.packagingMaterialClassificationCodeReference)
				&& Objects.equals(this.packagingMaterialColourCodeReference,
						compositeMaterialDetail.packagingMaterialColourCodeReference)
				&& Objects.equals(this.packagingMaterialCompositionQuantity,
						compositeMaterialDetail.packagingMaterialCompositionQuantity)
				&& Objects.equals(this.packagingMaterialThickness, compositeMaterialDetail.packagingMaterialThickness)
				&& Objects.equals(this.packagingMaterialTypeCode, compositeMaterialDetail.packagingMaterialTypeCode);
	}

	@Override
	public int hashCode() {
		return Objects.hash(packagingMaterialClassificationCodeReference, packagingMaterialColourCodeReference,
				packagingMaterialCompositionQuantity, packagingMaterialThickness, packagingMaterialTypeCode);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CompositeMaterialDetail {\n");

		sb.append("    packagingMaterialClassificationCodeReference: ")
				.append(toIndentedString(packagingMaterialClassificationCodeReference)).append("\n");
		sb.append("    packagingMaterialColourCodeReference: ")
				.append(toIndentedString(packagingMaterialColourCodeReference)).append("\n");
		sb.append("    packagingMaterialCompositionQuantity: ")
				.append(toIndentedString(packagingMaterialCompositionQuantity)).append("\n");
		sb.append("    packagingMaterialThickness: ").append(toIndentedString(packagingMaterialThickness)).append("\n");
		sb.append("    packagingMaterialTypeCode: ").append(toIndentedString(packagingMaterialTypeCode)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
