/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.QualifiedValue;

/**
 * CumulativeEnergyDemand
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class CumulativeEnergyDemand {
	@JsonProperty("cumulativeEnergyDemand")
	private QualifiedValue cumulativeEnergyDemand = null;

	@JsonProperty("cumulativeEnergyDemandDescription")
	private LanguageLabels cumulativeEnergyDemandDescription = null;

	@JsonProperty("cumulativeEnergyDemandProtocolCode")
	private CodifiedValue cumulativeEnergyDemandProtocolCode = null;

	@JsonProperty("cumulativeEnergyDemandProtocolDescription")
	private LanguageLabels cumulativeEnergyDemandProtocolDescription = null;

	@JsonProperty("cumulativeEnergyDemandReferenceSubstanceCode")
	private CodifiedValue cumulativeEnergyDemandReferenceSubstanceCode = null;

	@JsonProperty("cumulativeEnergyDemandReferenceSubstanceDescription")
	private LanguageLabels cumulativeEnergyDemandReferenceSubstanceDescription = null;

	@JsonProperty("cumulativeEnergyDemandTypeCode")
	private CodifiedValue cumulativeEnergyDemandTypeCode = null;

	public CumulativeEnergyDemand cumulativeEnergyDemand(QualifiedValue cumulativeEnergyDemand) {
		this.cumulativeEnergyDemand = cumulativeEnergyDemand;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemand
	 * 
	 * @return cumulativeEnergyDemand
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValue getCumulativeEnergyDemand() {
		return cumulativeEnergyDemand;
	}

	public void setCumulativeEnergyDemand(QualifiedValue cumulativeEnergyDemand) {
		this.cumulativeEnergyDemand = cumulativeEnergyDemand;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandDescription(LanguageLabels cumulativeEnergyDemandDescription) {
		this.cumulativeEnergyDemandDescription = cumulativeEnergyDemandDescription;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandDescription
	 * 
	 * @return cumulativeEnergyDemandDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getCumulativeEnergyDemandDescription() {
		return cumulativeEnergyDemandDescription;
	}

	public void setCumulativeEnergyDemandDescription(LanguageLabels cumulativeEnergyDemandDescription) {
		this.cumulativeEnergyDemandDescription = cumulativeEnergyDemandDescription;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandProtocolCode(CodifiedValue cumulativeEnergyDemandProtocolCode) {
		this.cumulativeEnergyDemandProtocolCode = cumulativeEnergyDemandProtocolCode;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandProtocolCode
	 * 
	 * @return cumulativeEnergyDemandProtocolCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getCumulativeEnergyDemandProtocolCode() {
		return cumulativeEnergyDemandProtocolCode;
	}

	public void setCumulativeEnergyDemandProtocolCode(CodifiedValue cumulativeEnergyDemandProtocolCode) {
		this.cumulativeEnergyDemandProtocolCode = cumulativeEnergyDemandProtocolCode;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandProtocolDescription(
			LanguageLabels cumulativeEnergyDemandProtocolDescription) {
		this.cumulativeEnergyDemandProtocolDescription = cumulativeEnergyDemandProtocolDescription;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandProtocolDescription
	 * 
	 * @return cumulativeEnergyDemandProtocolDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getCumulativeEnergyDemandProtocolDescription() {
		return cumulativeEnergyDemandProtocolDescription;
	}

	public void setCumulativeEnergyDemandProtocolDescription(LanguageLabels cumulativeEnergyDemandProtocolDescription) {
		this.cumulativeEnergyDemandProtocolDescription = cumulativeEnergyDemandProtocolDescription;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandReferenceSubstanceCode(
			CodifiedValue cumulativeEnergyDemandReferenceSubstanceCode) {
		this.cumulativeEnergyDemandReferenceSubstanceCode = cumulativeEnergyDemandReferenceSubstanceCode;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandReferenceSubstanceCode
	 * 
	 * @return cumulativeEnergyDemandReferenceSubstanceCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getCumulativeEnergyDemandReferenceSubstanceCode() {
		return cumulativeEnergyDemandReferenceSubstanceCode;
	}

	public void setCumulativeEnergyDemandReferenceSubstanceCode(
			CodifiedValue cumulativeEnergyDemandReferenceSubstanceCode) {
		this.cumulativeEnergyDemandReferenceSubstanceCode = cumulativeEnergyDemandReferenceSubstanceCode;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandReferenceSubstanceDescription(
			LanguageLabels cumulativeEnergyDemandReferenceSubstanceDescription) {
		this.cumulativeEnergyDemandReferenceSubstanceDescription = cumulativeEnergyDemandReferenceSubstanceDescription;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandReferenceSubstanceDescription
	 * 
	 * @return cumulativeEnergyDemandReferenceSubstanceDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getCumulativeEnergyDemandReferenceSubstanceDescription() {
		return cumulativeEnergyDemandReferenceSubstanceDescription;
	}

	public void setCumulativeEnergyDemandReferenceSubstanceDescription(
			LanguageLabels cumulativeEnergyDemandReferenceSubstanceDescription) {
		this.cumulativeEnergyDemandReferenceSubstanceDescription = cumulativeEnergyDemandReferenceSubstanceDescription;
	}

	public CumulativeEnergyDemand cumulativeEnergyDemandTypeCode(CodifiedValue cumulativeEnergyDemandTypeCode) {
		this.cumulativeEnergyDemandTypeCode = cumulativeEnergyDemandTypeCode;
		return this;
	}

	/**
	 * Get cumulativeEnergyDemandTypeCode
	 * 
	 * @return cumulativeEnergyDemandTypeCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getCumulativeEnergyDemandTypeCode() {
		return cumulativeEnergyDemandTypeCode;
	}

	public void setCumulativeEnergyDemandTypeCode(CodifiedValue cumulativeEnergyDemandTypeCode) {
		this.cumulativeEnergyDemandTypeCode = cumulativeEnergyDemandTypeCode;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CumulativeEnergyDemand cumulativeEnergyDemand = (CumulativeEnergyDemand) o;
		return Objects.equals(this.cumulativeEnergyDemand, cumulativeEnergyDemand.cumulativeEnergyDemand)
				&& Objects.equals(this.cumulativeEnergyDemandDescription,
						cumulativeEnergyDemand.cumulativeEnergyDemandDescription)
				&& Objects.equals(this.cumulativeEnergyDemandProtocolCode,
						cumulativeEnergyDemand.cumulativeEnergyDemandProtocolCode)
				&& Objects.equals(this.cumulativeEnergyDemandProtocolDescription,
						cumulativeEnergyDemand.cumulativeEnergyDemandProtocolDescription)
				&& Objects.equals(this.cumulativeEnergyDemandReferenceSubstanceCode,
						cumulativeEnergyDemand.cumulativeEnergyDemandReferenceSubstanceCode)
				&& Objects.equals(this.cumulativeEnergyDemandReferenceSubstanceDescription,
						cumulativeEnergyDemand.cumulativeEnergyDemandReferenceSubstanceDescription)
				&& Objects.equals(this.cumulativeEnergyDemandTypeCode,
						cumulativeEnergyDemand.cumulativeEnergyDemandTypeCode);
	}

	@Override
	public int hashCode() {
		return Objects.hash(cumulativeEnergyDemand, cumulativeEnergyDemandDescription,
				cumulativeEnergyDemandProtocolCode, cumulativeEnergyDemandProtocolDescription,
				cumulativeEnergyDemandReferenceSubstanceCode, cumulativeEnergyDemandReferenceSubstanceDescription,
				cumulativeEnergyDemandTypeCode);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CumulativeEnergyDemand {\n");

		sb.append("    cumulativeEnergyDemand: ").append(toIndentedString(cumulativeEnergyDemand)).append("\n");
		sb.append("    cumulativeEnergyDemandDescription: ").append(toIndentedString(cumulativeEnergyDemandDescription))
				.append("\n");
		sb.append("    cumulativeEnergyDemandProtocolCode: ")
				.append(toIndentedString(cumulativeEnergyDemandProtocolCode)).append("\n");
		sb.append("    cumulativeEnergyDemandProtocolDescription: ")
				.append(toIndentedString(cumulativeEnergyDemandProtocolDescription)).append("\n");
		sb.append("    cumulativeEnergyDemandReferenceSubstanceCode: ")
				.append(toIndentedString(cumulativeEnergyDemandReferenceSubstanceCode)).append("\n");
		sb.append("    cumulativeEnergyDemandReferenceSubstanceDescription: ")
				.append(toIndentedString(cumulativeEnergyDemandReferenceSubstanceDescription)).append("\n");
		sb.append("    cumulativeEnergyDemandTypeCode: ").append(toIndentedString(cumulativeEnergyDemandTypeCode))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
