/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.CodifiedValues;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.QualifiedValues;

/**
 * HealthRelatedInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class HealthRelatedInformation {
	@JsonProperty("compulsoryAdditiveLabelInformation")
	private LanguageLabels compulsoryAdditiveLabelInformation = null;

	@JsonProperty("doesTradeItemCompositionIncludeLatex")
	private CodifiedValue doesTradeItemCompositionIncludeLatex = null;

	@JsonProperty("expectedResultsTime")
	private QualifiedValues expectedResultsTime = null;

	@JsonProperty("healthClaimCode")
	private CodifiedValues healthClaimCode = null;

	@JsonProperty("healthClaimDescription")
	private LanguageLabels healthClaimDescription = null;

	@JsonProperty("isTradeItemChemicalNotIntendedForHumanConsumption")
	private CodifiedValue isTradeItemChemicalNotIntendedForHumanConsumption = null;

	@JsonProperty("nutritionalLabelTypeCode")
	private CodifiedValues nutritionalLabelTypeCode = null;

	@JsonProperty("nutritionalProgramCode")
	private CodifiedValues nutritionalProgramCode = null;

	@JsonProperty("nutritionalProgramDetail")
	private LanguageLabels nutritionalProgramDetail = null;

	@JsonProperty("sunProtectionFactor")
	private String sunProtectionFactor = null;

	@JsonProperty("tradeItemUVRating")
	private String tradeItemUVRating = null;

	public HealthRelatedInformation compulsoryAdditiveLabelInformation(
			LanguageLabels compulsoryAdditiveLabelInformation) {
		this.compulsoryAdditiveLabelInformation = compulsoryAdditiveLabelInformation;
		return this;
	}

	/**
	 * Get compulsoryAdditiveLabelInformation
	 * 
	 * @return compulsoryAdditiveLabelInformation
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getCompulsoryAdditiveLabelInformation() {
		return compulsoryAdditiveLabelInformation;
	}

	public void setCompulsoryAdditiveLabelInformation(LanguageLabels compulsoryAdditiveLabelInformation) {
		this.compulsoryAdditiveLabelInformation = compulsoryAdditiveLabelInformation;
	}

	public HealthRelatedInformation doesTradeItemCompositionIncludeLatex(
			CodifiedValue doesTradeItemCompositionIncludeLatex) {
		this.doesTradeItemCompositionIncludeLatex = doesTradeItemCompositionIncludeLatex;
		return this;
	}

	/**
	 * Get doesTradeItemCompositionIncludeLatex
	 * 
	 * @return doesTradeItemCompositionIncludeLatex
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getDoesTradeItemCompositionIncludeLatex() {
		return doesTradeItemCompositionIncludeLatex;
	}

	public void setDoesTradeItemCompositionIncludeLatex(CodifiedValue doesTradeItemCompositionIncludeLatex) {
		this.doesTradeItemCompositionIncludeLatex = doesTradeItemCompositionIncludeLatex;
	}

	public HealthRelatedInformation expectedResultsTime(QualifiedValues expectedResultsTime) {
		this.expectedResultsTime = expectedResultsTime;
		return this;
	}

	/**
	 * Get expectedResultsTime
	 * 
	 * @return expectedResultsTime
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getExpectedResultsTime() {
		return expectedResultsTime;
	}

	public void setExpectedResultsTime(QualifiedValues expectedResultsTime) {
		this.expectedResultsTime = expectedResultsTime;
	}

	public HealthRelatedInformation healthClaimCode(CodifiedValues healthClaimCode) {
		this.healthClaimCode = healthClaimCode;
		return this;
	}

	/**
	 * Get healthClaimCode
	 * 
	 * @return healthClaimCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValues getHealthClaimCode() {
		return healthClaimCode;
	}

	public void setHealthClaimCode(CodifiedValues healthClaimCode) {
		this.healthClaimCode = healthClaimCode;
	}

	public HealthRelatedInformation healthClaimDescription(LanguageLabels healthClaimDescription) {
		this.healthClaimDescription = healthClaimDescription;
		return this;
	}

	/**
	 * Get healthClaimDescription
	 * 
	 * @return healthClaimDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getHealthClaimDescription() {
		return healthClaimDescription;
	}

	public void setHealthClaimDescription(LanguageLabels healthClaimDescription) {
		this.healthClaimDescription = healthClaimDescription;
	}

	public HealthRelatedInformation isTradeItemChemicalNotIntendedForHumanConsumption(
			CodifiedValue isTradeItemChemicalNotIntendedForHumanConsumption) {
		this.isTradeItemChemicalNotIntendedForHumanConsumption = isTradeItemChemicalNotIntendedForHumanConsumption;
		return this;
	}

	/**
	 * Get isTradeItemChemicalNotIntendedForHumanConsumption
	 * 
	 * @return isTradeItemChemicalNotIntendedForHumanConsumption
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemChemicalNotIntendedForHumanConsumption() {
		return isTradeItemChemicalNotIntendedForHumanConsumption;
	}

	public void setIsTradeItemChemicalNotIntendedForHumanConsumption(
			CodifiedValue isTradeItemChemicalNotIntendedForHumanConsumption) {
		this.isTradeItemChemicalNotIntendedForHumanConsumption = isTradeItemChemicalNotIntendedForHumanConsumption;
	}

	public HealthRelatedInformation nutritionalLabelTypeCode(CodifiedValues nutritionalLabelTypeCode) {
		this.nutritionalLabelTypeCode = nutritionalLabelTypeCode;
		return this;
	}

	/**
	 * Get nutritionalLabelTypeCode
	 * 
	 * @return nutritionalLabelTypeCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValues getNutritionalLabelTypeCode() {
		return nutritionalLabelTypeCode;
	}

	public void setNutritionalLabelTypeCode(CodifiedValues nutritionalLabelTypeCode) {
		this.nutritionalLabelTypeCode = nutritionalLabelTypeCode;
	}

	public HealthRelatedInformation nutritionalProgramCode(CodifiedValues nutritionalProgramCode) {
		this.nutritionalProgramCode = nutritionalProgramCode;
		return this;
	}

	/**
	 * Get nutritionalProgramCode
	 * 
	 * @return nutritionalProgramCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValues getNutritionalProgramCode() {
		return nutritionalProgramCode;
	}

	public void setNutritionalProgramCode(CodifiedValues nutritionalProgramCode) {
		this.nutritionalProgramCode = nutritionalProgramCode;
	}

	public HealthRelatedInformation nutritionalProgramDetail(LanguageLabels nutritionalProgramDetail) {
		this.nutritionalProgramDetail = nutritionalProgramDetail;
		return this;
	}

	/**
	 * Get nutritionalProgramDetail
	 * 
	 * @return nutritionalProgramDetail
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getNutritionalProgramDetail() {
		return nutritionalProgramDetail;
	}

	public void setNutritionalProgramDetail(LanguageLabels nutritionalProgramDetail) {
		this.nutritionalProgramDetail = nutritionalProgramDetail;
	}

	public HealthRelatedInformation sunProtectionFactor(String sunProtectionFactor) {
		this.sunProtectionFactor = sunProtectionFactor;
		return this;
	}

	/**
	 * Get sunProtectionFactor
	 * 
	 * @return sunProtectionFactor
	 **/
	@ApiModelProperty(value = "")
	public String getSunProtectionFactor() {
		return sunProtectionFactor;
	}

	public void setSunProtectionFactor(String sunProtectionFactor) {
		this.sunProtectionFactor = sunProtectionFactor;
	}

	public HealthRelatedInformation tradeItemUVRating(String tradeItemUVRating) {
		this.tradeItemUVRating = tradeItemUVRating;
		return this;
	}

	/**
	 * Get tradeItemUVRating
	 * 
	 * @return tradeItemUVRating
	 **/
	@ApiModelProperty(value = "")
	public String getTradeItemUVRating() {
		return tradeItemUVRating;
	}

	public void setTradeItemUVRating(String tradeItemUVRating) {
		this.tradeItemUVRating = tradeItemUVRating;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		HealthRelatedInformation healthRelatedInformation = (HealthRelatedInformation) o;
		return Objects.equals(this.compulsoryAdditiveLabelInformation,
				healthRelatedInformation.compulsoryAdditiveLabelInformation)
				&& Objects.equals(this.doesTradeItemCompositionIncludeLatex,
						healthRelatedInformation.doesTradeItemCompositionIncludeLatex)
				&& Objects.equals(this.expectedResultsTime, healthRelatedInformation.expectedResultsTime)
				&& Objects.equals(this.healthClaimCode, healthRelatedInformation.healthClaimCode)
				&& Objects.equals(this.healthClaimDescription, healthRelatedInformation.healthClaimDescription)
				&& Objects.equals(this.isTradeItemChemicalNotIntendedForHumanConsumption,
						healthRelatedInformation.isTradeItemChemicalNotIntendedForHumanConsumption)
				&& Objects.equals(this.nutritionalLabelTypeCode, healthRelatedInformation.nutritionalLabelTypeCode)
				&& Objects.equals(this.nutritionalProgramCode, healthRelatedInformation.nutritionalProgramCode)
				&& Objects.equals(this.nutritionalProgramDetail, healthRelatedInformation.nutritionalProgramDetail)
				&& Objects.equals(this.sunProtectionFactor, healthRelatedInformation.sunProtectionFactor)
				&& Objects.equals(this.tradeItemUVRating, healthRelatedInformation.tradeItemUVRating);
	}

	@Override
	public int hashCode() {
		return Objects.hash(compulsoryAdditiveLabelInformation, doesTradeItemCompositionIncludeLatex,
				expectedResultsTime, healthClaimCode, healthClaimDescription,
				isTradeItemChemicalNotIntendedForHumanConsumption, nutritionalLabelTypeCode, nutritionalProgramCode,
				nutritionalProgramDetail, sunProtectionFactor, tradeItemUVRating);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class HealthRelatedInformation {\n");

		sb.append("    compulsoryAdditiveLabelInformation: ")
				.append(toIndentedString(compulsoryAdditiveLabelInformation)).append("\n");
		sb.append("    doesTradeItemCompositionIncludeLatex: ")
				.append(toIndentedString(doesTradeItemCompositionIncludeLatex)).append("\n");
		sb.append("    expectedResultsTime: ").append(toIndentedString(expectedResultsTime)).append("\n");
		sb.append("    healthClaimCode: ").append(toIndentedString(healthClaimCode)).append("\n");
		sb.append("    healthClaimDescription: ").append(toIndentedString(healthClaimDescription)).append("\n");
		sb.append("    isTradeItemChemicalNotIntendedForHumanConsumption: ")
				.append(toIndentedString(isTradeItemChemicalNotIntendedForHumanConsumption)).append("\n");
		sb.append("    nutritionalLabelTypeCode: ").append(toIndentedString(nutritionalLabelTypeCode)).append("\n");
		sb.append("    nutritionalProgramCode: ").append(toIndentedString(nutritionalProgramCode)).append("\n");
		sb.append("    nutritionalProgramDetail: ").append(toIndentedString(nutritionalProgramDetail)).append("\n");
		sb.append("    sunProtectionFactor: ").append(toIndentedString(sunProtectionFactor)).append("\n");
		sb.append("    tradeItemUVRating: ").append(toIndentedString(tradeItemUVRating)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
