/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.AcidificationPotential;
import org.foodauthent.oneworldsync.client.model.AquaticEutrophication;
import org.foodauthent.oneworldsync.client.model.CumulativeEnergyDemand;
import org.foodauthent.oneworldsync.client.model.FreshWaterEcotoxicityPotential;
import org.foodauthent.oneworldsync.client.model.GlobalWarmingPotential;
import org.foodauthent.oneworldsync.client.model.MassEquivalent;
import org.foodauthent.oneworldsync.client.model.ToxicityProperties;

/**
 * LifeCycleIndicators
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class LifeCycleIndicators {
	@JsonProperty("acidificationPotential")
	private AcidificationPotential acidificationPotential = null;

	@JsonProperty("aquaticEutrophication")
	private AquaticEutrophication aquaticEutrophication = null;

	@JsonProperty("cumulativeEnergyDemand")
	private List<CumulativeEnergyDemand> cumulativeEnergyDemand = null;

	@JsonProperty("freshWaterEcotoxicityPotential")
	private FreshWaterEcotoxicityPotential freshWaterEcotoxicityPotential = null;

	@JsonProperty("globalWarmingPotential")
	private List<GlobalWarmingPotential> globalWarmingPotential = null;

	@JsonProperty("massEquivalent")
	private List<MassEquivalent> massEquivalent = null;

	@JsonProperty("toxicityProperties")
	private List<ToxicityProperties> toxicityProperties = null;

	public LifeCycleIndicators acidificationPotential(AcidificationPotential acidificationPotential) {
		this.acidificationPotential = acidificationPotential;
		return this;
	}

	/**
	 * Get acidificationPotential
	 * 
	 * @return acidificationPotential
	 **/
	@ApiModelProperty(value = "")
	public AcidificationPotential getAcidificationPotential() {
		return acidificationPotential;
	}

	public void setAcidificationPotential(AcidificationPotential acidificationPotential) {
		this.acidificationPotential = acidificationPotential;
	}

	public LifeCycleIndicators aquaticEutrophication(AquaticEutrophication aquaticEutrophication) {
		this.aquaticEutrophication = aquaticEutrophication;
		return this;
	}

	/**
	 * Get aquaticEutrophication
	 * 
	 * @return aquaticEutrophication
	 **/
	@ApiModelProperty(value = "")
	public AquaticEutrophication getAquaticEutrophication() {
		return aquaticEutrophication;
	}

	public void setAquaticEutrophication(AquaticEutrophication aquaticEutrophication) {
		this.aquaticEutrophication = aquaticEutrophication;
	}

	public LifeCycleIndicators cumulativeEnergyDemand(List<CumulativeEnergyDemand> cumulativeEnergyDemand) {
		this.cumulativeEnergyDemand = cumulativeEnergyDemand;
		return this;
	}

	public LifeCycleIndicators addCumulativeEnergyDemandItem(CumulativeEnergyDemand cumulativeEnergyDemandItem) {
		if (this.cumulativeEnergyDemand == null) {
			this.cumulativeEnergyDemand = new ArrayList<CumulativeEnergyDemand>();
		}
		this.cumulativeEnergyDemand.add(cumulativeEnergyDemandItem);
		return this;
	}

	/**
	 * Get cumulativeEnergyDemand
	 * 
	 * @return cumulativeEnergyDemand
	 **/
	@ApiModelProperty(value = "")
	public List<CumulativeEnergyDemand> getCumulativeEnergyDemand() {
		return cumulativeEnergyDemand;
	}

	public void setCumulativeEnergyDemand(List<CumulativeEnergyDemand> cumulativeEnergyDemand) {
		this.cumulativeEnergyDemand = cumulativeEnergyDemand;
	}

	public LifeCycleIndicators freshWaterEcotoxicityPotential(
			FreshWaterEcotoxicityPotential freshWaterEcotoxicityPotential) {
		this.freshWaterEcotoxicityPotential = freshWaterEcotoxicityPotential;
		return this;
	}

	/**
	 * Get freshWaterEcotoxicityPotential
	 * 
	 * @return freshWaterEcotoxicityPotential
	 **/
	@ApiModelProperty(value = "")
	public FreshWaterEcotoxicityPotential getFreshWaterEcotoxicityPotential() {
		return freshWaterEcotoxicityPotential;
	}

	public void setFreshWaterEcotoxicityPotential(FreshWaterEcotoxicityPotential freshWaterEcotoxicityPotential) {
		this.freshWaterEcotoxicityPotential = freshWaterEcotoxicityPotential;
	}

	public LifeCycleIndicators globalWarmingPotential(List<GlobalWarmingPotential> globalWarmingPotential) {
		this.globalWarmingPotential = globalWarmingPotential;
		return this;
	}

	public LifeCycleIndicators addGlobalWarmingPotentialItem(GlobalWarmingPotential globalWarmingPotentialItem) {
		if (this.globalWarmingPotential == null) {
			this.globalWarmingPotential = new ArrayList<GlobalWarmingPotential>();
		}
		this.globalWarmingPotential.add(globalWarmingPotentialItem);
		return this;
	}

	/**
	 * Get globalWarmingPotential
	 * 
	 * @return globalWarmingPotential
	 **/
	@ApiModelProperty(value = "")
	public List<GlobalWarmingPotential> getGlobalWarmingPotential() {
		return globalWarmingPotential;
	}

	public void setGlobalWarmingPotential(List<GlobalWarmingPotential> globalWarmingPotential) {
		this.globalWarmingPotential = globalWarmingPotential;
	}

	public LifeCycleIndicators massEquivalent(List<MassEquivalent> massEquivalent) {
		this.massEquivalent = massEquivalent;
		return this;
	}

	public LifeCycleIndicators addMassEquivalentItem(MassEquivalent massEquivalentItem) {
		if (this.massEquivalent == null) {
			this.massEquivalent = new ArrayList<MassEquivalent>();
		}
		this.massEquivalent.add(massEquivalentItem);
		return this;
	}

	/**
	 * Get massEquivalent
	 * 
	 * @return massEquivalent
	 **/
	@ApiModelProperty(value = "")
	public List<MassEquivalent> getMassEquivalent() {
		return massEquivalent;
	}

	public void setMassEquivalent(List<MassEquivalent> massEquivalent) {
		this.massEquivalent = massEquivalent;
	}

	public LifeCycleIndicators toxicityProperties(List<ToxicityProperties> toxicityProperties) {
		this.toxicityProperties = toxicityProperties;
		return this;
	}

	public LifeCycleIndicators addToxicityPropertiesItem(ToxicityProperties toxicityPropertiesItem) {
		if (this.toxicityProperties == null) {
			this.toxicityProperties = new ArrayList<ToxicityProperties>();
		}
		this.toxicityProperties.add(toxicityPropertiesItem);
		return this;
	}

	/**
	 * Get toxicityProperties
	 * 
	 * @return toxicityProperties
	 **/
	@ApiModelProperty(value = "")
	public List<ToxicityProperties> getToxicityProperties() {
		return toxicityProperties;
	}

	public void setToxicityProperties(List<ToxicityProperties> toxicityProperties) {
		this.toxicityProperties = toxicityProperties;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		LifeCycleIndicators lifeCycleIndicators = (LifeCycleIndicators) o;
		return Objects.equals(this.acidificationPotential, lifeCycleIndicators.acidificationPotential)
				&& Objects.equals(this.aquaticEutrophication, lifeCycleIndicators.aquaticEutrophication)
				&& Objects.equals(this.cumulativeEnergyDemand, lifeCycleIndicators.cumulativeEnergyDemand)
				&& Objects.equals(this.freshWaterEcotoxicityPotential,
						lifeCycleIndicators.freshWaterEcotoxicityPotential)
				&& Objects.equals(this.globalWarmingPotential, lifeCycleIndicators.globalWarmingPotential)
				&& Objects.equals(this.massEquivalent, lifeCycleIndicators.massEquivalent)
				&& Objects.equals(this.toxicityProperties, lifeCycleIndicators.toxicityProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(acidificationPotential, aquaticEutrophication, cumulativeEnergyDemand,
				freshWaterEcotoxicityPotential, globalWarmingPotential, massEquivalent, toxicityProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LifeCycleIndicators {\n");

		sb.append("    acidificationPotential: ").append(toIndentedString(acidificationPotential)).append("\n");
		sb.append("    aquaticEutrophication: ").append(toIndentedString(aquaticEutrophication)).append("\n");
		sb.append("    cumulativeEnergyDemand: ").append(toIndentedString(cumulativeEnergyDemand)).append("\n");
		sb.append("    freshWaterEcotoxicityPotential: ").append(toIndentedString(freshWaterEcotoxicityPotential))
				.append("\n");
		sb.append("    globalWarmingPotential: ").append(toIndentedString(globalWarmingPotential)).append("\n");
		sb.append("    massEquivalent: ").append(toIndentedString(massEquivalent)).append("\n");
		sb.append("    toxicityProperties: ").append(toIndentedString(toxicityProperties)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
