/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.MassEquivalentSubstanceCodeReference;
import org.foodauthent.oneworldsync.client.model.QualifiedValue;

/**
 * MassEquivalent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class MassEquivalent {
	@JsonProperty("massEquivalentCode")
	private CodifiedValue massEquivalentCode = null;

	@JsonProperty("massEquivalentMeasurement")
	private QualifiedValue massEquivalentMeasurement = null;

	@JsonProperty("massEquivalentProtocolCode")
	private CodifiedValue massEquivalentProtocolCode = null;

	@JsonProperty("massEquivalentProtocolDescription")
	private LanguageLabels massEquivalentProtocolDescription = null;

	@JsonProperty("massEquivalentSubstanceCodeReference")
	private List<MassEquivalentSubstanceCodeReference> massEquivalentSubstanceCodeReference = null;

	@JsonProperty("massEquivalentSubstanceDescription")
	private LanguageLabels massEquivalentSubstanceDescription = null;

	public MassEquivalent massEquivalentCode(CodifiedValue massEquivalentCode) {
		this.massEquivalentCode = massEquivalentCode;
		return this;
	}

	/**
	 * Get massEquivalentCode
	 * 
	 * @return massEquivalentCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getMassEquivalentCode() {
		return massEquivalentCode;
	}

	public void setMassEquivalentCode(CodifiedValue massEquivalentCode) {
		this.massEquivalentCode = massEquivalentCode;
	}

	public MassEquivalent massEquivalentMeasurement(QualifiedValue massEquivalentMeasurement) {
		this.massEquivalentMeasurement = massEquivalentMeasurement;
		return this;
	}

	/**
	 * Get massEquivalentMeasurement
	 * 
	 * @return massEquivalentMeasurement
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValue getMassEquivalentMeasurement() {
		return massEquivalentMeasurement;
	}

	public void setMassEquivalentMeasurement(QualifiedValue massEquivalentMeasurement) {
		this.massEquivalentMeasurement = massEquivalentMeasurement;
	}

	public MassEquivalent massEquivalentProtocolCode(CodifiedValue massEquivalentProtocolCode) {
		this.massEquivalentProtocolCode = massEquivalentProtocolCode;
		return this;
	}

	/**
	 * Get massEquivalentProtocolCode
	 * 
	 * @return massEquivalentProtocolCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getMassEquivalentProtocolCode() {
		return massEquivalentProtocolCode;
	}

	public void setMassEquivalentProtocolCode(CodifiedValue massEquivalentProtocolCode) {
		this.massEquivalentProtocolCode = massEquivalentProtocolCode;
	}

	public MassEquivalent massEquivalentProtocolDescription(LanguageLabels massEquivalentProtocolDescription) {
		this.massEquivalentProtocolDescription = massEquivalentProtocolDescription;
		return this;
	}

	/**
	 * Get massEquivalentProtocolDescription
	 * 
	 * @return massEquivalentProtocolDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getMassEquivalentProtocolDescription() {
		return massEquivalentProtocolDescription;
	}

	public void setMassEquivalentProtocolDescription(LanguageLabels massEquivalentProtocolDescription) {
		this.massEquivalentProtocolDescription = massEquivalentProtocolDescription;
	}

	public MassEquivalent massEquivalentSubstanceCodeReference(
			List<MassEquivalentSubstanceCodeReference> massEquivalentSubstanceCodeReference) {
		this.massEquivalentSubstanceCodeReference = massEquivalentSubstanceCodeReference;
		return this;
	}

	public MassEquivalent addMassEquivalentSubstanceCodeReferenceItem(
			MassEquivalentSubstanceCodeReference massEquivalentSubstanceCodeReferenceItem) {
		if (this.massEquivalentSubstanceCodeReference == null) {
			this.massEquivalentSubstanceCodeReference = new ArrayList<MassEquivalentSubstanceCodeReference>();
		}
		this.massEquivalentSubstanceCodeReference.add(massEquivalentSubstanceCodeReferenceItem);
		return this;
	}

	/**
	 * Get massEquivalentSubstanceCodeReference
	 * 
	 * @return massEquivalentSubstanceCodeReference
	 **/
	@ApiModelProperty(value = "")
	public List<MassEquivalentSubstanceCodeReference> getMassEquivalentSubstanceCodeReference() {
		return massEquivalentSubstanceCodeReference;
	}

	public void setMassEquivalentSubstanceCodeReference(
			List<MassEquivalentSubstanceCodeReference> massEquivalentSubstanceCodeReference) {
		this.massEquivalentSubstanceCodeReference = massEquivalentSubstanceCodeReference;
	}

	public MassEquivalent massEquivalentSubstanceDescription(LanguageLabels massEquivalentSubstanceDescription) {
		this.massEquivalentSubstanceDescription = massEquivalentSubstanceDescription;
		return this;
	}

	/**
	 * Get massEquivalentSubstanceDescription
	 * 
	 * @return massEquivalentSubstanceDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getMassEquivalentSubstanceDescription() {
		return massEquivalentSubstanceDescription;
	}

	public void setMassEquivalentSubstanceDescription(LanguageLabels massEquivalentSubstanceDescription) {
		this.massEquivalentSubstanceDescription = massEquivalentSubstanceDescription;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		MassEquivalent massEquivalent = (MassEquivalent) o;
		return Objects.equals(this.massEquivalentCode, massEquivalent.massEquivalentCode)
				&& Objects.equals(this.massEquivalentMeasurement, massEquivalent.massEquivalentMeasurement)
				&& Objects.equals(this.massEquivalentProtocolCode, massEquivalent.massEquivalentProtocolCode)
				&& Objects.equals(this.massEquivalentProtocolDescription,
						massEquivalent.massEquivalentProtocolDescription)
				&& Objects.equals(this.massEquivalentSubstanceCodeReference,
						massEquivalent.massEquivalentSubstanceCodeReference)
				&& Objects.equals(this.massEquivalentSubstanceDescription,
						massEquivalent.massEquivalentSubstanceDescription);
	}

	@Override
	public int hashCode() {
		return Objects.hash(massEquivalentCode, massEquivalentMeasurement, massEquivalentProtocolCode,
				massEquivalentProtocolDescription, massEquivalentSubstanceCodeReference,
				massEquivalentSubstanceDescription);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class MassEquivalent {\n");

		sb.append("    massEquivalentCode: ").append(toIndentedString(massEquivalentCode)).append("\n");
		sb.append("    massEquivalentMeasurement: ").append(toIndentedString(massEquivalentMeasurement)).append("\n");
		sb.append("    massEquivalentProtocolCode: ").append(toIndentedString(massEquivalentProtocolCode)).append("\n");
		sb.append("    massEquivalentProtocolDescription: ").append(toIndentedString(massEquivalentProtocolDescription))
				.append("\n");
		sb.append("    massEquivalentSubstanceCodeReference: ")
				.append(toIndentedString(massEquivalentSubstanceCodeReference)).append("\n");
		sb.append("    massEquivalentSubstanceDescription: ")
				.append(toIndentedString(massEquivalentSubstanceDescription)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
