/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;

/**
 * OrderableReturnableInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class OrderableReturnableInformation {
	@JsonProperty("firstReturnableDateTime")
	private String firstReturnableDateTime = null;

	@JsonProperty("isNonSoldTradeItemReturnable")
	private String isNonSoldTradeItemReturnable = null;

	@JsonProperty("lastReturnableDateTime")
	private String lastReturnableDateTime = null;

	@JsonProperty("orderableReturnableConditionsCode")
	private CodifiedValue orderableReturnableConditionsCode = null;

	@JsonProperty("returnGoodsPolicyCode")
	private CodifiedValue returnGoodsPolicyCode = null;

	public OrderableReturnableInformation firstReturnableDateTime(String firstReturnableDateTime) {
		this.firstReturnableDateTime = firstReturnableDateTime;
		return this;
	}

	/**
	 * Get firstReturnableDateTime
	 * 
	 * @return firstReturnableDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getFirstReturnableDateTime() {
		return firstReturnableDateTime;
	}

	public void setFirstReturnableDateTime(String firstReturnableDateTime) {
		this.firstReturnableDateTime = firstReturnableDateTime;
	}

	public OrderableReturnableInformation isNonSoldTradeItemReturnable(String isNonSoldTradeItemReturnable) {
		this.isNonSoldTradeItemReturnable = isNonSoldTradeItemReturnable;
		return this;
	}

	/**
	 * Get isNonSoldTradeItemReturnable
	 * 
	 * @return isNonSoldTradeItemReturnable
	 **/
	@ApiModelProperty(value = "")
	public String getIsNonSoldTradeItemReturnable() {
		return isNonSoldTradeItemReturnable;
	}

	public void setIsNonSoldTradeItemReturnable(String isNonSoldTradeItemReturnable) {
		this.isNonSoldTradeItemReturnable = isNonSoldTradeItemReturnable;
	}

	public OrderableReturnableInformation lastReturnableDateTime(String lastReturnableDateTime) {
		this.lastReturnableDateTime = lastReturnableDateTime;
		return this;
	}

	/**
	 * Get lastReturnableDateTime
	 * 
	 * @return lastReturnableDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getLastReturnableDateTime() {
		return lastReturnableDateTime;
	}

	public void setLastReturnableDateTime(String lastReturnableDateTime) {
		this.lastReturnableDateTime = lastReturnableDateTime;
	}

	public OrderableReturnableInformation orderableReturnableConditionsCode(
			CodifiedValue orderableReturnableConditionsCode) {
		this.orderableReturnableConditionsCode = orderableReturnableConditionsCode;
		return this;
	}

	/**
	 * Get orderableReturnableConditionsCode
	 * 
	 * @return orderableReturnableConditionsCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getOrderableReturnableConditionsCode() {
		return orderableReturnableConditionsCode;
	}

	public void setOrderableReturnableConditionsCode(CodifiedValue orderableReturnableConditionsCode) {
		this.orderableReturnableConditionsCode = orderableReturnableConditionsCode;
	}

	public OrderableReturnableInformation returnGoodsPolicyCode(CodifiedValue returnGoodsPolicyCode) {
		this.returnGoodsPolicyCode = returnGoodsPolicyCode;
		return this;
	}

	/**
	 * Get returnGoodsPolicyCode
	 * 
	 * @return returnGoodsPolicyCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getReturnGoodsPolicyCode() {
		return returnGoodsPolicyCode;
	}

	public void setReturnGoodsPolicyCode(CodifiedValue returnGoodsPolicyCode) {
		this.returnGoodsPolicyCode = returnGoodsPolicyCode;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		OrderableReturnableInformation orderableReturnableInformation = (OrderableReturnableInformation) o;
		return Objects.equals(this.firstReturnableDateTime, orderableReturnableInformation.firstReturnableDateTime)
				&& Objects.equals(this.isNonSoldTradeItemReturnable,
						orderableReturnableInformation.isNonSoldTradeItemReturnable)
				&& Objects.equals(this.lastReturnableDateTime, orderableReturnableInformation.lastReturnableDateTime)
				&& Objects.equals(this.orderableReturnableConditionsCode,
						orderableReturnableInformation.orderableReturnableConditionsCode)
				&& Objects.equals(this.returnGoodsPolicyCode, orderableReturnableInformation.returnGoodsPolicyCode);
	}

	@Override
	public int hashCode() {
		return Objects.hash(firstReturnableDateTime, isNonSoldTradeItemReturnable, lastReturnableDateTime,
				orderableReturnableConditionsCode, returnGoodsPolicyCode);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OrderableReturnableInformation {\n");

		sb.append("    firstReturnableDateTime: ").append(toIndentedString(firstReturnableDateTime)).append("\n");
		sb.append("    isNonSoldTradeItemReturnable: ").append(toIndentedString(isNonSoldTradeItemReturnable))
				.append("\n");
		sb.append("    lastReturnableDateTime: ").append(toIndentedString(lastReturnableDateTime)).append("\n");
		sb.append("    orderableReturnableConditionsCode: ").append(toIndentedString(orderableReturnableConditionsCode))
				.append("\n");
		sb.append("    returnGoodsPolicyCode: ").append(toIndentedString(returnGoodsPolicyCode)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
