/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.IndividualPackagingComponentLevel;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.LifeCycleIndicators;
import org.foodauthent.oneworldsync.client.model.PackagingSustainabilityEconomicIndicators;
import org.foodauthent.oneworldsync.client.model.QualifiedValues;

/**
 * PackagingSustainabilityModule
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class PackagingSustainabilityModule {
	@JsonProperty("functionalBasisUnitCode")
	private CodifiedValue functionalBasisUnitCode = null;

	@JsonProperty("functionalBasisUnitDescription")
	private LanguageLabels functionalBasisUnitDescription = null;

	@JsonProperty("individualPackagingComponentLevel")
	private List<IndividualPackagingComponentLevel> individualPackagingComponentLevel = null;

	@JsonProperty("lifeCycleIndicators")
	private LifeCycleIndicators lifeCycleIndicators = null;

	@JsonProperty("packagingCubeUtilisationRatio")
	private String packagingCubeUtilisationRatio = null;

	@JsonProperty("packagingSustainabilityEconomicIndicators")
	private PackagingSustainabilityEconomicIndicators packagingSustainabilityEconomicIndicators = null;

	@JsonProperty("packagingToTradeItemWeightRatio")
	private String packagingToTradeItemWeightRatio = null;

	@JsonProperty("packagingWeightPerConsumerUse")
	private QualifiedValues packagingWeightPerConsumerUse = null;

	@JsonProperty("quantityOfFunctionalBasisUnit")
	private QualifiedValues quantityOfFunctionalBasisUnit = null;

	public PackagingSustainabilityModule functionalBasisUnitCode(CodifiedValue functionalBasisUnitCode) {
		this.functionalBasisUnitCode = functionalBasisUnitCode;
		return this;
	}

	/**
	 * Get functionalBasisUnitCode
	 * 
	 * @return functionalBasisUnitCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getFunctionalBasisUnitCode() {
		return functionalBasisUnitCode;
	}

	public void setFunctionalBasisUnitCode(CodifiedValue functionalBasisUnitCode) {
		this.functionalBasisUnitCode = functionalBasisUnitCode;
	}

	public PackagingSustainabilityModule functionalBasisUnitDescription(LanguageLabels functionalBasisUnitDescription) {
		this.functionalBasisUnitDescription = functionalBasisUnitDescription;
		return this;
	}

	/**
	 * Get functionalBasisUnitDescription
	 * 
	 * @return functionalBasisUnitDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getFunctionalBasisUnitDescription() {
		return functionalBasisUnitDescription;
	}

	public void setFunctionalBasisUnitDescription(LanguageLabels functionalBasisUnitDescription) {
		this.functionalBasisUnitDescription = functionalBasisUnitDescription;
	}

	public PackagingSustainabilityModule individualPackagingComponentLevel(
			List<IndividualPackagingComponentLevel> individualPackagingComponentLevel) {
		this.individualPackagingComponentLevel = individualPackagingComponentLevel;
		return this;
	}

	public PackagingSustainabilityModule addIndividualPackagingComponentLevelItem(
			IndividualPackagingComponentLevel individualPackagingComponentLevelItem) {
		if (this.individualPackagingComponentLevel == null) {
			this.individualPackagingComponentLevel = new ArrayList<IndividualPackagingComponentLevel>();
		}
		this.individualPackagingComponentLevel.add(individualPackagingComponentLevelItem);
		return this;
	}

	/**
	 * Get individualPackagingComponentLevel
	 * 
	 * @return individualPackagingComponentLevel
	 **/
	@ApiModelProperty(value = "")
	public List<IndividualPackagingComponentLevel> getIndividualPackagingComponentLevel() {
		return individualPackagingComponentLevel;
	}

	public void setIndividualPackagingComponentLevel(
			List<IndividualPackagingComponentLevel> individualPackagingComponentLevel) {
		this.individualPackagingComponentLevel = individualPackagingComponentLevel;
	}

	public PackagingSustainabilityModule lifeCycleIndicators(LifeCycleIndicators lifeCycleIndicators) {
		this.lifeCycleIndicators = lifeCycleIndicators;
		return this;
	}

	/**
	 * Get lifeCycleIndicators
	 * 
	 * @return lifeCycleIndicators
	 **/
	@ApiModelProperty(value = "")
	public LifeCycleIndicators getLifeCycleIndicators() {
		return lifeCycleIndicators;
	}

	public void setLifeCycleIndicators(LifeCycleIndicators lifeCycleIndicators) {
		this.lifeCycleIndicators = lifeCycleIndicators;
	}

	public PackagingSustainabilityModule packagingCubeUtilisationRatio(String packagingCubeUtilisationRatio) {
		this.packagingCubeUtilisationRatio = packagingCubeUtilisationRatio;
		return this;
	}

	/**
	 * Get packagingCubeUtilisationRatio
	 * 
	 * @return packagingCubeUtilisationRatio
	 **/
	@ApiModelProperty(value = "")
	public String getPackagingCubeUtilisationRatio() {
		return packagingCubeUtilisationRatio;
	}

	public void setPackagingCubeUtilisationRatio(String packagingCubeUtilisationRatio) {
		this.packagingCubeUtilisationRatio = packagingCubeUtilisationRatio;
	}

	public PackagingSustainabilityModule packagingSustainabilityEconomicIndicators(
			PackagingSustainabilityEconomicIndicators packagingSustainabilityEconomicIndicators) {
		this.packagingSustainabilityEconomicIndicators = packagingSustainabilityEconomicIndicators;
		return this;
	}

	/**
	 * Get packagingSustainabilityEconomicIndicators
	 * 
	 * @return packagingSustainabilityEconomicIndicators
	 **/
	@ApiModelProperty(value = "")
	public PackagingSustainabilityEconomicIndicators getPackagingSustainabilityEconomicIndicators() {
		return packagingSustainabilityEconomicIndicators;
	}

	public void setPackagingSustainabilityEconomicIndicators(
			PackagingSustainabilityEconomicIndicators packagingSustainabilityEconomicIndicators) {
		this.packagingSustainabilityEconomicIndicators = packagingSustainabilityEconomicIndicators;
	}

	public PackagingSustainabilityModule packagingToTradeItemWeightRatio(String packagingToTradeItemWeightRatio) {
		this.packagingToTradeItemWeightRatio = packagingToTradeItemWeightRatio;
		return this;
	}

	/**
	 * Get packagingToTradeItemWeightRatio
	 * 
	 * @return packagingToTradeItemWeightRatio
	 **/
	@ApiModelProperty(value = "")
	public String getPackagingToTradeItemWeightRatio() {
		return packagingToTradeItemWeightRatio;
	}

	public void setPackagingToTradeItemWeightRatio(String packagingToTradeItemWeightRatio) {
		this.packagingToTradeItemWeightRatio = packagingToTradeItemWeightRatio;
	}

	public PackagingSustainabilityModule packagingWeightPerConsumerUse(QualifiedValues packagingWeightPerConsumerUse) {
		this.packagingWeightPerConsumerUse = packagingWeightPerConsumerUse;
		return this;
	}

	/**
	 * Get packagingWeightPerConsumerUse
	 * 
	 * @return packagingWeightPerConsumerUse
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getPackagingWeightPerConsumerUse() {
		return packagingWeightPerConsumerUse;
	}

	public void setPackagingWeightPerConsumerUse(QualifiedValues packagingWeightPerConsumerUse) {
		this.packagingWeightPerConsumerUse = packagingWeightPerConsumerUse;
	}

	public PackagingSustainabilityModule quantityOfFunctionalBasisUnit(QualifiedValues quantityOfFunctionalBasisUnit) {
		this.quantityOfFunctionalBasisUnit = quantityOfFunctionalBasisUnit;
		return this;
	}

	/**
	 * Get quantityOfFunctionalBasisUnit
	 * 
	 * @return quantityOfFunctionalBasisUnit
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getQuantityOfFunctionalBasisUnit() {
		return quantityOfFunctionalBasisUnit;
	}

	public void setQuantityOfFunctionalBasisUnit(QualifiedValues quantityOfFunctionalBasisUnit) {
		this.quantityOfFunctionalBasisUnit = quantityOfFunctionalBasisUnit;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PackagingSustainabilityModule packagingSustainabilityModule = (PackagingSustainabilityModule) o;
		return Objects.equals(this.functionalBasisUnitCode, packagingSustainabilityModule.functionalBasisUnitCode)
				&& Objects.equals(this.functionalBasisUnitDescription,
						packagingSustainabilityModule.functionalBasisUnitDescription)
				&& Objects.equals(this.individualPackagingComponentLevel,
						packagingSustainabilityModule.individualPackagingComponentLevel)
				&& Objects.equals(this.lifeCycleIndicators, packagingSustainabilityModule.lifeCycleIndicators)
				&& Objects.equals(this.packagingCubeUtilisationRatio,
						packagingSustainabilityModule.packagingCubeUtilisationRatio)
				&& Objects.equals(this.packagingSustainabilityEconomicIndicators,
						packagingSustainabilityModule.packagingSustainabilityEconomicIndicators)
				&& Objects.equals(this.packagingToTradeItemWeightRatio,
						packagingSustainabilityModule.packagingToTradeItemWeightRatio)
				&& Objects.equals(this.packagingWeightPerConsumerUse,
						packagingSustainabilityModule.packagingWeightPerConsumerUse)
				&& Objects.equals(this.quantityOfFunctionalBasisUnit,
						packagingSustainabilityModule.quantityOfFunctionalBasisUnit);
	}

	@Override
	public int hashCode() {
		return Objects.hash(functionalBasisUnitCode, functionalBasisUnitDescription, individualPackagingComponentLevel,
				lifeCycleIndicators, packagingCubeUtilisationRatio, packagingSustainabilityEconomicIndicators,
				packagingToTradeItemWeightRatio, packagingWeightPerConsumerUse, quantityOfFunctionalBasisUnit);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PackagingSustainabilityModule {\n");

		sb.append("    functionalBasisUnitCode: ").append(toIndentedString(functionalBasisUnitCode)).append("\n");
		sb.append("    functionalBasisUnitDescription: ").append(toIndentedString(functionalBasisUnitDescription))
				.append("\n");
		sb.append("    individualPackagingComponentLevel: ").append(toIndentedString(individualPackagingComponentLevel))
				.append("\n");
		sb.append("    lifeCycleIndicators: ").append(toIndentedString(lifeCycleIndicators)).append("\n");
		sb.append("    packagingCubeUtilisationRatio: ").append(toIndentedString(packagingCubeUtilisationRatio))
				.append("\n");
		sb.append("    packagingSustainabilityEconomicIndicators: ")
				.append(toIndentedString(packagingSustainabilityEconomicIndicators)).append("\n");
		sb.append("    packagingToTradeItemWeightRatio: ").append(toIndentedString(packagingToTradeItemWeightRatio))
				.append("\n");
		sb.append("    packagingWeightPerConsumerUse: ").append(toIndentedString(packagingWeightPerConsumerUse))
				.append("\n");
		sb.append("    quantityOfFunctionalBasisUnit: ").append(toIndentedString(quantityOfFunctionalBasisUnit))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
