/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;

/**
 * PackagingChainOfCustody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class PackagingChainOfCustody {
	@JsonProperty("packagingChainOfCustodyEventSequenceNumber")
	private String packagingChainOfCustodyEventSequenceNumber = null;

	@JsonProperty("packagingChainOfCustodySourceCertifiedCode")
	private CodifiedValue packagingChainOfCustodySourceCertifiedCode = null;

	@JsonProperty("sourceCertificationSystemProtocolCode")
	private CodifiedValue sourceCertificationSystemProtocolCode = null;

	@JsonProperty("sourceCertificationSystemProtocolDescription")
	private LanguageLabels sourceCertificationSystemProtocolDescription = null;

	public PackagingChainOfCustody packagingChainOfCustodyEventSequenceNumber(
			String packagingChainOfCustodyEventSequenceNumber) {
		this.packagingChainOfCustodyEventSequenceNumber = packagingChainOfCustodyEventSequenceNumber;
		return this;
	}

	/**
	 * Get packagingChainOfCustodyEventSequenceNumber
	 * 
	 * @return packagingChainOfCustodyEventSequenceNumber
	 **/
	@ApiModelProperty(value = "")
	public String getPackagingChainOfCustodyEventSequenceNumber() {
		return packagingChainOfCustodyEventSequenceNumber;
	}

	public void setPackagingChainOfCustodyEventSequenceNumber(String packagingChainOfCustodyEventSequenceNumber) {
		this.packagingChainOfCustodyEventSequenceNumber = packagingChainOfCustodyEventSequenceNumber;
	}

	public PackagingChainOfCustody packagingChainOfCustodySourceCertifiedCode(
			CodifiedValue packagingChainOfCustodySourceCertifiedCode) {
		this.packagingChainOfCustodySourceCertifiedCode = packagingChainOfCustodySourceCertifiedCode;
		return this;
	}

	/**
	 * Get packagingChainOfCustodySourceCertifiedCode
	 * 
	 * @return packagingChainOfCustodySourceCertifiedCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getPackagingChainOfCustodySourceCertifiedCode() {
		return packagingChainOfCustodySourceCertifiedCode;
	}

	public void setPackagingChainOfCustodySourceCertifiedCode(
			CodifiedValue packagingChainOfCustodySourceCertifiedCode) {
		this.packagingChainOfCustodySourceCertifiedCode = packagingChainOfCustodySourceCertifiedCode;
	}

	public PackagingChainOfCustody sourceCertificationSystemProtocolCode(
			CodifiedValue sourceCertificationSystemProtocolCode) {
		this.sourceCertificationSystemProtocolCode = sourceCertificationSystemProtocolCode;
		return this;
	}

	/**
	 * Get sourceCertificationSystemProtocolCode
	 * 
	 * @return sourceCertificationSystemProtocolCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getSourceCertificationSystemProtocolCode() {
		return sourceCertificationSystemProtocolCode;
	}

	public void setSourceCertificationSystemProtocolCode(CodifiedValue sourceCertificationSystemProtocolCode) {
		this.sourceCertificationSystemProtocolCode = sourceCertificationSystemProtocolCode;
	}

	public PackagingChainOfCustody sourceCertificationSystemProtocolDescription(
			LanguageLabels sourceCertificationSystemProtocolDescription) {
		this.sourceCertificationSystemProtocolDescription = sourceCertificationSystemProtocolDescription;
		return this;
	}

	/**
	 * Get sourceCertificationSystemProtocolDescription
	 * 
	 * @return sourceCertificationSystemProtocolDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getSourceCertificationSystemProtocolDescription() {
		return sourceCertificationSystemProtocolDescription;
	}

	public void setSourceCertificationSystemProtocolDescription(
			LanguageLabels sourceCertificationSystemProtocolDescription) {
		this.sourceCertificationSystemProtocolDescription = sourceCertificationSystemProtocolDescription;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PackagingChainOfCustody packagingChainOfCustody = (PackagingChainOfCustody) o;
		return Objects.equals(this.packagingChainOfCustodyEventSequenceNumber,
				packagingChainOfCustody.packagingChainOfCustodyEventSequenceNumber)
				&& Objects.equals(this.packagingChainOfCustodySourceCertifiedCode,
						packagingChainOfCustody.packagingChainOfCustodySourceCertifiedCode)
				&& Objects.equals(this.sourceCertificationSystemProtocolCode,
						packagingChainOfCustody.sourceCertificationSystemProtocolCode)
				&& Objects.equals(this.sourceCertificationSystemProtocolDescription,
						packagingChainOfCustody.sourceCertificationSystemProtocolDescription);
	}

	@Override
	public int hashCode() {
		return Objects.hash(packagingChainOfCustodyEventSequenceNumber, packagingChainOfCustodySourceCertifiedCode,
				sourceCertificationSystemProtocolCode, sourceCertificationSystemProtocolDescription);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PackagingChainOfCustody {\n");

		sb.append("    packagingChainOfCustodyEventSequenceNumber: ")
				.append(toIndentedString(packagingChainOfCustodyEventSequenceNumber)).append("\n");
		sb.append("    packagingChainOfCustodySourceCertifiedCode: ")
				.append(toIndentedString(packagingChainOfCustodySourceCertifiedCode)).append("\n");
		sb.append("    sourceCertificationSystemProtocolCode: ")
				.append(toIndentedString(sourceCertificationSystemProtocolCode)).append("\n");
		sb.append("    sourceCertificationSystemProtocolDescription: ")
				.append(toIndentedString(sourceCertificationSystemProtocolDescription)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
