/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.Dosage;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.PsychotropicSubstance;

/**
 * PharmaceuticalItemInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class PharmaceuticalItemInformation {
	@JsonProperty("dosage")
	private List<Dosage> dosage = null;

	@JsonProperty("drugInteractions")
	private LanguageLabels drugInteractions = null;

	@JsonProperty("drugPreparations")
	private LanguageLabels drugPreparations = null;

	@JsonProperty("drugSideEffectsAndWarnings")
	private LanguageLabels drugSideEffectsAndWarnings = null;

	@JsonProperty("isOrphanDrug")
	private CodifiedValue isOrphanDrug = null;

	@JsonProperty("isTradeItemConsideredDopingProduct")
	private CodifiedValue isTradeItemConsideredDopingProduct = null;

	@JsonProperty("isTradeItemMarkedNoShake")
	private CodifiedValue isTradeItemMarkedNoShake = null;

	@JsonProperty("psychotropicSubstance")
	private List<PsychotropicSubstance> psychotropicSubstance = null;

	public PharmaceuticalItemInformation dosage(List<Dosage> dosage) {
		this.dosage = dosage;
		return this;
	}

	public PharmaceuticalItemInformation addDosageItem(Dosage dosageItem) {
		if (this.dosage == null) {
			this.dosage = new ArrayList<Dosage>();
		}
		this.dosage.add(dosageItem);
		return this;
	}

	/**
	 * Get dosage
	 * 
	 * @return dosage
	 **/
	@ApiModelProperty(value = "")
	public List<Dosage> getDosage() {
		return dosage;
	}

	public void setDosage(List<Dosage> dosage) {
		this.dosage = dosage;
	}

	public PharmaceuticalItemInformation drugInteractions(LanguageLabels drugInteractions) {
		this.drugInteractions = drugInteractions;
		return this;
	}

	/**
	 * Get drugInteractions
	 * 
	 * @return drugInteractions
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getDrugInteractions() {
		return drugInteractions;
	}

	public void setDrugInteractions(LanguageLabels drugInteractions) {
		this.drugInteractions = drugInteractions;
	}

	public PharmaceuticalItemInformation drugPreparations(LanguageLabels drugPreparations) {
		this.drugPreparations = drugPreparations;
		return this;
	}

	/**
	 * Get drugPreparations
	 * 
	 * @return drugPreparations
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getDrugPreparations() {
		return drugPreparations;
	}

	public void setDrugPreparations(LanguageLabels drugPreparations) {
		this.drugPreparations = drugPreparations;
	}

	public PharmaceuticalItemInformation drugSideEffectsAndWarnings(LanguageLabels drugSideEffectsAndWarnings) {
		this.drugSideEffectsAndWarnings = drugSideEffectsAndWarnings;
		return this;
	}

	/**
	 * Get drugSideEffectsAndWarnings
	 * 
	 * @return drugSideEffectsAndWarnings
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getDrugSideEffectsAndWarnings() {
		return drugSideEffectsAndWarnings;
	}

	public void setDrugSideEffectsAndWarnings(LanguageLabels drugSideEffectsAndWarnings) {
		this.drugSideEffectsAndWarnings = drugSideEffectsAndWarnings;
	}

	public PharmaceuticalItemInformation isOrphanDrug(CodifiedValue isOrphanDrug) {
		this.isOrphanDrug = isOrphanDrug;
		return this;
	}

	/**
	 * Get isOrphanDrug
	 * 
	 * @return isOrphanDrug
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsOrphanDrug() {
		return isOrphanDrug;
	}

	public void setIsOrphanDrug(CodifiedValue isOrphanDrug) {
		this.isOrphanDrug = isOrphanDrug;
	}

	public PharmaceuticalItemInformation isTradeItemConsideredDopingProduct(
			CodifiedValue isTradeItemConsideredDopingProduct) {
		this.isTradeItemConsideredDopingProduct = isTradeItemConsideredDopingProduct;
		return this;
	}

	/**
	 * Get isTradeItemConsideredDopingProduct
	 * 
	 * @return isTradeItemConsideredDopingProduct
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemConsideredDopingProduct() {
		return isTradeItemConsideredDopingProduct;
	}

	public void setIsTradeItemConsideredDopingProduct(CodifiedValue isTradeItemConsideredDopingProduct) {
		this.isTradeItemConsideredDopingProduct = isTradeItemConsideredDopingProduct;
	}

	public PharmaceuticalItemInformation isTradeItemMarkedNoShake(CodifiedValue isTradeItemMarkedNoShake) {
		this.isTradeItemMarkedNoShake = isTradeItemMarkedNoShake;
		return this;
	}

	/**
	 * Get isTradeItemMarkedNoShake
	 * 
	 * @return isTradeItemMarkedNoShake
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemMarkedNoShake() {
		return isTradeItemMarkedNoShake;
	}

	public void setIsTradeItemMarkedNoShake(CodifiedValue isTradeItemMarkedNoShake) {
		this.isTradeItemMarkedNoShake = isTradeItemMarkedNoShake;
	}

	public PharmaceuticalItemInformation psychotropicSubstance(List<PsychotropicSubstance> psychotropicSubstance) {
		this.psychotropicSubstance = psychotropicSubstance;
		return this;
	}

	public PharmaceuticalItemInformation addPsychotropicSubstanceItem(PsychotropicSubstance psychotropicSubstanceItem) {
		if (this.psychotropicSubstance == null) {
			this.psychotropicSubstance = new ArrayList<PsychotropicSubstance>();
		}
		this.psychotropicSubstance.add(psychotropicSubstanceItem);
		return this;
	}

	/**
	 * Get psychotropicSubstance
	 * 
	 * @return psychotropicSubstance
	 **/
	@ApiModelProperty(value = "")
	public List<PsychotropicSubstance> getPsychotropicSubstance() {
		return psychotropicSubstance;
	}

	public void setPsychotropicSubstance(List<PsychotropicSubstance> psychotropicSubstance) {
		this.psychotropicSubstance = psychotropicSubstance;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PharmaceuticalItemInformation pharmaceuticalItemInformation = (PharmaceuticalItemInformation) o;
		return Objects.equals(this.dosage, pharmaceuticalItemInformation.dosage)
				&& Objects.equals(this.drugInteractions, pharmaceuticalItemInformation.drugInteractions)
				&& Objects.equals(this.drugPreparations, pharmaceuticalItemInformation.drugPreparations)
				&& Objects.equals(this.drugSideEffectsAndWarnings,
						pharmaceuticalItemInformation.drugSideEffectsAndWarnings)
				&& Objects.equals(this.isOrphanDrug, pharmaceuticalItemInformation.isOrphanDrug)
				&& Objects.equals(this.isTradeItemConsideredDopingProduct,
						pharmaceuticalItemInformation.isTradeItemConsideredDopingProduct)
				&& Objects.equals(this.isTradeItemMarkedNoShake, pharmaceuticalItemInformation.isTradeItemMarkedNoShake)
				&& Objects.equals(this.psychotropicSubstance, pharmaceuticalItemInformation.psychotropicSubstance);
	}

	@Override
	public int hashCode() {
		return Objects.hash(dosage, drugInteractions, drugPreparations, drugSideEffectsAndWarnings, isOrphanDrug,
				isTradeItemConsideredDopingProduct, isTradeItemMarkedNoShake, psychotropicSubstance);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PharmaceuticalItemInformation {\n");

		sb.append("    dosage: ").append(toIndentedString(dosage)).append("\n");
		sb.append("    drugInteractions: ").append(toIndentedString(drugInteractions)).append("\n");
		sb.append("    drugPreparations: ").append(toIndentedString(drugPreparations)).append("\n");
		sb.append("    drugSideEffectsAndWarnings: ").append(toIndentedString(drugSideEffectsAndWarnings)).append("\n");
		sb.append("    isOrphanDrug: ").append(toIndentedString(isOrphanDrug)).append("\n");
		sb.append("    isTradeItemConsideredDopingProduct: ")
				.append(toIndentedString(isTradeItemConsideredDopingProduct)).append("\n");
		sb.append("    isTradeItemMarkedNoShake: ").append(toIndentedString(isTradeItemMarkedNoShake)).append("\n");
		sb.append("    psychotropicSubstance: ").append(toIndentedString(psychotropicSubstance)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
