/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.QualifiedValues;

/**
 * ProductCharacteristics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class ProductCharacteristics {
	@JsonProperty("productCharacteristicCode")
	private CodifiedValue productCharacteristicCode = null;

	@JsonProperty("productCharacteristicValueAmount")
	private QualifiedValues productCharacteristicValueAmount = null;

	@JsonProperty("productCharacteristicValueCode")
	private String productCharacteristicValueCode = null;

	@JsonProperty("productCharacteristicValueDateTime")
	private String productCharacteristicValueDateTime = null;

	@JsonProperty("productCharacteristicValueDescription")
	private LanguageLabels productCharacteristicValueDescription = null;

	@JsonProperty("productCharacteristicValueInteger")
	private String productCharacteristicValueInteger = null;

	@JsonProperty("productCharacteristicValueMeasurement")
	private QualifiedValues productCharacteristicValueMeasurement = null;

	@JsonProperty("productCharacteristicValueNumeric")
	private String productCharacteristicValueNumeric = null;

	@JsonProperty("productCharacteristicValueString")
	private String productCharacteristicValueString = null;

	public ProductCharacteristics productCharacteristicCode(CodifiedValue productCharacteristicCode) {
		this.productCharacteristicCode = productCharacteristicCode;
		return this;
	}

	/**
	 * Get productCharacteristicCode
	 * 
	 * @return productCharacteristicCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getProductCharacteristicCode() {
		return productCharacteristicCode;
	}

	public void setProductCharacteristicCode(CodifiedValue productCharacteristicCode) {
		this.productCharacteristicCode = productCharacteristicCode;
	}

	public ProductCharacteristics productCharacteristicValueAmount(QualifiedValues productCharacteristicValueAmount) {
		this.productCharacteristicValueAmount = productCharacteristicValueAmount;
		return this;
	}

	/**
	 * Get productCharacteristicValueAmount
	 * 
	 * @return productCharacteristicValueAmount
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getProductCharacteristicValueAmount() {
		return productCharacteristicValueAmount;
	}

	public void setProductCharacteristicValueAmount(QualifiedValues productCharacteristicValueAmount) {
		this.productCharacteristicValueAmount = productCharacteristicValueAmount;
	}

	public ProductCharacteristics productCharacteristicValueCode(String productCharacteristicValueCode) {
		this.productCharacteristicValueCode = productCharacteristicValueCode;
		return this;
	}

	/**
	 * Get productCharacteristicValueCode
	 * 
	 * @return productCharacteristicValueCode
	 **/
	@ApiModelProperty(value = "")
	public String getProductCharacteristicValueCode() {
		return productCharacteristicValueCode;
	}

	public void setProductCharacteristicValueCode(String productCharacteristicValueCode) {
		this.productCharacteristicValueCode = productCharacteristicValueCode;
	}

	public ProductCharacteristics productCharacteristicValueDateTime(String productCharacteristicValueDateTime) {
		this.productCharacteristicValueDateTime = productCharacteristicValueDateTime;
		return this;
	}

	/**
	 * Get productCharacteristicValueDateTime
	 * 
	 * @return productCharacteristicValueDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getProductCharacteristicValueDateTime() {
		return productCharacteristicValueDateTime;
	}

	public void setProductCharacteristicValueDateTime(String productCharacteristicValueDateTime) {
		this.productCharacteristicValueDateTime = productCharacteristicValueDateTime;
	}

	public ProductCharacteristics productCharacteristicValueDescription(
			LanguageLabels productCharacteristicValueDescription) {
		this.productCharacteristicValueDescription = productCharacteristicValueDescription;
		return this;
	}

	/**
	 * Get productCharacteristicValueDescription
	 * 
	 * @return productCharacteristicValueDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getProductCharacteristicValueDescription() {
		return productCharacteristicValueDescription;
	}

	public void setProductCharacteristicValueDescription(LanguageLabels productCharacteristicValueDescription) {
		this.productCharacteristicValueDescription = productCharacteristicValueDescription;
	}

	public ProductCharacteristics productCharacteristicValueInteger(String productCharacteristicValueInteger) {
		this.productCharacteristicValueInteger = productCharacteristicValueInteger;
		return this;
	}

	/**
	 * Get productCharacteristicValueInteger
	 * 
	 * @return productCharacteristicValueInteger
	 **/
	@ApiModelProperty(value = "")
	public String getProductCharacteristicValueInteger() {
		return productCharacteristicValueInteger;
	}

	public void setProductCharacteristicValueInteger(String productCharacteristicValueInteger) {
		this.productCharacteristicValueInteger = productCharacteristicValueInteger;
	}

	public ProductCharacteristics productCharacteristicValueMeasurement(
			QualifiedValues productCharacteristicValueMeasurement) {
		this.productCharacteristicValueMeasurement = productCharacteristicValueMeasurement;
		return this;
	}

	/**
	 * Get productCharacteristicValueMeasurement
	 * 
	 * @return productCharacteristicValueMeasurement
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValues getProductCharacteristicValueMeasurement() {
		return productCharacteristicValueMeasurement;
	}

	public void setProductCharacteristicValueMeasurement(QualifiedValues productCharacteristicValueMeasurement) {
		this.productCharacteristicValueMeasurement = productCharacteristicValueMeasurement;
	}

	public ProductCharacteristics productCharacteristicValueNumeric(String productCharacteristicValueNumeric) {
		this.productCharacteristicValueNumeric = productCharacteristicValueNumeric;
		return this;
	}

	/**
	 * Get productCharacteristicValueNumeric
	 * 
	 * @return productCharacteristicValueNumeric
	 **/
	@ApiModelProperty(value = "")
	public String getProductCharacteristicValueNumeric() {
		return productCharacteristicValueNumeric;
	}

	public void setProductCharacteristicValueNumeric(String productCharacteristicValueNumeric) {
		this.productCharacteristicValueNumeric = productCharacteristicValueNumeric;
	}

	public ProductCharacteristics productCharacteristicValueString(String productCharacteristicValueString) {
		this.productCharacteristicValueString = productCharacteristicValueString;
		return this;
	}

	/**
	 * Get productCharacteristicValueString
	 * 
	 * @return productCharacteristicValueString
	 **/
	@ApiModelProperty(value = "")
	public String getProductCharacteristicValueString() {
		return productCharacteristicValueString;
	}

	public void setProductCharacteristicValueString(String productCharacteristicValueString) {
		this.productCharacteristicValueString = productCharacteristicValueString;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ProductCharacteristics productCharacteristics = (ProductCharacteristics) o;
		return Objects.equals(this.productCharacteristicCode, productCharacteristics.productCharacteristicCode)
				&& Objects.equals(this.productCharacteristicValueAmount,
						productCharacteristics.productCharacteristicValueAmount)
				&& Objects.equals(this.productCharacteristicValueCode,
						productCharacteristics.productCharacteristicValueCode)
				&& Objects.equals(this.productCharacteristicValueDateTime,
						productCharacteristics.productCharacteristicValueDateTime)
				&& Objects.equals(this.productCharacteristicValueDescription,
						productCharacteristics.productCharacteristicValueDescription)
				&& Objects.equals(this.productCharacteristicValueInteger,
						productCharacteristics.productCharacteristicValueInteger)
				&& Objects.equals(this.productCharacteristicValueMeasurement,
						productCharacteristics.productCharacteristicValueMeasurement)
				&& Objects.equals(this.productCharacteristicValueNumeric,
						productCharacteristics.productCharacteristicValueNumeric)
				&& Objects.equals(this.productCharacteristicValueString,
						productCharacteristics.productCharacteristicValueString);
	}

	@Override
	public int hashCode() {
		return Objects.hash(productCharacteristicCode, productCharacteristicValueAmount, productCharacteristicValueCode,
				productCharacteristicValueDateTime, productCharacteristicValueDescription,
				productCharacteristicValueInteger, productCharacteristicValueMeasurement,
				productCharacteristicValueNumeric, productCharacteristicValueString);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ProductCharacteristics {\n");

		sb.append("    productCharacteristicCode: ").append(toIndentedString(productCharacteristicCode)).append("\n");
		sb.append("    productCharacteristicValueAmount: ").append(toIndentedString(productCharacteristicValueAmount))
				.append("\n");
		sb.append("    productCharacteristicValueCode: ").append(toIndentedString(productCharacteristicValueCode))
				.append("\n");
		sb.append("    productCharacteristicValueDateTime: ")
				.append(toIndentedString(productCharacteristicValueDateTime)).append("\n");
		sb.append("    productCharacteristicValueDescription: ")
				.append(toIndentedString(productCharacteristicValueDescription)).append("\n");
		sb.append("    productCharacteristicValueInteger: ").append(toIndentedString(productCharacteristicValueInteger))
				.append("\n");
		sb.append("    productCharacteristicValueMeasurement: ")
				.append(toIndentedString(productCharacteristicValueMeasurement)).append("\n");
		sb.append("    productCharacteristicValueNumeric: ").append(toIndentedString(productCharacteristicValueNumeric))
				.append("\n");
		sb.append("    productCharacteristicValueString: ").append(toIndentedString(productCharacteristicValueString))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
