/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.CodifiedValues;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.PermitIdentification;
import org.foodauthent.oneworldsync.client.model.Values;

/**
 * RegulatoryInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class RegulatoryInformation {
	@JsonProperty("isPackagingMarkedWithRegulatoryCompliance")
	private CodifiedValue isPackagingMarkedWithRegulatoryCompliance = null;

	@JsonProperty("isTradeItemRegulationCompliant")
	private CodifiedValue isTradeItemRegulationCompliant = null;

	@JsonProperty("permitIdentification")
	private List<PermitIdentification> permitIdentification = null;

	@JsonProperty("regulationCommunityLevelCode")
	private CodifiedValue regulationCommunityLevelCode = null;

	@JsonProperty("regulationRestrictionCommunityIdentifier")
	private Values regulationRestrictionCommunityIdentifier = null;

	@JsonProperty("regulationRestrictionsAndDescriptors")
	private LanguageLabels regulationRestrictionsAndDescriptors = null;

	@JsonProperty("regulationTypeCode")
	private CodifiedValues regulationTypeCode = null;

	@JsonProperty("regulatoryAct")
	private String regulatoryAct = null;

	@JsonProperty("regulatoryActComplianceLevelCode")
	private CodifiedValue regulatoryActComplianceLevelCode = null;

	@JsonProperty("regulatoryAgency")
	private String regulatoryAgency = null;

	public RegulatoryInformation isPackagingMarkedWithRegulatoryCompliance(
			CodifiedValue isPackagingMarkedWithRegulatoryCompliance) {
		this.isPackagingMarkedWithRegulatoryCompliance = isPackagingMarkedWithRegulatoryCompliance;
		return this;
	}

	/**
	 * Get isPackagingMarkedWithRegulatoryCompliance
	 * 
	 * @return isPackagingMarkedWithRegulatoryCompliance
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsPackagingMarkedWithRegulatoryCompliance() {
		return isPackagingMarkedWithRegulatoryCompliance;
	}

	public void setIsPackagingMarkedWithRegulatoryCompliance(CodifiedValue isPackagingMarkedWithRegulatoryCompliance) {
		this.isPackagingMarkedWithRegulatoryCompliance = isPackagingMarkedWithRegulatoryCompliance;
	}

	public RegulatoryInformation isTradeItemRegulationCompliant(CodifiedValue isTradeItemRegulationCompliant) {
		this.isTradeItemRegulationCompliant = isTradeItemRegulationCompliant;
		return this;
	}

	/**
	 * Get isTradeItemRegulationCompliant
	 * 
	 * @return isTradeItemRegulationCompliant
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemRegulationCompliant() {
		return isTradeItemRegulationCompliant;
	}

	public void setIsTradeItemRegulationCompliant(CodifiedValue isTradeItemRegulationCompliant) {
		this.isTradeItemRegulationCompliant = isTradeItemRegulationCompliant;
	}

	public RegulatoryInformation permitIdentification(List<PermitIdentification> permitIdentification) {
		this.permitIdentification = permitIdentification;
		return this;
	}

	public RegulatoryInformation addPermitIdentificationItem(PermitIdentification permitIdentificationItem) {
		if (this.permitIdentification == null) {
			this.permitIdentification = new ArrayList<PermitIdentification>();
		}
		this.permitIdentification.add(permitIdentificationItem);
		return this;
	}

	/**
	 * Get permitIdentification
	 * 
	 * @return permitIdentification
	 **/
	@ApiModelProperty(value = "")
	public List<PermitIdentification> getPermitIdentification() {
		return permitIdentification;
	}

	public void setPermitIdentification(List<PermitIdentification> permitIdentification) {
		this.permitIdentification = permitIdentification;
	}

	public RegulatoryInformation regulationCommunityLevelCode(CodifiedValue regulationCommunityLevelCode) {
		this.regulationCommunityLevelCode = regulationCommunityLevelCode;
		return this;
	}

	/**
	 * Get regulationCommunityLevelCode
	 * 
	 * @return regulationCommunityLevelCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getRegulationCommunityLevelCode() {
		return regulationCommunityLevelCode;
	}

	public void setRegulationCommunityLevelCode(CodifiedValue regulationCommunityLevelCode) {
		this.regulationCommunityLevelCode = regulationCommunityLevelCode;
	}

	public RegulatoryInformation regulationRestrictionCommunityIdentifier(
			Values regulationRestrictionCommunityIdentifier) {
		this.regulationRestrictionCommunityIdentifier = regulationRestrictionCommunityIdentifier;
		return this;
	}

	/**
	 * Get regulationRestrictionCommunityIdentifier
	 * 
	 * @return regulationRestrictionCommunityIdentifier
	 **/
	@ApiModelProperty(value = "")
	public Values getRegulationRestrictionCommunityIdentifier() {
		return regulationRestrictionCommunityIdentifier;
	}

	public void setRegulationRestrictionCommunityIdentifier(Values regulationRestrictionCommunityIdentifier) {
		this.regulationRestrictionCommunityIdentifier = regulationRestrictionCommunityIdentifier;
	}

	public RegulatoryInformation regulationRestrictionsAndDescriptors(
			LanguageLabels regulationRestrictionsAndDescriptors) {
		this.regulationRestrictionsAndDescriptors = regulationRestrictionsAndDescriptors;
		return this;
	}

	/**
	 * Get regulationRestrictionsAndDescriptors
	 * 
	 * @return regulationRestrictionsAndDescriptors
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getRegulationRestrictionsAndDescriptors() {
		return regulationRestrictionsAndDescriptors;
	}

	public void setRegulationRestrictionsAndDescriptors(LanguageLabels regulationRestrictionsAndDescriptors) {
		this.regulationRestrictionsAndDescriptors = regulationRestrictionsAndDescriptors;
	}

	public RegulatoryInformation regulationTypeCode(CodifiedValues regulationTypeCode) {
		this.regulationTypeCode = regulationTypeCode;
		return this;
	}

	/**
	 * Get regulationTypeCode
	 * 
	 * @return regulationTypeCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValues getRegulationTypeCode() {
		return regulationTypeCode;
	}

	public void setRegulationTypeCode(CodifiedValues regulationTypeCode) {
		this.regulationTypeCode = regulationTypeCode;
	}

	public RegulatoryInformation regulatoryAct(String regulatoryAct) {
		this.regulatoryAct = regulatoryAct;
		return this;
	}

	/**
	 * Get regulatoryAct
	 * 
	 * @return regulatoryAct
	 **/
	@ApiModelProperty(value = "")
	public String getRegulatoryAct() {
		return regulatoryAct;
	}

	public void setRegulatoryAct(String regulatoryAct) {
		this.regulatoryAct = regulatoryAct;
	}

	public RegulatoryInformation regulatoryActComplianceLevelCode(CodifiedValue regulatoryActComplianceLevelCode) {
		this.regulatoryActComplianceLevelCode = regulatoryActComplianceLevelCode;
		return this;
	}

	/**
	 * Get regulatoryActComplianceLevelCode
	 * 
	 * @return regulatoryActComplianceLevelCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getRegulatoryActComplianceLevelCode() {
		return regulatoryActComplianceLevelCode;
	}

	public void setRegulatoryActComplianceLevelCode(CodifiedValue regulatoryActComplianceLevelCode) {
		this.regulatoryActComplianceLevelCode = regulatoryActComplianceLevelCode;
	}

	public RegulatoryInformation regulatoryAgency(String regulatoryAgency) {
		this.regulatoryAgency = regulatoryAgency;
		return this;
	}

	/**
	 * Get regulatoryAgency
	 * 
	 * @return regulatoryAgency
	 **/
	@ApiModelProperty(value = "")
	public String getRegulatoryAgency() {
		return regulatoryAgency;
	}

	public void setRegulatoryAgency(String regulatoryAgency) {
		this.regulatoryAgency = regulatoryAgency;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RegulatoryInformation regulatoryInformation = (RegulatoryInformation) o;
		return Objects.equals(this.isPackagingMarkedWithRegulatoryCompliance,
				regulatoryInformation.isPackagingMarkedWithRegulatoryCompliance)
				&& Objects.equals(this.isTradeItemRegulationCompliant,
						regulatoryInformation.isTradeItemRegulationCompliant)
				&& Objects.equals(this.permitIdentification, regulatoryInformation.permitIdentification)
				&& Objects.equals(this.regulationCommunityLevelCode, regulatoryInformation.regulationCommunityLevelCode)
				&& Objects.equals(this.regulationRestrictionCommunityIdentifier,
						regulatoryInformation.regulationRestrictionCommunityIdentifier)
				&& Objects.equals(this.regulationRestrictionsAndDescriptors,
						regulatoryInformation.regulationRestrictionsAndDescriptors)
				&& Objects.equals(this.regulationTypeCode, regulatoryInformation.regulationTypeCode)
				&& Objects.equals(this.regulatoryAct, regulatoryInformation.regulatoryAct)
				&& Objects.equals(this.regulatoryActComplianceLevelCode,
						regulatoryInformation.regulatoryActComplianceLevelCode)
				&& Objects.equals(this.regulatoryAgency, regulatoryInformation.regulatoryAgency);
	}

	@Override
	public int hashCode() {
		return Objects.hash(isPackagingMarkedWithRegulatoryCompliance, isTradeItemRegulationCompliant,
				permitIdentification, regulationCommunityLevelCode, regulationRestrictionCommunityIdentifier,
				regulationRestrictionsAndDescriptors, regulationTypeCode, regulatoryAct,
				regulatoryActComplianceLevelCode, regulatoryAgency);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RegulatoryInformation {\n");

		sb.append("    isPackagingMarkedWithRegulatoryCompliance: ")
				.append(toIndentedString(isPackagingMarkedWithRegulatoryCompliance)).append("\n");
		sb.append("    isTradeItemRegulationCompliant: ").append(toIndentedString(isTradeItemRegulationCompliant))
				.append("\n");
		sb.append("    permitIdentification: ").append(toIndentedString(permitIdentification)).append("\n");
		sb.append("    regulationCommunityLevelCode: ").append(toIndentedString(regulationCommunityLevelCode))
				.append("\n");
		sb.append("    regulationRestrictionCommunityIdentifier: ")
				.append(toIndentedString(regulationRestrictionCommunityIdentifier)).append("\n");
		sb.append("    regulationRestrictionsAndDescriptors: ")
				.append(toIndentedString(regulationRestrictionsAndDescriptors)).append("\n");
		sb.append("    regulationTypeCode: ").append(toIndentedString(regulationTypeCode)).append("\n");
		sb.append("    regulatoryAct: ").append(toIndentedString(regulatoryAct)).append("\n");
		sb.append("    regulatoryActComplianceLevelCode: ").append(toIndentedString(regulatoryActComplianceLevelCode))
				.append("\n");
		sb.append("    regulatoryAgency: ").append(toIndentedString(regulatoryAgency)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
