/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.EnumerationValueInformation;

/**
 * RiskPhraseCode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class RiskPhraseCode {
	@JsonProperty("enumerationValueInformation")
	private List<EnumerationValueInformation> enumerationValueInformation = null;

	@JsonProperty("externalAgencyName")
	private String externalAgencyName = null;

	@JsonProperty("externalCodeListName")
	private String externalCodeListName = null;

	@JsonProperty("externalCodeListVersion")
	private String externalCodeListVersion = null;

	public RiskPhraseCode enumerationValueInformation(List<EnumerationValueInformation> enumerationValueInformation) {
		this.enumerationValueInformation = enumerationValueInformation;
		return this;
	}

	public RiskPhraseCode addEnumerationValueInformationItem(
			EnumerationValueInformation enumerationValueInformationItem) {
		if (this.enumerationValueInformation == null) {
			this.enumerationValueInformation = new ArrayList<EnumerationValueInformation>();
		}
		this.enumerationValueInformation.add(enumerationValueInformationItem);
		return this;
	}

	/**
	 * Get enumerationValueInformation
	 * 
	 * @return enumerationValueInformation
	 **/
	@ApiModelProperty(value = "")
	public List<EnumerationValueInformation> getEnumerationValueInformation() {
		return enumerationValueInformation;
	}

	public void setEnumerationValueInformation(List<EnumerationValueInformation> enumerationValueInformation) {
		this.enumerationValueInformation = enumerationValueInformation;
	}

	public RiskPhraseCode externalAgencyName(String externalAgencyName) {
		this.externalAgencyName = externalAgencyName;
		return this;
	}

	/**
	 * Get externalAgencyName
	 * 
	 * @return externalAgencyName
	 **/
	@ApiModelProperty(value = "")
	public String getExternalAgencyName() {
		return externalAgencyName;
	}

	public void setExternalAgencyName(String externalAgencyName) {
		this.externalAgencyName = externalAgencyName;
	}

	public RiskPhraseCode externalCodeListName(String externalCodeListName) {
		this.externalCodeListName = externalCodeListName;
		return this;
	}

	/**
	 * Get externalCodeListName
	 * 
	 * @return externalCodeListName
	 **/
	@ApiModelProperty(value = "")
	public String getExternalCodeListName() {
		return externalCodeListName;
	}

	public void setExternalCodeListName(String externalCodeListName) {
		this.externalCodeListName = externalCodeListName;
	}

	public RiskPhraseCode externalCodeListVersion(String externalCodeListVersion) {
		this.externalCodeListVersion = externalCodeListVersion;
		return this;
	}

	/**
	 * Get externalCodeListVersion
	 * 
	 * @return externalCodeListVersion
	 **/
	@ApiModelProperty(value = "")
	public String getExternalCodeListVersion() {
		return externalCodeListVersion;
	}

	public void setExternalCodeListVersion(String externalCodeListVersion) {
		this.externalCodeListVersion = externalCodeListVersion;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		RiskPhraseCode riskPhraseCode = (RiskPhraseCode) o;
		return Objects.equals(this.enumerationValueInformation, riskPhraseCode.enumerationValueInformation)
				&& Objects.equals(this.externalAgencyName, riskPhraseCode.externalAgencyName)
				&& Objects.equals(this.externalCodeListName, riskPhraseCode.externalCodeListName)
				&& Objects.equals(this.externalCodeListVersion, riskPhraseCode.externalCodeListVersion);
	}

	@Override
	public int hashCode() {
		return Objects.hash(enumerationValueInformation, externalAgencyName, externalCodeListName,
				externalCodeListVersion);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class RiskPhraseCode {\n");

		sb.append("    enumerationValueInformation: ").append(toIndentedString(enumerationValueInformation))
				.append("\n");
		sb.append("    externalAgencyName: ").append(toIndentedString(externalAgencyName)).append("\n");
		sb.append("    externalCodeListName: ").append(toIndentedString(externalCodeListName)).append("\n");
		sb.append("    externalCodeListVersion: ").append(toIndentedString(externalCodeListVersion)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
