/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.QualifiedValue;

/**
 * ToxicityProperties
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class ToxicityProperties {
	@JsonProperty("hasCancerousProperties")
	private CodifiedValue hasCancerousProperties = null;

	@JsonProperty("toxicityMeasurement")
	private QualifiedValue toxicityMeasurement = null;

	@JsonProperty("toxicityMeasurementProtocolCode")
	private CodifiedValue toxicityMeasurementProtocolCode = null;

	@JsonProperty("toxicityMeasurementProtocolDescription")
	private LanguageLabels toxicityMeasurementProtocolDescription = null;

	@JsonProperty("toxicityReferenceSubstanceCode")
	private CodifiedValue toxicityReferenceSubstanceCode = null;

	@JsonProperty("toxicityReferenceSubstanceDescription")
	private LanguageLabels toxicityReferenceSubstanceDescription = null;

	public ToxicityProperties hasCancerousProperties(CodifiedValue hasCancerousProperties) {
		this.hasCancerousProperties = hasCancerousProperties;
		return this;
	}

	/**
	 * Get hasCancerousProperties
	 * 
	 * @return hasCancerousProperties
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getHasCancerousProperties() {
		return hasCancerousProperties;
	}

	public void setHasCancerousProperties(CodifiedValue hasCancerousProperties) {
		this.hasCancerousProperties = hasCancerousProperties;
	}

	public ToxicityProperties toxicityMeasurement(QualifiedValue toxicityMeasurement) {
		this.toxicityMeasurement = toxicityMeasurement;
		return this;
	}

	/**
	 * Get toxicityMeasurement
	 * 
	 * @return toxicityMeasurement
	 **/
	@ApiModelProperty(value = "")
	public QualifiedValue getToxicityMeasurement() {
		return toxicityMeasurement;
	}

	public void setToxicityMeasurement(QualifiedValue toxicityMeasurement) {
		this.toxicityMeasurement = toxicityMeasurement;
	}

	public ToxicityProperties toxicityMeasurementProtocolCode(CodifiedValue toxicityMeasurementProtocolCode) {
		this.toxicityMeasurementProtocolCode = toxicityMeasurementProtocolCode;
		return this;
	}

	/**
	 * Get toxicityMeasurementProtocolCode
	 * 
	 * @return toxicityMeasurementProtocolCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getToxicityMeasurementProtocolCode() {
		return toxicityMeasurementProtocolCode;
	}

	public void setToxicityMeasurementProtocolCode(CodifiedValue toxicityMeasurementProtocolCode) {
		this.toxicityMeasurementProtocolCode = toxicityMeasurementProtocolCode;
	}

	public ToxicityProperties toxicityMeasurementProtocolDescription(
			LanguageLabels toxicityMeasurementProtocolDescription) {
		this.toxicityMeasurementProtocolDescription = toxicityMeasurementProtocolDescription;
		return this;
	}

	/**
	 * Get toxicityMeasurementProtocolDescription
	 * 
	 * @return toxicityMeasurementProtocolDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getToxicityMeasurementProtocolDescription() {
		return toxicityMeasurementProtocolDescription;
	}

	public void setToxicityMeasurementProtocolDescription(LanguageLabels toxicityMeasurementProtocolDescription) {
		this.toxicityMeasurementProtocolDescription = toxicityMeasurementProtocolDescription;
	}

	public ToxicityProperties toxicityReferenceSubstanceCode(CodifiedValue toxicityReferenceSubstanceCode) {
		this.toxicityReferenceSubstanceCode = toxicityReferenceSubstanceCode;
		return this;
	}

	/**
	 * Get toxicityReferenceSubstanceCode
	 * 
	 * @return toxicityReferenceSubstanceCode
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getToxicityReferenceSubstanceCode() {
		return toxicityReferenceSubstanceCode;
	}

	public void setToxicityReferenceSubstanceCode(CodifiedValue toxicityReferenceSubstanceCode) {
		this.toxicityReferenceSubstanceCode = toxicityReferenceSubstanceCode;
	}

	public ToxicityProperties toxicityReferenceSubstanceDescription(
			LanguageLabels toxicityReferenceSubstanceDescription) {
		this.toxicityReferenceSubstanceDescription = toxicityReferenceSubstanceDescription;
		return this;
	}

	/**
	 * Get toxicityReferenceSubstanceDescription
	 * 
	 * @return toxicityReferenceSubstanceDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getToxicityReferenceSubstanceDescription() {
		return toxicityReferenceSubstanceDescription;
	}

	public void setToxicityReferenceSubstanceDescription(LanguageLabels toxicityReferenceSubstanceDescription) {
		this.toxicityReferenceSubstanceDescription = toxicityReferenceSubstanceDescription;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ToxicityProperties toxicityProperties = (ToxicityProperties) o;
		return Objects.equals(this.hasCancerousProperties, toxicityProperties.hasCancerousProperties)
				&& Objects.equals(this.toxicityMeasurement, toxicityProperties.toxicityMeasurement)
				&& Objects.equals(this.toxicityMeasurementProtocolCode,
						toxicityProperties.toxicityMeasurementProtocolCode)
				&& Objects.equals(this.toxicityMeasurementProtocolDescription,
						toxicityProperties.toxicityMeasurementProtocolDescription)
				&& Objects.equals(this.toxicityReferenceSubstanceCode,
						toxicityProperties.toxicityReferenceSubstanceCode)
				&& Objects.equals(this.toxicityReferenceSubstanceDescription,
						toxicityProperties.toxicityReferenceSubstanceDescription);
	}

	@Override
	public int hashCode() {
		return Objects.hash(hasCancerousProperties, toxicityMeasurement, toxicityMeasurementProtocolCode,
				toxicityMeasurementProtocolDescription, toxicityReferenceSubstanceCode,
				toxicityReferenceSubstanceDescription);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ToxicityProperties {\n");

		sb.append("    hasCancerousProperties: ").append(toIndentedString(hasCancerousProperties)).append("\n");
		sb.append("    toxicityMeasurement: ").append(toIndentedString(toxicityMeasurement)).append("\n");
		sb.append("    toxicityMeasurementProtocolCode: ").append(toIndentedString(toxicityMeasurementProtocolCode))
				.append("\n");
		sb.append("    toxicityMeasurementProtocolDescription: ")
				.append(toIndentedString(toxicityMeasurementProtocolDescription)).append("\n");
		sb.append("    toxicityReferenceSubstanceCode: ").append(toIndentedString(toxicityReferenceSubstanceCode))
				.append("\n");
		sb.append("    toxicityReferenceSubstanceDescription: ")
				.append(toIndentedString(toxicityReferenceSubstanceDescription)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
