/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.AlcoholInformationModule;
import org.foodauthent.oneworldsync.client.model.AllergenInformationModuleGroup;
import org.foodauthent.oneworldsync.client.model.AnimalFeedingModule;
import org.foodauthent.oneworldsync.client.model.ApparelInformationModule;
import org.foodauthent.oneworldsync.client.model.AudienceOrPlayerInformationModule;
import org.foodauthent.oneworldsync.client.model.AudioVisualMediaContentInformationModule;
import org.foodauthent.oneworldsync.client.model.AudioVisualMediaProductDescriptionInformationModule;
import org.foodauthent.oneworldsync.client.model.AudioVisualMediaProductionInformationModule;
import org.foodauthent.oneworldsync.client.model.AwardPrizeModule;
import org.foodauthent.oneworldsync.client.model.BatteryInformationModule;
import org.foodauthent.oneworldsync.client.model.CertificationInformationModule;
import org.foodauthent.oneworldsync.client.model.ChemicalRegulationInformationModule;
import org.foodauthent.oneworldsync.client.model.ChildNutritionInformationModule;
import org.foodauthent.oneworldsync.client.model.ConsumerInstructionsModule;
import org.foodauthent.oneworldsync.client.model.ControlledSubstanceModule;
import org.foodauthent.oneworldsync.client.model.DairyFishMeatPoultryItemModule;
import org.foodauthent.oneworldsync.client.model.DangerousSubstanceInformationModule;
import org.foodauthent.oneworldsync.client.model.DeliveryPurchasingInformationModuleGroup;
import org.foodauthent.oneworldsync.client.model.DietInformationModule;
import org.foodauthent.oneworldsync.client.model.DurableGoodsCharacteristicsModule;
import org.foodauthent.oneworldsync.client.model.DutyFeeTaxInformationModule;
import org.foodauthent.oneworldsync.client.model.ElectronicDeviceCharacteristicsInformationModule;
import org.foodauthent.oneworldsync.client.model.FarmingAndProcessingInformationModule;
import org.foodauthent.oneworldsync.client.model.FoodAndBeverageIngredientModule;
import org.foodauthent.oneworldsync.client.model.FoodAndBeveragePreparationServingModule;
import org.foodauthent.oneworldsync.client.model.FoodAndBeveragePropertiesInformationModule;
import org.foodauthent.oneworldsync.client.model.HealthRelatedInformationModule;
import org.foodauthent.oneworldsync.client.model.HealthWellnessPackagingMarkingModule;
import org.foodauthent.oneworldsync.client.model.HealthcareItemInformationModule;
import org.foodauthent.oneworldsync.client.model.LanguageLabels;
import org.foodauthent.oneworldsync.client.model.LightingDeviceModule;
import org.foodauthent.oneworldsync.client.model.MarketingInformationModuleGroup;
import org.foodauthent.oneworldsync.client.model.MedicalDeviceTradeItemModule;
import org.foodauthent.oneworldsync.client.model.MovieRevenueInformationModule;
import org.foodauthent.oneworldsync.client.model.NonGTINLogisticsUnitInformationModule;
import org.foodauthent.oneworldsync.client.model.NonfoodIngredientModule;
import org.foodauthent.oneworldsync.client.model.NutritionalInformationModule;
import org.foodauthent.oneworldsync.client.model.OrganismClassificationModule;
import org.foodauthent.oneworldsync.client.model.PackagingInformationModule;
import org.foodauthent.oneworldsync.client.model.PackagingMarkingModule;
import org.foodauthent.oneworldsync.client.model.PackagingSustainabilityModule;
import org.foodauthent.oneworldsync.client.model.PharmaceuticalItemInformationModule;
import org.foodauthent.oneworldsync.client.model.PhysicalResourceUsageInformationModule;
import org.foodauthent.oneworldsync.client.model.PlaceOfItemActivityModule;
import org.foodauthent.oneworldsync.client.model.ProductCharacteristicsModule;
import org.foodauthent.oneworldsync.client.model.ProductFormulationStatementModule;
import org.foodauthent.oneworldsync.client.model.PromotionalItemInformationModuleGroup;
import org.foodauthent.oneworldsync.client.model.PropellantInformationModule;
import org.foodauthent.oneworldsync.client.model.PublicationTitleRatingModule;
import org.foodauthent.oneworldsync.client.model.ReferencedFileDetailInformationModule;
import org.foodauthent.oneworldsync.client.model.RegulatedTradeItemModule;
import org.foodauthent.oneworldsync.client.model.SafetyDataSheetModule;
import org.foodauthent.oneworldsync.client.model.SalesInformationModuleGroup;
import org.foodauthent.oneworldsync.client.model.SecurityTagInformationModule;
import org.foodauthent.oneworldsync.client.model.SustainabilityModule;
import org.foodauthent.oneworldsync.client.model.TextileMaterialModule;
import org.foodauthent.oneworldsync.client.model.TradeItemComponents;
import org.foodauthent.oneworldsync.client.model.TradeItemDataCarrierAndIdentificationModule;
import org.foodauthent.oneworldsync.client.model.TradeItemDescriptionModule;
import org.foodauthent.oneworldsync.client.model.TradeItemDisposalInformationModule;
import org.foodauthent.oneworldsync.client.model.TradeItemHandlingModule;
import org.foodauthent.oneworldsync.client.model.TradeItemHierarchyModule;
import org.foodauthent.oneworldsync.client.model.TradeItemHumidityInformationModule;
import org.foodauthent.oneworldsync.client.model.TradeItemLicensingModule;
import org.foodauthent.oneworldsync.client.model.TradeItemLifespanModuleGroup;
import org.foodauthent.oneworldsync.client.model.TradeItemMeasurementsModule;
import org.foodauthent.oneworldsync.client.model.TradeItemSizeModule;
import org.foodauthent.oneworldsync.client.model.TradeItemTemperatureInformationModule;
import org.foodauthent.oneworldsync.client.model.TransportationHazardousClassificationModule;
import org.foodauthent.oneworldsync.client.model.VariableTradeItemInformationModule;
import org.foodauthent.oneworldsync.client.model.VideoDisplayDeviceInformationModule;
import org.foodauthent.oneworldsync.client.model.WarrantyInformationModule;

/**
 * TradeItemInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class TradeItemInformation {
	@JsonProperty("alcoholInformationModule")
	private AlcoholInformationModule alcoholInformationModule = null;

	@JsonProperty("allergenInformationModuleGroup")
	private List<AllergenInformationModuleGroup> allergenInformationModuleGroup = null;

	@JsonProperty("animalFeedingModule")
	private AnimalFeedingModule animalFeedingModule = null;

	@JsonProperty("apparelInformationModule")
	private ApparelInformationModule apparelInformationModule = null;

	@JsonProperty("audienceOrPlayerInformationModule")
	private AudienceOrPlayerInformationModule audienceOrPlayerInformationModule = null;

	@JsonProperty("audioVisualMediaContentInformationModule")
	private AudioVisualMediaContentInformationModule audioVisualMediaContentInformationModule = null;

	@JsonProperty("audioVisualMediaProductDescriptionInformationModule")
	private AudioVisualMediaProductDescriptionInformationModule audioVisualMediaProductDescriptionInformationModule = null;

	@JsonProperty("audioVisualMediaProductionInformationModule")
	private AudioVisualMediaProductionInformationModule audioVisualMediaProductionInformationModule = null;

	@JsonProperty("awardPrizeModule")
	private AwardPrizeModule awardPrizeModule = null;

	@JsonProperty("batteryInformationModule")
	private BatteryInformationModule batteryInformationModule = null;

	@JsonProperty("certificationInformationModule")
	private CertificationInformationModule certificationInformationModule = null;

	@JsonProperty("chemicalRegulationInformationModule")
	private ChemicalRegulationInformationModule chemicalRegulationInformationModule = null;

	@JsonProperty("childNutritionInformationModule")
	private ChildNutritionInformationModule childNutritionInformationModule = null;

	@JsonProperty("consumerInstructionsModule")
	private List<ConsumerInstructionsModule> consumerInstructionsModule = null;

	@JsonProperty("controlledSubstanceModule")
	private ControlledSubstanceModule controlledSubstanceModule = null;

	@JsonProperty("dairyFishMeatPoultryItemModule")
	private DairyFishMeatPoultryItemModule dairyFishMeatPoultryItemModule = null;

	@JsonProperty("dangerousSubstanceInformationModule")
	private DangerousSubstanceInformationModule dangerousSubstanceInformationModule = null;

	@JsonProperty("deliveryPurchasingInformationModuleGroup")
	private List<DeliveryPurchasingInformationModuleGroup> deliveryPurchasingInformationModuleGroup = null;

	@JsonProperty("dietInformationModule")
	private DietInformationModule dietInformationModule = null;

	@JsonProperty("durableGoodsCharacteristicsModule")
	private DurableGoodsCharacteristicsModule durableGoodsCharacteristicsModule = null;

	@JsonProperty("dutyFeeTaxInformationModule")
	private DutyFeeTaxInformationModule dutyFeeTaxInformationModule = null;

	@JsonProperty("electronicDeviceCharacteristicsInformationModule")
	private ElectronicDeviceCharacteristicsInformationModule electronicDeviceCharacteristicsInformationModule = null;

	@JsonProperty("farmingAndProcessingInformationModule")
	private FarmingAndProcessingInformationModule farmingAndProcessingInformationModule = null;

	@JsonProperty("foodAndBeverageIngredientModule")
	private List<FoodAndBeverageIngredientModule> foodAndBeverageIngredientModule = null;

	@JsonProperty("foodAndBeveragePreparationServingModule")
	private List<FoodAndBeveragePreparationServingModule> foodAndBeveragePreparationServingModule = null;

	@JsonProperty("foodAndBeveragePropertiesInformationModule")
	private FoodAndBeveragePropertiesInformationModule foodAndBeveragePropertiesInformationModule = null;

	@JsonProperty("healthRelatedInformationModule")
	private HealthRelatedInformationModule healthRelatedInformationModule = null;

	@JsonProperty("healthWellnessPackagingMarkingModule")
	private HealthWellnessPackagingMarkingModule healthWellnessPackagingMarkingModule = null;

	@JsonProperty("healthcareItemInformationModule")
	private HealthcareItemInformationModule healthcareItemInformationModule = null;

	@JsonProperty("lightingDeviceModule")
	private LightingDeviceModule lightingDeviceModule = null;

	@JsonProperty("marketingInformationModuleGroup")
	private List<MarketingInformationModuleGroup> marketingInformationModuleGroup = null;

	@JsonProperty("medicalDeviceTradeItemModule")
	private MedicalDeviceTradeItemModule medicalDeviceTradeItemModule = null;

	@JsonProperty("movieRevenueInformationModule")
	private MovieRevenueInformationModule movieRevenueInformationModule = null;

	@JsonProperty("nonGTINLogisticsUnitInformationModule")
	private NonGTINLogisticsUnitInformationModule nonGTINLogisticsUnitInformationModule = null;

	@JsonProperty("nonfoodIngredientModule")
	private NonfoodIngredientModule nonfoodIngredientModule = null;

	@JsonProperty("nutritionalInformationModule")
	private List<NutritionalInformationModule> nutritionalInformationModule = null;

	@JsonProperty("organismClassificationModule")
	private OrganismClassificationModule organismClassificationModule = null;

	@JsonProperty("packagingInformationModule")
	private PackagingInformationModule packagingInformationModule = null;

	@JsonProperty("packagingMarkingModule")
	private PackagingMarkingModule packagingMarkingModule = null;

	@JsonProperty("packagingSustainabilityModule")
	private PackagingSustainabilityModule packagingSustainabilityModule = null;

	@JsonProperty("pharmaceuticalItemInformationModule")
	private PharmaceuticalItemInformationModule pharmaceuticalItemInformationModule = null;

	@JsonProperty("physicalResourceUsageInformationModule")
	private PhysicalResourceUsageInformationModule physicalResourceUsageInformationModule = null;

	@JsonProperty("placeOfItemActivityModule")
	private PlaceOfItemActivityModule placeOfItemActivityModule = null;

	@JsonProperty("productCharacteristicsModule")
	private ProductCharacteristicsModule productCharacteristicsModule = null;

	@JsonProperty("productFormulationStatementModule")
	private ProductFormulationStatementModule productFormulationStatementModule = null;

	@JsonProperty("productionVariantCancelledDateTime")
	private String productionVariantCancelledDateTime = null;

	@JsonProperty("productionVariantDescription")
	private LanguageLabels productionVariantDescription = null;

	@JsonProperty("productionVariantDiscontinuedDateTime")
	private String productionVariantDiscontinuedDateTime = null;

	@JsonProperty("productionVariantEffectiveDateTime")
	private String productionVariantEffectiveDateTime = null;

	@JsonProperty("promotionalItemInformationModuleGroup")
	private List<PromotionalItemInformationModuleGroup> promotionalItemInformationModuleGroup = null;

	@JsonProperty("propellantInformationModule")
	private PropellantInformationModule propellantInformationModule = null;

	@JsonProperty("publicationTitleRatingModule")
	private PublicationTitleRatingModule publicationTitleRatingModule = null;

	@JsonProperty("referencedFileDetailInformationModule")
	private ReferencedFileDetailInformationModule referencedFileDetailInformationModule = null;

	@JsonProperty("regulatedTradeItemModule")
	private RegulatedTradeItemModule regulatedTradeItemModule = null;

	@JsonProperty("safetyDataSheetModule")
	private SafetyDataSheetModule safetyDataSheetModule = null;

	@JsonProperty("salesInformationModuleGroup")
	private List<SalesInformationModuleGroup> salesInformationModuleGroup = null;

	@JsonProperty("securityTagInformationModule")
	private SecurityTagInformationModule securityTagInformationModule = null;

	@JsonProperty("sustainabilityModule")
	private SustainabilityModule sustainabilityModule = null;

	@JsonProperty("textileMaterialModule")
	private TextileMaterialModule textileMaterialModule = null;

	@JsonProperty("tradeItemComponents")
	private TradeItemComponents tradeItemComponents = null;

	@JsonProperty("tradeItemDataCarrierAndIdentificationModule")
	private TradeItemDataCarrierAndIdentificationModule tradeItemDataCarrierAndIdentificationModule = null;

	@JsonProperty("tradeItemDescriptionModule")
	private TradeItemDescriptionModule tradeItemDescriptionModule = null;

	@JsonProperty("tradeItemDisposalInformationModule")
	private TradeItemDisposalInformationModule tradeItemDisposalInformationModule = null;

	@JsonProperty("tradeItemFeatureBenefitExtended")
	private LanguageLabels tradeItemFeatureBenefitExtended = null;

	@JsonProperty("tradeItemHandlingModule")
	private TradeItemHandlingModule tradeItemHandlingModule = null;

	@JsonProperty("tradeItemHierarchyModule")
	private TradeItemHierarchyModule tradeItemHierarchyModule = null;

	@JsonProperty("tradeItemHumidityInformationModule")
	private TradeItemHumidityInformationModule tradeItemHumidityInformationModule = null;

	@JsonProperty("tradeItemLicensingModule")
	private TradeItemLicensingModule tradeItemLicensingModule = null;

	@JsonProperty("tradeItemLifespanModuleGroup")
	private List<TradeItemLifespanModuleGroup> tradeItemLifespanModuleGroup = null;

	@JsonProperty("tradeItemMeasurementsModule")
	private TradeItemMeasurementsModule tradeItemMeasurementsModule = null;

	@JsonProperty("tradeItemSizeModule")
	private TradeItemSizeModule tradeItemSizeModule = null;

	@JsonProperty("tradeItemTemperatureInformationModule")
	private TradeItemTemperatureInformationModule tradeItemTemperatureInformationModule = null;

	@JsonProperty("transportationHazardousClassificationModule")
	private TransportationHazardousClassificationModule transportationHazardousClassificationModule = null;

	@JsonProperty("variableTradeItemInformationModule")
	private VariableTradeItemInformationModule variableTradeItemInformationModule = null;

	@JsonProperty("videoDisplayDeviceInformationModule")
	private VideoDisplayDeviceInformationModule videoDisplayDeviceInformationModule = null;

	@JsonProperty("warrantyInformationModule")
	private WarrantyInformationModule warrantyInformationModule = null;

	public TradeItemInformation alcoholInformationModule(AlcoholInformationModule alcoholInformationModule) {
		this.alcoholInformationModule = alcoholInformationModule;
		return this;
	}

	/**
	 * Get alcoholInformationModule
	 * 
	 * @return alcoholInformationModule
	 **/
	@ApiModelProperty(value = "")
	public AlcoholInformationModule getAlcoholInformationModule() {
		return alcoholInformationModule;
	}

	public void setAlcoholInformationModule(AlcoholInformationModule alcoholInformationModule) {
		this.alcoholInformationModule = alcoholInformationModule;
	}

	public TradeItemInformation allergenInformationModuleGroup(
			List<AllergenInformationModuleGroup> allergenInformationModuleGroup) {
		this.allergenInformationModuleGroup = allergenInformationModuleGroup;
		return this;
	}

	public TradeItemInformation addAllergenInformationModuleGroupItem(
			AllergenInformationModuleGroup allergenInformationModuleGroupItem) {
		if (this.allergenInformationModuleGroup == null) {
			this.allergenInformationModuleGroup = new ArrayList<AllergenInformationModuleGroup>();
		}
		this.allergenInformationModuleGroup.add(allergenInformationModuleGroupItem);
		return this;
	}

	/**
	 * Get allergenInformationModuleGroup
	 * 
	 * @return allergenInformationModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<AllergenInformationModuleGroup> getAllergenInformationModuleGroup() {
		return allergenInformationModuleGroup;
	}

	public void setAllergenInformationModuleGroup(List<AllergenInformationModuleGroup> allergenInformationModuleGroup) {
		this.allergenInformationModuleGroup = allergenInformationModuleGroup;
	}

	public TradeItemInformation animalFeedingModule(AnimalFeedingModule animalFeedingModule) {
		this.animalFeedingModule = animalFeedingModule;
		return this;
	}

	/**
	 * Get animalFeedingModule
	 * 
	 * @return animalFeedingModule
	 **/
	@ApiModelProperty(value = "")
	public AnimalFeedingModule getAnimalFeedingModule() {
		return animalFeedingModule;
	}

	public void setAnimalFeedingModule(AnimalFeedingModule animalFeedingModule) {
		this.animalFeedingModule = animalFeedingModule;
	}

	public TradeItemInformation apparelInformationModule(ApparelInformationModule apparelInformationModule) {
		this.apparelInformationModule = apparelInformationModule;
		return this;
	}

	/**
	 * Get apparelInformationModule
	 * 
	 * @return apparelInformationModule
	 **/
	@ApiModelProperty(value = "")
	public ApparelInformationModule getApparelInformationModule() {
		return apparelInformationModule;
	}

	public void setApparelInformationModule(ApparelInformationModule apparelInformationModule) {
		this.apparelInformationModule = apparelInformationModule;
	}

	public TradeItemInformation audienceOrPlayerInformationModule(
			AudienceOrPlayerInformationModule audienceOrPlayerInformationModule) {
		this.audienceOrPlayerInformationModule = audienceOrPlayerInformationModule;
		return this;
	}

	/**
	 * Get audienceOrPlayerInformationModule
	 * 
	 * @return audienceOrPlayerInformationModule
	 **/
	@ApiModelProperty(value = "")
	public AudienceOrPlayerInformationModule getAudienceOrPlayerInformationModule() {
		return audienceOrPlayerInformationModule;
	}

	public void setAudienceOrPlayerInformationModule(
			AudienceOrPlayerInformationModule audienceOrPlayerInformationModule) {
		this.audienceOrPlayerInformationModule = audienceOrPlayerInformationModule;
	}

	public TradeItemInformation audioVisualMediaContentInformationModule(
			AudioVisualMediaContentInformationModule audioVisualMediaContentInformationModule) {
		this.audioVisualMediaContentInformationModule = audioVisualMediaContentInformationModule;
		return this;
	}

	/**
	 * Get audioVisualMediaContentInformationModule
	 * 
	 * @return audioVisualMediaContentInformationModule
	 **/
	@ApiModelProperty(value = "")
	public AudioVisualMediaContentInformationModule getAudioVisualMediaContentInformationModule() {
		return audioVisualMediaContentInformationModule;
	}

	public void setAudioVisualMediaContentInformationModule(
			AudioVisualMediaContentInformationModule audioVisualMediaContentInformationModule) {
		this.audioVisualMediaContentInformationModule = audioVisualMediaContentInformationModule;
	}

	public TradeItemInformation audioVisualMediaProductDescriptionInformationModule(
			AudioVisualMediaProductDescriptionInformationModule audioVisualMediaProductDescriptionInformationModule) {
		this.audioVisualMediaProductDescriptionInformationModule = audioVisualMediaProductDescriptionInformationModule;
		return this;
	}

	/**
	 * Get audioVisualMediaProductDescriptionInformationModule
	 * 
	 * @return audioVisualMediaProductDescriptionInformationModule
	 **/
	@ApiModelProperty(value = "")
	public AudioVisualMediaProductDescriptionInformationModule getAudioVisualMediaProductDescriptionInformationModule() {
		return audioVisualMediaProductDescriptionInformationModule;
	}

	public void setAudioVisualMediaProductDescriptionInformationModule(
			AudioVisualMediaProductDescriptionInformationModule audioVisualMediaProductDescriptionInformationModule) {
		this.audioVisualMediaProductDescriptionInformationModule = audioVisualMediaProductDescriptionInformationModule;
	}

	public TradeItemInformation audioVisualMediaProductionInformationModule(
			AudioVisualMediaProductionInformationModule audioVisualMediaProductionInformationModule) {
		this.audioVisualMediaProductionInformationModule = audioVisualMediaProductionInformationModule;
		return this;
	}

	/**
	 * Get audioVisualMediaProductionInformationModule
	 * 
	 * @return audioVisualMediaProductionInformationModule
	 **/
	@ApiModelProperty(value = "")
	public AudioVisualMediaProductionInformationModule getAudioVisualMediaProductionInformationModule() {
		return audioVisualMediaProductionInformationModule;
	}

	public void setAudioVisualMediaProductionInformationModule(
			AudioVisualMediaProductionInformationModule audioVisualMediaProductionInformationModule) {
		this.audioVisualMediaProductionInformationModule = audioVisualMediaProductionInformationModule;
	}

	public TradeItemInformation awardPrizeModule(AwardPrizeModule awardPrizeModule) {
		this.awardPrizeModule = awardPrizeModule;
		return this;
	}

	/**
	 * Get awardPrizeModule
	 * 
	 * @return awardPrizeModule
	 **/
	@ApiModelProperty(value = "")
	public AwardPrizeModule getAwardPrizeModule() {
		return awardPrizeModule;
	}

	public void setAwardPrizeModule(AwardPrizeModule awardPrizeModule) {
		this.awardPrizeModule = awardPrizeModule;
	}

	public TradeItemInformation batteryInformationModule(BatteryInformationModule batteryInformationModule) {
		this.batteryInformationModule = batteryInformationModule;
		return this;
	}

	/**
	 * Get batteryInformationModule
	 * 
	 * @return batteryInformationModule
	 **/
	@ApiModelProperty(value = "")
	public BatteryInformationModule getBatteryInformationModule() {
		return batteryInformationModule;
	}

	public void setBatteryInformationModule(BatteryInformationModule batteryInformationModule) {
		this.batteryInformationModule = batteryInformationModule;
	}

	public TradeItemInformation certificationInformationModule(
			CertificationInformationModule certificationInformationModule) {
		this.certificationInformationModule = certificationInformationModule;
		return this;
	}

	/**
	 * Get certificationInformationModule
	 * 
	 * @return certificationInformationModule
	 **/
	@ApiModelProperty(value = "")
	public CertificationInformationModule getCertificationInformationModule() {
		return certificationInformationModule;
	}

	public void setCertificationInformationModule(CertificationInformationModule certificationInformationModule) {
		this.certificationInformationModule = certificationInformationModule;
	}

	public TradeItemInformation chemicalRegulationInformationModule(
			ChemicalRegulationInformationModule chemicalRegulationInformationModule) {
		this.chemicalRegulationInformationModule = chemicalRegulationInformationModule;
		return this;
	}

	/**
	 * Get chemicalRegulationInformationModule
	 * 
	 * @return chemicalRegulationInformationModule
	 **/
	@ApiModelProperty(value = "")
	public ChemicalRegulationInformationModule getChemicalRegulationInformationModule() {
		return chemicalRegulationInformationModule;
	}

	public void setChemicalRegulationInformationModule(
			ChemicalRegulationInformationModule chemicalRegulationInformationModule) {
		this.chemicalRegulationInformationModule = chemicalRegulationInformationModule;
	}

	public TradeItemInformation childNutritionInformationModule(
			ChildNutritionInformationModule childNutritionInformationModule) {
		this.childNutritionInformationModule = childNutritionInformationModule;
		return this;
	}

	/**
	 * Get childNutritionInformationModule
	 * 
	 * @return childNutritionInformationModule
	 **/
	@ApiModelProperty(value = "")
	public ChildNutritionInformationModule getChildNutritionInformationModule() {
		return childNutritionInformationModule;
	}

	public void setChildNutritionInformationModule(ChildNutritionInformationModule childNutritionInformationModule) {
		this.childNutritionInformationModule = childNutritionInformationModule;
	}

	public TradeItemInformation consumerInstructionsModule(
			List<ConsumerInstructionsModule> consumerInstructionsModule) {
		this.consumerInstructionsModule = consumerInstructionsModule;
		return this;
	}

	public TradeItemInformation addConsumerInstructionsModuleItem(
			ConsumerInstructionsModule consumerInstructionsModuleItem) {
		if (this.consumerInstructionsModule == null) {
			this.consumerInstructionsModule = new ArrayList<ConsumerInstructionsModule>();
		}
		this.consumerInstructionsModule.add(consumerInstructionsModuleItem);
		return this;
	}

	/**
	 * Get consumerInstructionsModule
	 * 
	 * @return consumerInstructionsModule
	 **/
	@ApiModelProperty(value = "")
	public List<ConsumerInstructionsModule> getConsumerInstructionsModule() {
		return consumerInstructionsModule;
	}

	public void setConsumerInstructionsModule(List<ConsumerInstructionsModule> consumerInstructionsModule) {
		this.consumerInstructionsModule = consumerInstructionsModule;
	}

	public TradeItemInformation controlledSubstanceModule(ControlledSubstanceModule controlledSubstanceModule) {
		this.controlledSubstanceModule = controlledSubstanceModule;
		return this;
	}

	/**
	 * Get controlledSubstanceModule
	 * 
	 * @return controlledSubstanceModule
	 **/
	@ApiModelProperty(value = "")
	public ControlledSubstanceModule getControlledSubstanceModule() {
		return controlledSubstanceModule;
	}

	public void setControlledSubstanceModule(ControlledSubstanceModule controlledSubstanceModule) {
		this.controlledSubstanceModule = controlledSubstanceModule;
	}

	public TradeItemInformation dairyFishMeatPoultryItemModule(
			DairyFishMeatPoultryItemModule dairyFishMeatPoultryItemModule) {
		this.dairyFishMeatPoultryItemModule = dairyFishMeatPoultryItemModule;
		return this;
	}

	/**
	 * Get dairyFishMeatPoultryItemModule
	 * 
	 * @return dairyFishMeatPoultryItemModule
	 **/
	@ApiModelProperty(value = "")
	public DairyFishMeatPoultryItemModule getDairyFishMeatPoultryItemModule() {
		return dairyFishMeatPoultryItemModule;
	}

	public void setDairyFishMeatPoultryItemModule(DairyFishMeatPoultryItemModule dairyFishMeatPoultryItemModule) {
		this.dairyFishMeatPoultryItemModule = dairyFishMeatPoultryItemModule;
	}

	public TradeItemInformation dangerousSubstanceInformationModule(
			DangerousSubstanceInformationModule dangerousSubstanceInformationModule) {
		this.dangerousSubstanceInformationModule = dangerousSubstanceInformationModule;
		return this;
	}

	/**
	 * Get dangerousSubstanceInformationModule
	 * 
	 * @return dangerousSubstanceInformationModule
	 **/
	@ApiModelProperty(value = "")
	public DangerousSubstanceInformationModule getDangerousSubstanceInformationModule() {
		return dangerousSubstanceInformationModule;
	}

	public void setDangerousSubstanceInformationModule(
			DangerousSubstanceInformationModule dangerousSubstanceInformationModule) {
		this.dangerousSubstanceInformationModule = dangerousSubstanceInformationModule;
	}

	public TradeItemInformation deliveryPurchasingInformationModuleGroup(
			List<DeliveryPurchasingInformationModuleGroup> deliveryPurchasingInformationModuleGroup) {
		this.deliveryPurchasingInformationModuleGroup = deliveryPurchasingInformationModuleGroup;
		return this;
	}

	public TradeItemInformation addDeliveryPurchasingInformationModuleGroupItem(
			DeliveryPurchasingInformationModuleGroup deliveryPurchasingInformationModuleGroupItem) {
		if (this.deliveryPurchasingInformationModuleGroup == null) {
			this.deliveryPurchasingInformationModuleGroup = new ArrayList<DeliveryPurchasingInformationModuleGroup>();
		}
		this.deliveryPurchasingInformationModuleGroup.add(deliveryPurchasingInformationModuleGroupItem);
		return this;
	}

	/**
	 * Get deliveryPurchasingInformationModuleGroup
	 * 
	 * @return deliveryPurchasingInformationModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<DeliveryPurchasingInformationModuleGroup> getDeliveryPurchasingInformationModuleGroup() {
		return deliveryPurchasingInformationModuleGroup;
	}

	public void setDeliveryPurchasingInformationModuleGroup(
			List<DeliveryPurchasingInformationModuleGroup> deliveryPurchasingInformationModuleGroup) {
		this.deliveryPurchasingInformationModuleGroup = deliveryPurchasingInformationModuleGroup;
	}

	public TradeItemInformation dietInformationModule(DietInformationModule dietInformationModule) {
		this.dietInformationModule = dietInformationModule;
		return this;
	}

	/**
	 * Get dietInformationModule
	 * 
	 * @return dietInformationModule
	 **/
	@ApiModelProperty(value = "")
	public DietInformationModule getDietInformationModule() {
		return dietInformationModule;
	}

	public void setDietInformationModule(DietInformationModule dietInformationModule) {
		this.dietInformationModule = dietInformationModule;
	}

	public TradeItemInformation durableGoodsCharacteristicsModule(
			DurableGoodsCharacteristicsModule durableGoodsCharacteristicsModule) {
		this.durableGoodsCharacteristicsModule = durableGoodsCharacteristicsModule;
		return this;
	}

	/**
	 * Get durableGoodsCharacteristicsModule
	 * 
	 * @return durableGoodsCharacteristicsModule
	 **/
	@ApiModelProperty(value = "")
	public DurableGoodsCharacteristicsModule getDurableGoodsCharacteristicsModule() {
		return durableGoodsCharacteristicsModule;
	}

	public void setDurableGoodsCharacteristicsModule(
			DurableGoodsCharacteristicsModule durableGoodsCharacteristicsModule) {
		this.durableGoodsCharacteristicsModule = durableGoodsCharacteristicsModule;
	}

	public TradeItemInformation dutyFeeTaxInformationModule(DutyFeeTaxInformationModule dutyFeeTaxInformationModule) {
		this.dutyFeeTaxInformationModule = dutyFeeTaxInformationModule;
		return this;
	}

	/**
	 * Get dutyFeeTaxInformationModule
	 * 
	 * @return dutyFeeTaxInformationModule
	 **/
	@ApiModelProperty(value = "")
	public DutyFeeTaxInformationModule getDutyFeeTaxInformationModule() {
		return dutyFeeTaxInformationModule;
	}

	public void setDutyFeeTaxInformationModule(DutyFeeTaxInformationModule dutyFeeTaxInformationModule) {
		this.dutyFeeTaxInformationModule = dutyFeeTaxInformationModule;
	}

	public TradeItemInformation electronicDeviceCharacteristicsInformationModule(
			ElectronicDeviceCharacteristicsInformationModule electronicDeviceCharacteristicsInformationModule) {
		this.electronicDeviceCharacteristicsInformationModule = electronicDeviceCharacteristicsInformationModule;
		return this;
	}

	/**
	 * Get electronicDeviceCharacteristicsInformationModule
	 * 
	 * @return electronicDeviceCharacteristicsInformationModule
	 **/
	@ApiModelProperty(value = "")
	public ElectronicDeviceCharacteristicsInformationModule getElectronicDeviceCharacteristicsInformationModule() {
		return electronicDeviceCharacteristicsInformationModule;
	}

	public void setElectronicDeviceCharacteristicsInformationModule(
			ElectronicDeviceCharacteristicsInformationModule electronicDeviceCharacteristicsInformationModule) {
		this.electronicDeviceCharacteristicsInformationModule = electronicDeviceCharacteristicsInformationModule;
	}

	public TradeItemInformation farmingAndProcessingInformationModule(
			FarmingAndProcessingInformationModule farmingAndProcessingInformationModule) {
		this.farmingAndProcessingInformationModule = farmingAndProcessingInformationModule;
		return this;
	}

	/**
	 * Get farmingAndProcessingInformationModule
	 * 
	 * @return farmingAndProcessingInformationModule
	 **/
	@ApiModelProperty(value = "")
	public FarmingAndProcessingInformationModule getFarmingAndProcessingInformationModule() {
		return farmingAndProcessingInformationModule;
	}

	public void setFarmingAndProcessingInformationModule(
			FarmingAndProcessingInformationModule farmingAndProcessingInformationModule) {
		this.farmingAndProcessingInformationModule = farmingAndProcessingInformationModule;
	}

	public TradeItemInformation foodAndBeverageIngredientModule(
			List<FoodAndBeverageIngredientModule> foodAndBeverageIngredientModule) {
		this.foodAndBeverageIngredientModule = foodAndBeverageIngredientModule;
		return this;
	}

	public TradeItemInformation addFoodAndBeverageIngredientModuleItem(
			FoodAndBeverageIngredientModule foodAndBeverageIngredientModuleItem) {
		if (this.foodAndBeverageIngredientModule == null) {
			this.foodAndBeverageIngredientModule = new ArrayList<FoodAndBeverageIngredientModule>();
		}
		this.foodAndBeverageIngredientModule.add(foodAndBeverageIngredientModuleItem);
		return this;
	}

	/**
	 * Get foodAndBeverageIngredientModule
	 * 
	 * @return foodAndBeverageIngredientModule
	 **/
	@ApiModelProperty(value = "")
	public List<FoodAndBeverageIngredientModule> getFoodAndBeverageIngredientModule() {
		return foodAndBeverageIngredientModule;
	}

	public void setFoodAndBeverageIngredientModule(
			List<FoodAndBeverageIngredientModule> foodAndBeverageIngredientModule) {
		this.foodAndBeverageIngredientModule = foodAndBeverageIngredientModule;
	}

	public TradeItemInformation foodAndBeveragePreparationServingModule(
			List<FoodAndBeveragePreparationServingModule> foodAndBeveragePreparationServingModule) {
		this.foodAndBeveragePreparationServingModule = foodAndBeveragePreparationServingModule;
		return this;
	}

	public TradeItemInformation addFoodAndBeveragePreparationServingModuleItem(
			FoodAndBeveragePreparationServingModule foodAndBeveragePreparationServingModuleItem) {
		if (this.foodAndBeveragePreparationServingModule == null) {
			this.foodAndBeveragePreparationServingModule = new ArrayList<FoodAndBeveragePreparationServingModule>();
		}
		this.foodAndBeveragePreparationServingModule.add(foodAndBeveragePreparationServingModuleItem);
		return this;
	}

	/**
	 * Get foodAndBeveragePreparationServingModule
	 * 
	 * @return foodAndBeveragePreparationServingModule
	 **/
	@ApiModelProperty(value = "")
	public List<FoodAndBeveragePreparationServingModule> getFoodAndBeveragePreparationServingModule() {
		return foodAndBeveragePreparationServingModule;
	}

	public void setFoodAndBeveragePreparationServingModule(
			List<FoodAndBeveragePreparationServingModule> foodAndBeveragePreparationServingModule) {
		this.foodAndBeveragePreparationServingModule = foodAndBeveragePreparationServingModule;
	}

	public TradeItemInformation foodAndBeveragePropertiesInformationModule(
			FoodAndBeveragePropertiesInformationModule foodAndBeveragePropertiesInformationModule) {
		this.foodAndBeveragePropertiesInformationModule = foodAndBeveragePropertiesInformationModule;
		return this;
	}

	/**
	 * Get foodAndBeveragePropertiesInformationModule
	 * 
	 * @return foodAndBeveragePropertiesInformationModule
	 **/
	@ApiModelProperty(value = "")
	public FoodAndBeveragePropertiesInformationModule getFoodAndBeveragePropertiesInformationModule() {
		return foodAndBeveragePropertiesInformationModule;
	}

	public void setFoodAndBeveragePropertiesInformationModule(
			FoodAndBeveragePropertiesInformationModule foodAndBeveragePropertiesInformationModule) {
		this.foodAndBeveragePropertiesInformationModule = foodAndBeveragePropertiesInformationModule;
	}

	public TradeItemInformation healthRelatedInformationModule(
			HealthRelatedInformationModule healthRelatedInformationModule) {
		this.healthRelatedInformationModule = healthRelatedInformationModule;
		return this;
	}

	/**
	 * Get healthRelatedInformationModule
	 * 
	 * @return healthRelatedInformationModule
	 **/
	@ApiModelProperty(value = "")
	public HealthRelatedInformationModule getHealthRelatedInformationModule() {
		return healthRelatedInformationModule;
	}

	public void setHealthRelatedInformationModule(HealthRelatedInformationModule healthRelatedInformationModule) {
		this.healthRelatedInformationModule = healthRelatedInformationModule;
	}

	public TradeItemInformation healthWellnessPackagingMarkingModule(
			HealthWellnessPackagingMarkingModule healthWellnessPackagingMarkingModule) {
		this.healthWellnessPackagingMarkingModule = healthWellnessPackagingMarkingModule;
		return this;
	}

	/**
	 * Get healthWellnessPackagingMarkingModule
	 * 
	 * @return healthWellnessPackagingMarkingModule
	 **/
	@ApiModelProperty(value = "")
	public HealthWellnessPackagingMarkingModule getHealthWellnessPackagingMarkingModule() {
		return healthWellnessPackagingMarkingModule;
	}

	public void setHealthWellnessPackagingMarkingModule(
			HealthWellnessPackagingMarkingModule healthWellnessPackagingMarkingModule) {
		this.healthWellnessPackagingMarkingModule = healthWellnessPackagingMarkingModule;
	}

	public TradeItemInformation healthcareItemInformationModule(
			HealthcareItemInformationModule healthcareItemInformationModule) {
		this.healthcareItemInformationModule = healthcareItemInformationModule;
		return this;
	}

	/**
	 * Get healthcareItemInformationModule
	 * 
	 * @return healthcareItemInformationModule
	 **/
	@ApiModelProperty(value = "")
	public HealthcareItemInformationModule getHealthcareItemInformationModule() {
		return healthcareItemInformationModule;
	}

	public void setHealthcareItemInformationModule(HealthcareItemInformationModule healthcareItemInformationModule) {
		this.healthcareItemInformationModule = healthcareItemInformationModule;
	}

	public TradeItemInformation lightingDeviceModule(LightingDeviceModule lightingDeviceModule) {
		this.lightingDeviceModule = lightingDeviceModule;
		return this;
	}

	/**
	 * Get lightingDeviceModule
	 * 
	 * @return lightingDeviceModule
	 **/
	@ApiModelProperty(value = "")
	public LightingDeviceModule getLightingDeviceModule() {
		return lightingDeviceModule;
	}

	public void setLightingDeviceModule(LightingDeviceModule lightingDeviceModule) {
		this.lightingDeviceModule = lightingDeviceModule;
	}

	public TradeItemInformation marketingInformationModuleGroup(
			List<MarketingInformationModuleGroup> marketingInformationModuleGroup) {
		this.marketingInformationModuleGroup = marketingInformationModuleGroup;
		return this;
	}

	public TradeItemInformation addMarketingInformationModuleGroupItem(
			MarketingInformationModuleGroup marketingInformationModuleGroupItem) {
		if (this.marketingInformationModuleGroup == null) {
			this.marketingInformationModuleGroup = new ArrayList<MarketingInformationModuleGroup>();
		}
		this.marketingInformationModuleGroup.add(marketingInformationModuleGroupItem);
		return this;
	}

	/**
	 * Get marketingInformationModuleGroup
	 * 
	 * @return marketingInformationModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<MarketingInformationModuleGroup> getMarketingInformationModuleGroup() {
		return marketingInformationModuleGroup;
	}

	public void setMarketingInformationModuleGroup(
			List<MarketingInformationModuleGroup> marketingInformationModuleGroup) {
		this.marketingInformationModuleGroup = marketingInformationModuleGroup;
	}

	public TradeItemInformation medicalDeviceTradeItemModule(
			MedicalDeviceTradeItemModule medicalDeviceTradeItemModule) {
		this.medicalDeviceTradeItemModule = medicalDeviceTradeItemModule;
		return this;
	}

	/**
	 * Get medicalDeviceTradeItemModule
	 * 
	 * @return medicalDeviceTradeItemModule
	 **/
	@ApiModelProperty(value = "")
	public MedicalDeviceTradeItemModule getMedicalDeviceTradeItemModule() {
		return medicalDeviceTradeItemModule;
	}

	public void setMedicalDeviceTradeItemModule(MedicalDeviceTradeItemModule medicalDeviceTradeItemModule) {
		this.medicalDeviceTradeItemModule = medicalDeviceTradeItemModule;
	}

	public TradeItemInformation movieRevenueInformationModule(
			MovieRevenueInformationModule movieRevenueInformationModule) {
		this.movieRevenueInformationModule = movieRevenueInformationModule;
		return this;
	}

	/**
	 * Get movieRevenueInformationModule
	 * 
	 * @return movieRevenueInformationModule
	 **/
	@ApiModelProperty(value = "")
	public MovieRevenueInformationModule getMovieRevenueInformationModule() {
		return movieRevenueInformationModule;
	}

	public void setMovieRevenueInformationModule(MovieRevenueInformationModule movieRevenueInformationModule) {
		this.movieRevenueInformationModule = movieRevenueInformationModule;
	}

	public TradeItemInformation nonGTINLogisticsUnitInformationModule(
			NonGTINLogisticsUnitInformationModule nonGTINLogisticsUnitInformationModule) {
		this.nonGTINLogisticsUnitInformationModule = nonGTINLogisticsUnitInformationModule;
		return this;
	}

	/**
	 * Get nonGTINLogisticsUnitInformationModule
	 * 
	 * @return nonGTINLogisticsUnitInformationModule
	 **/
	@ApiModelProperty(value = "")
	public NonGTINLogisticsUnitInformationModule getNonGTINLogisticsUnitInformationModule() {
		return nonGTINLogisticsUnitInformationModule;
	}

	public void setNonGTINLogisticsUnitInformationModule(
			NonGTINLogisticsUnitInformationModule nonGTINLogisticsUnitInformationModule) {
		this.nonGTINLogisticsUnitInformationModule = nonGTINLogisticsUnitInformationModule;
	}

	public TradeItemInformation nonfoodIngredientModule(NonfoodIngredientModule nonfoodIngredientModule) {
		this.nonfoodIngredientModule = nonfoodIngredientModule;
		return this;
	}

	/**
	 * Get nonfoodIngredientModule
	 * 
	 * @return nonfoodIngredientModule
	 **/
	@ApiModelProperty(value = "")
	public NonfoodIngredientModule getNonfoodIngredientModule() {
		return nonfoodIngredientModule;
	}

	public void setNonfoodIngredientModule(NonfoodIngredientModule nonfoodIngredientModule) {
		this.nonfoodIngredientModule = nonfoodIngredientModule;
	}

	public TradeItemInformation nutritionalInformationModule(
			List<NutritionalInformationModule> nutritionalInformationModule) {
		this.nutritionalInformationModule = nutritionalInformationModule;
		return this;
	}

	public TradeItemInformation addNutritionalInformationModuleItem(
			NutritionalInformationModule nutritionalInformationModuleItem) {
		if (this.nutritionalInformationModule == null) {
			this.nutritionalInformationModule = new ArrayList<NutritionalInformationModule>();
		}
		this.nutritionalInformationModule.add(nutritionalInformationModuleItem);
		return this;
	}

	/**
	 * Get nutritionalInformationModule
	 * 
	 * @return nutritionalInformationModule
	 **/
	@ApiModelProperty(value = "")
	public List<NutritionalInformationModule> getNutritionalInformationModule() {
		return nutritionalInformationModule;
	}

	public void setNutritionalInformationModule(List<NutritionalInformationModule> nutritionalInformationModule) {
		this.nutritionalInformationModule = nutritionalInformationModule;
	}

	public TradeItemInformation organismClassificationModule(
			OrganismClassificationModule organismClassificationModule) {
		this.organismClassificationModule = organismClassificationModule;
		return this;
	}

	/**
	 * Get organismClassificationModule
	 * 
	 * @return organismClassificationModule
	 **/
	@ApiModelProperty(value = "")
	public OrganismClassificationModule getOrganismClassificationModule() {
		return organismClassificationModule;
	}

	public void setOrganismClassificationModule(OrganismClassificationModule organismClassificationModule) {
		this.organismClassificationModule = organismClassificationModule;
	}

	public TradeItemInformation packagingInformationModule(PackagingInformationModule packagingInformationModule) {
		this.packagingInformationModule = packagingInformationModule;
		return this;
	}

	/**
	 * Get packagingInformationModule
	 * 
	 * @return packagingInformationModule
	 **/
	@ApiModelProperty(value = "")
	public PackagingInformationModule getPackagingInformationModule() {
		return packagingInformationModule;
	}

	public void setPackagingInformationModule(PackagingInformationModule packagingInformationModule) {
		this.packagingInformationModule = packagingInformationModule;
	}

	public TradeItemInformation packagingMarkingModule(PackagingMarkingModule packagingMarkingModule) {
		this.packagingMarkingModule = packagingMarkingModule;
		return this;
	}

	/**
	 * Get packagingMarkingModule
	 * 
	 * @return packagingMarkingModule
	 **/
	@ApiModelProperty(value = "")
	public PackagingMarkingModule getPackagingMarkingModule() {
		return packagingMarkingModule;
	}

	public void setPackagingMarkingModule(PackagingMarkingModule packagingMarkingModule) {
		this.packagingMarkingModule = packagingMarkingModule;
	}

	public TradeItemInformation packagingSustainabilityModule(
			PackagingSustainabilityModule packagingSustainabilityModule) {
		this.packagingSustainabilityModule = packagingSustainabilityModule;
		return this;
	}

	/**
	 * Get packagingSustainabilityModule
	 * 
	 * @return packagingSustainabilityModule
	 **/
	@ApiModelProperty(value = "")
	public PackagingSustainabilityModule getPackagingSustainabilityModule() {
		return packagingSustainabilityModule;
	}

	public void setPackagingSustainabilityModule(PackagingSustainabilityModule packagingSustainabilityModule) {
		this.packagingSustainabilityModule = packagingSustainabilityModule;
	}

	public TradeItemInformation pharmaceuticalItemInformationModule(
			PharmaceuticalItemInformationModule pharmaceuticalItemInformationModule) {
		this.pharmaceuticalItemInformationModule = pharmaceuticalItemInformationModule;
		return this;
	}

	/**
	 * Get pharmaceuticalItemInformationModule
	 * 
	 * @return pharmaceuticalItemInformationModule
	 **/
	@ApiModelProperty(value = "")
	public PharmaceuticalItemInformationModule getPharmaceuticalItemInformationModule() {
		return pharmaceuticalItemInformationModule;
	}

	public void setPharmaceuticalItemInformationModule(
			PharmaceuticalItemInformationModule pharmaceuticalItemInformationModule) {
		this.pharmaceuticalItemInformationModule = pharmaceuticalItemInformationModule;
	}

	public TradeItemInformation physicalResourceUsageInformationModule(
			PhysicalResourceUsageInformationModule physicalResourceUsageInformationModule) {
		this.physicalResourceUsageInformationModule = physicalResourceUsageInformationModule;
		return this;
	}

	/**
	 * Get physicalResourceUsageInformationModule
	 * 
	 * @return physicalResourceUsageInformationModule
	 **/
	@ApiModelProperty(value = "")
	public PhysicalResourceUsageInformationModule getPhysicalResourceUsageInformationModule() {
		return physicalResourceUsageInformationModule;
	}

	public void setPhysicalResourceUsageInformationModule(
			PhysicalResourceUsageInformationModule physicalResourceUsageInformationModule) {
		this.physicalResourceUsageInformationModule = physicalResourceUsageInformationModule;
	}

	public TradeItemInformation placeOfItemActivityModule(PlaceOfItemActivityModule placeOfItemActivityModule) {
		this.placeOfItemActivityModule = placeOfItemActivityModule;
		return this;
	}

	/**
	 * Get placeOfItemActivityModule
	 * 
	 * @return placeOfItemActivityModule
	 **/
	@ApiModelProperty(value = "")
	public PlaceOfItemActivityModule getPlaceOfItemActivityModule() {
		return placeOfItemActivityModule;
	}

	public void setPlaceOfItemActivityModule(PlaceOfItemActivityModule placeOfItemActivityModule) {
		this.placeOfItemActivityModule = placeOfItemActivityModule;
	}

	public TradeItemInformation productCharacteristicsModule(
			ProductCharacteristicsModule productCharacteristicsModule) {
		this.productCharacteristicsModule = productCharacteristicsModule;
		return this;
	}

	/**
	 * Get productCharacteristicsModule
	 * 
	 * @return productCharacteristicsModule
	 **/
	@ApiModelProperty(value = "")
	public ProductCharacteristicsModule getProductCharacteristicsModule() {
		return productCharacteristicsModule;
	}

	public void setProductCharacteristicsModule(ProductCharacteristicsModule productCharacteristicsModule) {
		this.productCharacteristicsModule = productCharacteristicsModule;
	}

	public TradeItemInformation productFormulationStatementModule(
			ProductFormulationStatementModule productFormulationStatementModule) {
		this.productFormulationStatementModule = productFormulationStatementModule;
		return this;
	}

	/**
	 * Get productFormulationStatementModule
	 * 
	 * @return productFormulationStatementModule
	 **/
	@ApiModelProperty(value = "")
	public ProductFormulationStatementModule getProductFormulationStatementModule() {
		return productFormulationStatementModule;
	}

	public void setProductFormulationStatementModule(
			ProductFormulationStatementModule productFormulationStatementModule) {
		this.productFormulationStatementModule = productFormulationStatementModule;
	}

	public TradeItemInformation productionVariantCancelledDateTime(String productionVariantCancelledDateTime) {
		this.productionVariantCancelledDateTime = productionVariantCancelledDateTime;
		return this;
	}

	/**
	 * Get productionVariantCancelledDateTime
	 * 
	 * @return productionVariantCancelledDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getProductionVariantCancelledDateTime() {
		return productionVariantCancelledDateTime;
	}

	public void setProductionVariantCancelledDateTime(String productionVariantCancelledDateTime) {
		this.productionVariantCancelledDateTime = productionVariantCancelledDateTime;
	}

	public TradeItemInformation productionVariantDescription(LanguageLabels productionVariantDescription) {
		this.productionVariantDescription = productionVariantDescription;
		return this;
	}

	/**
	 * Get productionVariantDescription
	 * 
	 * @return productionVariantDescription
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getProductionVariantDescription() {
		return productionVariantDescription;
	}

	public void setProductionVariantDescription(LanguageLabels productionVariantDescription) {
		this.productionVariantDescription = productionVariantDescription;
	}

	public TradeItemInformation productionVariantDiscontinuedDateTime(String productionVariantDiscontinuedDateTime) {
		this.productionVariantDiscontinuedDateTime = productionVariantDiscontinuedDateTime;
		return this;
	}

	/**
	 * Get productionVariantDiscontinuedDateTime
	 * 
	 * @return productionVariantDiscontinuedDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getProductionVariantDiscontinuedDateTime() {
		return productionVariantDiscontinuedDateTime;
	}

	public void setProductionVariantDiscontinuedDateTime(String productionVariantDiscontinuedDateTime) {
		this.productionVariantDiscontinuedDateTime = productionVariantDiscontinuedDateTime;
	}

	public TradeItemInformation productionVariantEffectiveDateTime(String productionVariantEffectiveDateTime) {
		this.productionVariantEffectiveDateTime = productionVariantEffectiveDateTime;
		return this;
	}

	/**
	 * Get productionVariantEffectiveDateTime
	 * 
	 * @return productionVariantEffectiveDateTime
	 **/
	@ApiModelProperty(value = "")
	public String getProductionVariantEffectiveDateTime() {
		return productionVariantEffectiveDateTime;
	}

	public void setProductionVariantEffectiveDateTime(String productionVariantEffectiveDateTime) {
		this.productionVariantEffectiveDateTime = productionVariantEffectiveDateTime;
	}

	public TradeItemInformation promotionalItemInformationModuleGroup(
			List<PromotionalItemInformationModuleGroup> promotionalItemInformationModuleGroup) {
		this.promotionalItemInformationModuleGroup = promotionalItemInformationModuleGroup;
		return this;
	}

	public TradeItemInformation addPromotionalItemInformationModuleGroupItem(
			PromotionalItemInformationModuleGroup promotionalItemInformationModuleGroupItem) {
		if (this.promotionalItemInformationModuleGroup == null) {
			this.promotionalItemInformationModuleGroup = new ArrayList<PromotionalItemInformationModuleGroup>();
		}
		this.promotionalItemInformationModuleGroup.add(promotionalItemInformationModuleGroupItem);
		return this;
	}

	/**
	 * Get promotionalItemInformationModuleGroup
	 * 
	 * @return promotionalItemInformationModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<PromotionalItemInformationModuleGroup> getPromotionalItemInformationModuleGroup() {
		return promotionalItemInformationModuleGroup;
	}

	public void setPromotionalItemInformationModuleGroup(
			List<PromotionalItemInformationModuleGroup> promotionalItemInformationModuleGroup) {
		this.promotionalItemInformationModuleGroup = promotionalItemInformationModuleGroup;
	}

	public TradeItemInformation propellantInformationModule(PropellantInformationModule propellantInformationModule) {
		this.propellantInformationModule = propellantInformationModule;
		return this;
	}

	/**
	 * Get propellantInformationModule
	 * 
	 * @return propellantInformationModule
	 **/
	@ApiModelProperty(value = "")
	public PropellantInformationModule getPropellantInformationModule() {
		return propellantInformationModule;
	}

	public void setPropellantInformationModule(PropellantInformationModule propellantInformationModule) {
		this.propellantInformationModule = propellantInformationModule;
	}

	public TradeItemInformation publicationTitleRatingModule(
			PublicationTitleRatingModule publicationTitleRatingModule) {
		this.publicationTitleRatingModule = publicationTitleRatingModule;
		return this;
	}

	/**
	 * Get publicationTitleRatingModule
	 * 
	 * @return publicationTitleRatingModule
	 **/
	@ApiModelProperty(value = "")
	public PublicationTitleRatingModule getPublicationTitleRatingModule() {
		return publicationTitleRatingModule;
	}

	public void setPublicationTitleRatingModule(PublicationTitleRatingModule publicationTitleRatingModule) {
		this.publicationTitleRatingModule = publicationTitleRatingModule;
	}

	public TradeItemInformation referencedFileDetailInformationModule(
			ReferencedFileDetailInformationModule referencedFileDetailInformationModule) {
		this.referencedFileDetailInformationModule = referencedFileDetailInformationModule;
		return this;
	}

	/**
	 * Get referencedFileDetailInformationModule
	 * 
	 * @return referencedFileDetailInformationModule
	 **/
	@ApiModelProperty(value = "")
	public ReferencedFileDetailInformationModule getReferencedFileDetailInformationModule() {
		return referencedFileDetailInformationModule;
	}

	public void setReferencedFileDetailInformationModule(
			ReferencedFileDetailInformationModule referencedFileDetailInformationModule) {
		this.referencedFileDetailInformationModule = referencedFileDetailInformationModule;
	}

	public TradeItemInformation regulatedTradeItemModule(RegulatedTradeItemModule regulatedTradeItemModule) {
		this.regulatedTradeItemModule = regulatedTradeItemModule;
		return this;
	}

	/**
	 * Get regulatedTradeItemModule
	 * 
	 * @return regulatedTradeItemModule
	 **/
	@ApiModelProperty(value = "")
	public RegulatedTradeItemModule getRegulatedTradeItemModule() {
		return regulatedTradeItemModule;
	}

	public void setRegulatedTradeItemModule(RegulatedTradeItemModule regulatedTradeItemModule) {
		this.regulatedTradeItemModule = regulatedTradeItemModule;
	}

	public TradeItemInformation safetyDataSheetModule(SafetyDataSheetModule safetyDataSheetModule) {
		this.safetyDataSheetModule = safetyDataSheetModule;
		return this;
	}

	/**
	 * Get safetyDataSheetModule
	 * 
	 * @return safetyDataSheetModule
	 **/
	@ApiModelProperty(value = "")
	public SafetyDataSheetModule getSafetyDataSheetModule() {
		return safetyDataSheetModule;
	}

	public void setSafetyDataSheetModule(SafetyDataSheetModule safetyDataSheetModule) {
		this.safetyDataSheetModule = safetyDataSheetModule;
	}

	public TradeItemInformation salesInformationModuleGroup(
			List<SalesInformationModuleGroup> salesInformationModuleGroup) {
		this.salesInformationModuleGroup = salesInformationModuleGroup;
		return this;
	}

	public TradeItemInformation addSalesInformationModuleGroupItem(
			SalesInformationModuleGroup salesInformationModuleGroupItem) {
		if (this.salesInformationModuleGroup == null) {
			this.salesInformationModuleGroup = new ArrayList<SalesInformationModuleGroup>();
		}
		this.salesInformationModuleGroup.add(salesInformationModuleGroupItem);
		return this;
	}

	/**
	 * Get salesInformationModuleGroup
	 * 
	 * @return salesInformationModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<SalesInformationModuleGroup> getSalesInformationModuleGroup() {
		return salesInformationModuleGroup;
	}

	public void setSalesInformationModuleGroup(List<SalesInformationModuleGroup> salesInformationModuleGroup) {
		this.salesInformationModuleGroup = salesInformationModuleGroup;
	}

	public TradeItemInformation securityTagInformationModule(
			SecurityTagInformationModule securityTagInformationModule) {
		this.securityTagInformationModule = securityTagInformationModule;
		return this;
	}

	/**
	 * Get securityTagInformationModule
	 * 
	 * @return securityTagInformationModule
	 **/
	@ApiModelProperty(value = "")
	public SecurityTagInformationModule getSecurityTagInformationModule() {
		return securityTagInformationModule;
	}

	public void setSecurityTagInformationModule(SecurityTagInformationModule securityTagInformationModule) {
		this.securityTagInformationModule = securityTagInformationModule;
	}

	public TradeItemInformation sustainabilityModule(SustainabilityModule sustainabilityModule) {
		this.sustainabilityModule = sustainabilityModule;
		return this;
	}

	/**
	 * Get sustainabilityModule
	 * 
	 * @return sustainabilityModule
	 **/
	@ApiModelProperty(value = "")
	public SustainabilityModule getSustainabilityModule() {
		return sustainabilityModule;
	}

	public void setSustainabilityModule(SustainabilityModule sustainabilityModule) {
		this.sustainabilityModule = sustainabilityModule;
	}

	public TradeItemInformation textileMaterialModule(TextileMaterialModule textileMaterialModule) {
		this.textileMaterialModule = textileMaterialModule;
		return this;
	}

	/**
	 * Get textileMaterialModule
	 * 
	 * @return textileMaterialModule
	 **/
	@ApiModelProperty(value = "")
	public TextileMaterialModule getTextileMaterialModule() {
		return textileMaterialModule;
	}

	public void setTextileMaterialModule(TextileMaterialModule textileMaterialModule) {
		this.textileMaterialModule = textileMaterialModule;
	}

	public TradeItemInformation tradeItemComponents(TradeItemComponents tradeItemComponents) {
		this.tradeItemComponents = tradeItemComponents;
		return this;
	}

	/**
	 * Get tradeItemComponents
	 * 
	 * @return tradeItemComponents
	 **/
	@ApiModelProperty(value = "")
	public TradeItemComponents getTradeItemComponents() {
		return tradeItemComponents;
	}

	public void setTradeItemComponents(TradeItemComponents tradeItemComponents) {
		this.tradeItemComponents = tradeItemComponents;
	}

	public TradeItemInformation tradeItemDataCarrierAndIdentificationModule(
			TradeItemDataCarrierAndIdentificationModule tradeItemDataCarrierAndIdentificationModule) {
		this.tradeItemDataCarrierAndIdentificationModule = tradeItemDataCarrierAndIdentificationModule;
		return this;
	}

	/**
	 * Get tradeItemDataCarrierAndIdentificationModule
	 * 
	 * @return tradeItemDataCarrierAndIdentificationModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemDataCarrierAndIdentificationModule getTradeItemDataCarrierAndIdentificationModule() {
		return tradeItemDataCarrierAndIdentificationModule;
	}

	public void setTradeItemDataCarrierAndIdentificationModule(
			TradeItemDataCarrierAndIdentificationModule tradeItemDataCarrierAndIdentificationModule) {
		this.tradeItemDataCarrierAndIdentificationModule = tradeItemDataCarrierAndIdentificationModule;
	}

	public TradeItemInformation tradeItemDescriptionModule(TradeItemDescriptionModule tradeItemDescriptionModule) {
		this.tradeItemDescriptionModule = tradeItemDescriptionModule;
		return this;
	}

	/**
	 * Get tradeItemDescriptionModule
	 * 
	 * @return tradeItemDescriptionModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemDescriptionModule getTradeItemDescriptionModule() {
		return tradeItemDescriptionModule;
	}

	public void setTradeItemDescriptionModule(TradeItemDescriptionModule tradeItemDescriptionModule) {
		this.tradeItemDescriptionModule = tradeItemDescriptionModule;
	}

	public TradeItemInformation tradeItemDisposalInformationModule(
			TradeItemDisposalInformationModule tradeItemDisposalInformationModule) {
		this.tradeItemDisposalInformationModule = tradeItemDisposalInformationModule;
		return this;
	}

	/**
	 * Get tradeItemDisposalInformationModule
	 * 
	 * @return tradeItemDisposalInformationModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemDisposalInformationModule getTradeItemDisposalInformationModule() {
		return tradeItemDisposalInformationModule;
	}

	public void setTradeItemDisposalInformationModule(
			TradeItemDisposalInformationModule tradeItemDisposalInformationModule) {
		this.tradeItemDisposalInformationModule = tradeItemDisposalInformationModule;
	}

	public TradeItemInformation tradeItemFeatureBenefitExtended(LanguageLabels tradeItemFeatureBenefitExtended) {
		this.tradeItemFeatureBenefitExtended = tradeItemFeatureBenefitExtended;
		return this;
	}

	/**
	 * Get tradeItemFeatureBenefitExtended
	 * 
	 * @return tradeItemFeatureBenefitExtended
	 **/
	@ApiModelProperty(value = "")
	public LanguageLabels getTradeItemFeatureBenefitExtended() {
		return tradeItemFeatureBenefitExtended;
	}

	public void setTradeItemFeatureBenefitExtended(LanguageLabels tradeItemFeatureBenefitExtended) {
		this.tradeItemFeatureBenefitExtended = tradeItemFeatureBenefitExtended;
	}

	public TradeItemInformation tradeItemHandlingModule(TradeItemHandlingModule tradeItemHandlingModule) {
		this.tradeItemHandlingModule = tradeItemHandlingModule;
		return this;
	}

	/**
	 * Get tradeItemHandlingModule
	 * 
	 * @return tradeItemHandlingModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemHandlingModule getTradeItemHandlingModule() {
		return tradeItemHandlingModule;
	}

	public void setTradeItemHandlingModule(TradeItemHandlingModule tradeItemHandlingModule) {
		this.tradeItemHandlingModule = tradeItemHandlingModule;
	}

	public TradeItemInformation tradeItemHierarchyModule(TradeItemHierarchyModule tradeItemHierarchyModule) {
		this.tradeItemHierarchyModule = tradeItemHierarchyModule;
		return this;
	}

	/**
	 * Get tradeItemHierarchyModule
	 * 
	 * @return tradeItemHierarchyModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemHierarchyModule getTradeItemHierarchyModule() {
		return tradeItemHierarchyModule;
	}

	public void setTradeItemHierarchyModule(TradeItemHierarchyModule tradeItemHierarchyModule) {
		this.tradeItemHierarchyModule = tradeItemHierarchyModule;
	}

	public TradeItemInformation tradeItemHumidityInformationModule(
			TradeItemHumidityInformationModule tradeItemHumidityInformationModule) {
		this.tradeItemHumidityInformationModule = tradeItemHumidityInformationModule;
		return this;
	}

	/**
	 * Get tradeItemHumidityInformationModule
	 * 
	 * @return tradeItemHumidityInformationModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemHumidityInformationModule getTradeItemHumidityInformationModule() {
		return tradeItemHumidityInformationModule;
	}

	public void setTradeItemHumidityInformationModule(
			TradeItemHumidityInformationModule tradeItemHumidityInformationModule) {
		this.tradeItemHumidityInformationModule = tradeItemHumidityInformationModule;
	}

	public TradeItemInformation tradeItemLicensingModule(TradeItemLicensingModule tradeItemLicensingModule) {
		this.tradeItemLicensingModule = tradeItemLicensingModule;
		return this;
	}

	/**
	 * Get tradeItemLicensingModule
	 * 
	 * @return tradeItemLicensingModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemLicensingModule getTradeItemLicensingModule() {
		return tradeItemLicensingModule;
	}

	public void setTradeItemLicensingModule(TradeItemLicensingModule tradeItemLicensingModule) {
		this.tradeItemLicensingModule = tradeItemLicensingModule;
	}

	public TradeItemInformation tradeItemLifespanModuleGroup(
			List<TradeItemLifespanModuleGroup> tradeItemLifespanModuleGroup) {
		this.tradeItemLifespanModuleGroup = tradeItemLifespanModuleGroup;
		return this;
	}

	public TradeItemInformation addTradeItemLifespanModuleGroupItem(
			TradeItemLifespanModuleGroup tradeItemLifespanModuleGroupItem) {
		if (this.tradeItemLifespanModuleGroup == null) {
			this.tradeItemLifespanModuleGroup = new ArrayList<TradeItemLifespanModuleGroup>();
		}
		this.tradeItemLifespanModuleGroup.add(tradeItemLifespanModuleGroupItem);
		return this;
	}

	/**
	 * Get tradeItemLifespanModuleGroup
	 * 
	 * @return tradeItemLifespanModuleGroup
	 **/
	@ApiModelProperty(value = "")
	public List<TradeItemLifespanModuleGroup> getTradeItemLifespanModuleGroup() {
		return tradeItemLifespanModuleGroup;
	}

	public void setTradeItemLifespanModuleGroup(List<TradeItemLifespanModuleGroup> tradeItemLifespanModuleGroup) {
		this.tradeItemLifespanModuleGroup = tradeItemLifespanModuleGroup;
	}

	public TradeItemInformation tradeItemMeasurementsModule(TradeItemMeasurementsModule tradeItemMeasurementsModule) {
		this.tradeItemMeasurementsModule = tradeItemMeasurementsModule;
		return this;
	}

	/**
	 * Get tradeItemMeasurementsModule
	 * 
	 * @return tradeItemMeasurementsModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemMeasurementsModule getTradeItemMeasurementsModule() {
		return tradeItemMeasurementsModule;
	}

	public void setTradeItemMeasurementsModule(TradeItemMeasurementsModule tradeItemMeasurementsModule) {
		this.tradeItemMeasurementsModule = tradeItemMeasurementsModule;
	}

	public TradeItemInformation tradeItemSizeModule(TradeItemSizeModule tradeItemSizeModule) {
		this.tradeItemSizeModule = tradeItemSizeModule;
		return this;
	}

	/**
	 * Get tradeItemSizeModule
	 * 
	 * @return tradeItemSizeModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemSizeModule getTradeItemSizeModule() {
		return tradeItemSizeModule;
	}

	public void setTradeItemSizeModule(TradeItemSizeModule tradeItemSizeModule) {
		this.tradeItemSizeModule = tradeItemSizeModule;
	}

	public TradeItemInformation tradeItemTemperatureInformationModule(
			TradeItemTemperatureInformationModule tradeItemTemperatureInformationModule) {
		this.tradeItemTemperatureInformationModule = tradeItemTemperatureInformationModule;
		return this;
	}

	/**
	 * Get tradeItemTemperatureInformationModule
	 * 
	 * @return tradeItemTemperatureInformationModule
	 **/
	@ApiModelProperty(value = "")
	public TradeItemTemperatureInformationModule getTradeItemTemperatureInformationModule() {
		return tradeItemTemperatureInformationModule;
	}

	public void setTradeItemTemperatureInformationModule(
			TradeItemTemperatureInformationModule tradeItemTemperatureInformationModule) {
		this.tradeItemTemperatureInformationModule = tradeItemTemperatureInformationModule;
	}

	public TradeItemInformation transportationHazardousClassificationModule(
			TransportationHazardousClassificationModule transportationHazardousClassificationModule) {
		this.transportationHazardousClassificationModule = transportationHazardousClassificationModule;
		return this;
	}

	/**
	 * Get transportationHazardousClassificationModule
	 * 
	 * @return transportationHazardousClassificationModule
	 **/
	@ApiModelProperty(value = "")
	public TransportationHazardousClassificationModule getTransportationHazardousClassificationModule() {
		return transportationHazardousClassificationModule;
	}

	public void setTransportationHazardousClassificationModule(
			TransportationHazardousClassificationModule transportationHazardousClassificationModule) {
		this.transportationHazardousClassificationModule = transportationHazardousClassificationModule;
	}

	public TradeItemInformation variableTradeItemInformationModule(
			VariableTradeItemInformationModule variableTradeItemInformationModule) {
		this.variableTradeItemInformationModule = variableTradeItemInformationModule;
		return this;
	}

	/**
	 * Get variableTradeItemInformationModule
	 * 
	 * @return variableTradeItemInformationModule
	 **/
	@ApiModelProperty(value = "")
	public VariableTradeItemInformationModule getVariableTradeItemInformationModule() {
		return variableTradeItemInformationModule;
	}

	public void setVariableTradeItemInformationModule(
			VariableTradeItemInformationModule variableTradeItemInformationModule) {
		this.variableTradeItemInformationModule = variableTradeItemInformationModule;
	}

	public TradeItemInformation videoDisplayDeviceInformationModule(
			VideoDisplayDeviceInformationModule videoDisplayDeviceInformationModule) {
		this.videoDisplayDeviceInformationModule = videoDisplayDeviceInformationModule;
		return this;
	}

	/**
	 * Get videoDisplayDeviceInformationModule
	 * 
	 * @return videoDisplayDeviceInformationModule
	 **/
	@ApiModelProperty(value = "")
	public VideoDisplayDeviceInformationModule getVideoDisplayDeviceInformationModule() {
		return videoDisplayDeviceInformationModule;
	}

	public void setVideoDisplayDeviceInformationModule(
			VideoDisplayDeviceInformationModule videoDisplayDeviceInformationModule) {
		this.videoDisplayDeviceInformationModule = videoDisplayDeviceInformationModule;
	}

	public TradeItemInformation warrantyInformationModule(WarrantyInformationModule warrantyInformationModule) {
		this.warrantyInformationModule = warrantyInformationModule;
		return this;
	}

	/**
	 * Get warrantyInformationModule
	 * 
	 * @return warrantyInformationModule
	 **/
	@ApiModelProperty(value = "")
	public WarrantyInformationModule getWarrantyInformationModule() {
		return warrantyInformationModule;
	}

	public void setWarrantyInformationModule(WarrantyInformationModule warrantyInformationModule) {
		this.warrantyInformationModule = warrantyInformationModule;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TradeItemInformation tradeItemInformation = (TradeItemInformation) o;
		return Objects.equals(this.alcoholInformationModule, tradeItemInformation.alcoholInformationModule)
				&& Objects.equals(this.allergenInformationModuleGroup,
						tradeItemInformation.allergenInformationModuleGroup)
				&& Objects.equals(this.animalFeedingModule, tradeItemInformation.animalFeedingModule)
				&& Objects.equals(this.apparelInformationModule, tradeItemInformation.apparelInformationModule)
				&& Objects.equals(this.audienceOrPlayerInformationModule,
						tradeItemInformation.audienceOrPlayerInformationModule)
				&& Objects.equals(this.audioVisualMediaContentInformationModule,
						tradeItemInformation.audioVisualMediaContentInformationModule)
				&& Objects.equals(this.audioVisualMediaProductDescriptionInformationModule,
						tradeItemInformation.audioVisualMediaProductDescriptionInformationModule)
				&& Objects.equals(this.audioVisualMediaProductionInformationModule,
						tradeItemInformation.audioVisualMediaProductionInformationModule)
				&& Objects.equals(this.awardPrizeModule, tradeItemInformation.awardPrizeModule)
				&& Objects.equals(this.batteryInformationModule, tradeItemInformation.batteryInformationModule)
				&& Objects.equals(this.certificationInformationModule,
						tradeItemInformation.certificationInformationModule)
				&& Objects.equals(this.chemicalRegulationInformationModule,
						tradeItemInformation.chemicalRegulationInformationModule)
				&& Objects.equals(this.childNutritionInformationModule,
						tradeItemInformation.childNutritionInformationModule)
				&& Objects.equals(this.consumerInstructionsModule, tradeItemInformation.consumerInstructionsModule)
				&& Objects.equals(this.controlledSubstanceModule, tradeItemInformation.controlledSubstanceModule)
				&& Objects.equals(this.dairyFishMeatPoultryItemModule,
						tradeItemInformation.dairyFishMeatPoultryItemModule)
				&& Objects.equals(this.dangerousSubstanceInformationModule,
						tradeItemInformation.dangerousSubstanceInformationModule)
				&& Objects.equals(this.deliveryPurchasingInformationModuleGroup,
						tradeItemInformation.deliveryPurchasingInformationModuleGroup)
				&& Objects.equals(this.dietInformationModule, tradeItemInformation.dietInformationModule)
				&& Objects.equals(this.durableGoodsCharacteristicsModule,
						tradeItemInformation.durableGoodsCharacteristicsModule)
				&& Objects.equals(this.dutyFeeTaxInformationModule, tradeItemInformation.dutyFeeTaxInformationModule)
				&& Objects.equals(this.electronicDeviceCharacteristicsInformationModule,
						tradeItemInformation.electronicDeviceCharacteristicsInformationModule)
				&& Objects.equals(this.farmingAndProcessingInformationModule,
						tradeItemInformation.farmingAndProcessingInformationModule)
				&& Objects.equals(this.foodAndBeverageIngredientModule,
						tradeItemInformation.foodAndBeverageIngredientModule)
				&& Objects.equals(this.foodAndBeveragePreparationServingModule,
						tradeItemInformation.foodAndBeveragePreparationServingModule)
				&& Objects.equals(this.foodAndBeveragePropertiesInformationModule,
						tradeItemInformation.foodAndBeveragePropertiesInformationModule)
				&& Objects.equals(this.healthRelatedInformationModule,
						tradeItemInformation.healthRelatedInformationModule)
				&& Objects.equals(this.healthWellnessPackagingMarkingModule,
						tradeItemInformation.healthWellnessPackagingMarkingModule)
				&& Objects.equals(this.healthcareItemInformationModule,
						tradeItemInformation.healthcareItemInformationModule)
				&& Objects.equals(this.lightingDeviceModule, tradeItemInformation.lightingDeviceModule)
				&& Objects.equals(this.marketingInformationModuleGroup,
						tradeItemInformation.marketingInformationModuleGroup)
				&& Objects.equals(this.medicalDeviceTradeItemModule, tradeItemInformation.medicalDeviceTradeItemModule)
				&& Objects.equals(this.movieRevenueInformationModule,
						tradeItemInformation.movieRevenueInformationModule)
				&& Objects.equals(this.nonGTINLogisticsUnitInformationModule,
						tradeItemInformation.nonGTINLogisticsUnitInformationModule)
				&& Objects.equals(this.nonfoodIngredientModule, tradeItemInformation.nonfoodIngredientModule)
				&& Objects.equals(this.nutritionalInformationModule, tradeItemInformation.nutritionalInformationModule)
				&& Objects.equals(this.organismClassificationModule, tradeItemInformation.organismClassificationModule)
				&& Objects.equals(this.packagingInformationModule, tradeItemInformation.packagingInformationModule)
				&& Objects.equals(this.packagingMarkingModule, tradeItemInformation.packagingMarkingModule)
				&& Objects.equals(this.packagingSustainabilityModule,
						tradeItemInformation.packagingSustainabilityModule)
				&& Objects.equals(this.pharmaceuticalItemInformationModule,
						tradeItemInformation.pharmaceuticalItemInformationModule)
				&& Objects.equals(this.physicalResourceUsageInformationModule,
						tradeItemInformation.physicalResourceUsageInformationModule)
				&& Objects.equals(this.placeOfItemActivityModule, tradeItemInformation.placeOfItemActivityModule)
				&& Objects.equals(this.productCharacteristicsModule, tradeItemInformation.productCharacteristicsModule)
				&& Objects.equals(this.productFormulationStatementModule,
						tradeItemInformation.productFormulationStatementModule)
				&& Objects.equals(this.productionVariantCancelledDateTime,
						tradeItemInformation.productionVariantCancelledDateTime)
				&& Objects.equals(this.productionVariantDescription, tradeItemInformation.productionVariantDescription)
				&& Objects.equals(this.productionVariantDiscontinuedDateTime,
						tradeItemInformation.productionVariantDiscontinuedDateTime)
				&& Objects.equals(this.productionVariantEffectiveDateTime,
						tradeItemInformation.productionVariantEffectiveDateTime)
				&& Objects.equals(this.promotionalItemInformationModuleGroup,
						tradeItemInformation.promotionalItemInformationModuleGroup)
				&& Objects.equals(this.propellantInformationModule, tradeItemInformation.propellantInformationModule)
				&& Objects.equals(this.publicationTitleRatingModule, tradeItemInformation.publicationTitleRatingModule)
				&& Objects.equals(this.referencedFileDetailInformationModule,
						tradeItemInformation.referencedFileDetailInformationModule)
				&& Objects.equals(this.regulatedTradeItemModule, tradeItemInformation.regulatedTradeItemModule)
				&& Objects.equals(this.safetyDataSheetModule, tradeItemInformation.safetyDataSheetModule)
				&& Objects.equals(this.salesInformationModuleGroup, tradeItemInformation.salesInformationModuleGroup)
				&& Objects.equals(this.securityTagInformationModule, tradeItemInformation.securityTagInformationModule)
				&& Objects.equals(this.sustainabilityModule, tradeItemInformation.sustainabilityModule)
				&& Objects.equals(this.textileMaterialModule, tradeItemInformation.textileMaterialModule)
				&& Objects.equals(this.tradeItemComponents, tradeItemInformation.tradeItemComponents)
				&& Objects.equals(this.tradeItemDataCarrierAndIdentificationModule,
						tradeItemInformation.tradeItemDataCarrierAndIdentificationModule)
				&& Objects.equals(this.tradeItemDescriptionModule, tradeItemInformation.tradeItemDescriptionModule)
				&& Objects.equals(this.tradeItemDisposalInformationModule,
						tradeItemInformation.tradeItemDisposalInformationModule)
				&& Objects.equals(this.tradeItemFeatureBenefitExtended,
						tradeItemInformation.tradeItemFeatureBenefitExtended)
				&& Objects.equals(this.tradeItemHandlingModule, tradeItemInformation.tradeItemHandlingModule)
				&& Objects.equals(this.tradeItemHierarchyModule, tradeItemInformation.tradeItemHierarchyModule)
				&& Objects.equals(this.tradeItemHumidityInformationModule,
						tradeItemInformation.tradeItemHumidityInformationModule)
				&& Objects.equals(this.tradeItemLicensingModule, tradeItemInformation.tradeItemLicensingModule)
				&& Objects.equals(this.tradeItemLifespanModuleGroup, tradeItemInformation.tradeItemLifespanModuleGroup)
				&& Objects.equals(this.tradeItemMeasurementsModule, tradeItemInformation.tradeItemMeasurementsModule)
				&& Objects.equals(this.tradeItemSizeModule, tradeItemInformation.tradeItemSizeModule)
				&& Objects.equals(this.tradeItemTemperatureInformationModule,
						tradeItemInformation.tradeItemTemperatureInformationModule)
				&& Objects.equals(this.transportationHazardousClassificationModule,
						tradeItemInformation.transportationHazardousClassificationModule)
				&& Objects.equals(this.variableTradeItemInformationModule,
						tradeItemInformation.variableTradeItemInformationModule)
				&& Objects.equals(this.videoDisplayDeviceInformationModule,
						tradeItemInformation.videoDisplayDeviceInformationModule)
				&& Objects.equals(this.warrantyInformationModule, tradeItemInformation.warrantyInformationModule);
	}

	@Override
	public int hashCode() {
		return Objects.hash(alcoholInformationModule, allergenInformationModuleGroup, animalFeedingModule,
				apparelInformationModule, audienceOrPlayerInformationModule, audioVisualMediaContentInformationModule,
				audioVisualMediaProductDescriptionInformationModule, audioVisualMediaProductionInformationModule,
				awardPrizeModule, batteryInformationModule, certificationInformationModule,
				chemicalRegulationInformationModule, childNutritionInformationModule, consumerInstructionsModule,
				controlledSubstanceModule, dairyFishMeatPoultryItemModule, dangerousSubstanceInformationModule,
				deliveryPurchasingInformationModuleGroup, dietInformationModule, durableGoodsCharacteristicsModule,
				dutyFeeTaxInformationModule, electronicDeviceCharacteristicsInformationModule,
				farmingAndProcessingInformationModule, foodAndBeverageIngredientModule,
				foodAndBeveragePreparationServingModule, foodAndBeveragePropertiesInformationModule,
				healthRelatedInformationModule, healthWellnessPackagingMarkingModule, healthcareItemInformationModule,
				lightingDeviceModule, marketingInformationModuleGroup, medicalDeviceTradeItemModule,
				movieRevenueInformationModule, nonGTINLogisticsUnitInformationModule, nonfoodIngredientModule,
				nutritionalInformationModule, organismClassificationModule, packagingInformationModule,
				packagingMarkingModule, packagingSustainabilityModule, pharmaceuticalItemInformationModule,
				physicalResourceUsageInformationModule, placeOfItemActivityModule, productCharacteristicsModule,
				productFormulationStatementModule, productionVariantCancelledDateTime, productionVariantDescription,
				productionVariantDiscontinuedDateTime, productionVariantEffectiveDateTime,
				promotionalItemInformationModuleGroup, propellantInformationModule, publicationTitleRatingModule,
				referencedFileDetailInformationModule, regulatedTradeItemModule, safetyDataSheetModule,
				salesInformationModuleGroup, securityTagInformationModule, sustainabilityModule, textileMaterialModule,
				tradeItemComponents, tradeItemDataCarrierAndIdentificationModule, tradeItemDescriptionModule,
				tradeItemDisposalInformationModule, tradeItemFeatureBenefitExtended, tradeItemHandlingModule,
				tradeItemHierarchyModule, tradeItemHumidityInformationModule, tradeItemLicensingModule,
				tradeItemLifespanModuleGroup, tradeItemMeasurementsModule, tradeItemSizeModule,
				tradeItemTemperatureInformationModule, transportationHazardousClassificationModule,
				variableTradeItemInformationModule, videoDisplayDeviceInformationModule, warrantyInformationModule);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TradeItemInformation {\n");

		sb.append("    alcoholInformationModule: ").append(toIndentedString(alcoholInformationModule)).append("\n");
		sb.append("    allergenInformationModuleGroup: ").append(toIndentedString(allergenInformationModuleGroup))
				.append("\n");
		sb.append("    animalFeedingModule: ").append(toIndentedString(animalFeedingModule)).append("\n");
		sb.append("    apparelInformationModule: ").append(toIndentedString(apparelInformationModule)).append("\n");
		sb.append("    audienceOrPlayerInformationModule: ").append(toIndentedString(audienceOrPlayerInformationModule))
				.append("\n");
		sb.append("    audioVisualMediaContentInformationModule: ")
				.append(toIndentedString(audioVisualMediaContentInformationModule)).append("\n");
		sb.append("    audioVisualMediaProductDescriptionInformationModule: ")
				.append(toIndentedString(audioVisualMediaProductDescriptionInformationModule)).append("\n");
		sb.append("    audioVisualMediaProductionInformationModule: ")
				.append(toIndentedString(audioVisualMediaProductionInformationModule)).append("\n");
		sb.append("    awardPrizeModule: ").append(toIndentedString(awardPrizeModule)).append("\n");
		sb.append("    batteryInformationModule: ").append(toIndentedString(batteryInformationModule)).append("\n");
		sb.append("    certificationInformationModule: ").append(toIndentedString(certificationInformationModule))
				.append("\n");
		sb.append("    chemicalRegulationInformationModule: ")
				.append(toIndentedString(chemicalRegulationInformationModule)).append("\n");
		sb.append("    childNutritionInformationModule: ").append(toIndentedString(childNutritionInformationModule))
				.append("\n");
		sb.append("    consumerInstructionsModule: ").append(toIndentedString(consumerInstructionsModule)).append("\n");
		sb.append("    controlledSubstanceModule: ").append(toIndentedString(controlledSubstanceModule)).append("\n");
		sb.append("    dairyFishMeatPoultryItemModule: ").append(toIndentedString(dairyFishMeatPoultryItemModule))
				.append("\n");
		sb.append("    dangerousSubstanceInformationModule: ")
				.append(toIndentedString(dangerousSubstanceInformationModule)).append("\n");
		sb.append("    deliveryPurchasingInformationModuleGroup: ")
				.append(toIndentedString(deliveryPurchasingInformationModuleGroup)).append("\n");
		sb.append("    dietInformationModule: ").append(toIndentedString(dietInformationModule)).append("\n");
		sb.append("    durableGoodsCharacteristicsModule: ").append(toIndentedString(durableGoodsCharacteristicsModule))
				.append("\n");
		sb.append("    dutyFeeTaxInformationModule: ").append(toIndentedString(dutyFeeTaxInformationModule))
				.append("\n");
		sb.append("    electronicDeviceCharacteristicsInformationModule: ")
				.append(toIndentedString(electronicDeviceCharacteristicsInformationModule)).append("\n");
		sb.append("    farmingAndProcessingInformationModule: ")
				.append(toIndentedString(farmingAndProcessingInformationModule)).append("\n");
		sb.append("    foodAndBeverageIngredientModule: ").append(toIndentedString(foodAndBeverageIngredientModule))
				.append("\n");
		sb.append("    foodAndBeveragePreparationServingModule: ")
				.append(toIndentedString(foodAndBeveragePreparationServingModule)).append("\n");
		sb.append("    foodAndBeveragePropertiesInformationModule: ")
				.append(toIndentedString(foodAndBeveragePropertiesInformationModule)).append("\n");
		sb.append("    healthRelatedInformationModule: ").append(toIndentedString(healthRelatedInformationModule))
				.append("\n");
		sb.append("    healthWellnessPackagingMarkingModule: ")
				.append(toIndentedString(healthWellnessPackagingMarkingModule)).append("\n");
		sb.append("    healthcareItemInformationModule: ").append(toIndentedString(healthcareItemInformationModule))
				.append("\n");
		sb.append("    lightingDeviceModule: ").append(toIndentedString(lightingDeviceModule)).append("\n");
		sb.append("    marketingInformationModuleGroup: ").append(toIndentedString(marketingInformationModuleGroup))
				.append("\n");
		sb.append("    medicalDeviceTradeItemModule: ").append(toIndentedString(medicalDeviceTradeItemModule))
				.append("\n");
		sb.append("    movieRevenueInformationModule: ").append(toIndentedString(movieRevenueInformationModule))
				.append("\n");
		sb.append("    nonGTINLogisticsUnitInformationModule: ")
				.append(toIndentedString(nonGTINLogisticsUnitInformationModule)).append("\n");
		sb.append("    nonfoodIngredientModule: ").append(toIndentedString(nonfoodIngredientModule)).append("\n");
		sb.append("    nutritionalInformationModule: ").append(toIndentedString(nutritionalInformationModule))
				.append("\n");
		sb.append("    organismClassificationModule: ").append(toIndentedString(organismClassificationModule))
				.append("\n");
		sb.append("    packagingInformationModule: ").append(toIndentedString(packagingInformationModule)).append("\n");
		sb.append("    packagingMarkingModule: ").append(toIndentedString(packagingMarkingModule)).append("\n");
		sb.append("    packagingSustainabilityModule: ").append(toIndentedString(packagingSustainabilityModule))
				.append("\n");
		sb.append("    pharmaceuticalItemInformationModule: ")
				.append(toIndentedString(pharmaceuticalItemInformationModule)).append("\n");
		sb.append("    physicalResourceUsageInformationModule: ")
				.append(toIndentedString(physicalResourceUsageInformationModule)).append("\n");
		sb.append("    placeOfItemActivityModule: ").append(toIndentedString(placeOfItemActivityModule)).append("\n");
		sb.append("    productCharacteristicsModule: ").append(toIndentedString(productCharacteristicsModule))
				.append("\n");
		sb.append("    productFormulationStatementModule: ").append(toIndentedString(productFormulationStatementModule))
				.append("\n");
		sb.append("    productionVariantCancelledDateTime: ")
				.append(toIndentedString(productionVariantCancelledDateTime)).append("\n");
		sb.append("    productionVariantDescription: ").append(toIndentedString(productionVariantDescription))
				.append("\n");
		sb.append("    productionVariantDiscontinuedDateTime: ")
				.append(toIndentedString(productionVariantDiscontinuedDateTime)).append("\n");
		sb.append("    productionVariantEffectiveDateTime: ")
				.append(toIndentedString(productionVariantEffectiveDateTime)).append("\n");
		sb.append("    promotionalItemInformationModuleGroup: ")
				.append(toIndentedString(promotionalItemInformationModuleGroup)).append("\n");
		sb.append("    propellantInformationModule: ").append(toIndentedString(propellantInformationModule))
				.append("\n");
		sb.append("    publicationTitleRatingModule: ").append(toIndentedString(publicationTitleRatingModule))
				.append("\n");
		sb.append("    referencedFileDetailInformationModule: ")
				.append(toIndentedString(referencedFileDetailInformationModule)).append("\n");
		sb.append("    regulatedTradeItemModule: ").append(toIndentedString(regulatedTradeItemModule)).append("\n");
		sb.append("    safetyDataSheetModule: ").append(toIndentedString(safetyDataSheetModule)).append("\n");
		sb.append("    salesInformationModuleGroup: ").append(toIndentedString(salesInformationModuleGroup))
				.append("\n");
		sb.append("    securityTagInformationModule: ").append(toIndentedString(securityTagInformationModule))
				.append("\n");
		sb.append("    sustainabilityModule: ").append(toIndentedString(sustainabilityModule)).append("\n");
		sb.append("    textileMaterialModule: ").append(toIndentedString(textileMaterialModule)).append("\n");
		sb.append("    tradeItemComponents: ").append(toIndentedString(tradeItemComponents)).append("\n");
		sb.append("    tradeItemDataCarrierAndIdentificationModule: ")
				.append(toIndentedString(tradeItemDataCarrierAndIdentificationModule)).append("\n");
		sb.append("    tradeItemDescriptionModule: ").append(toIndentedString(tradeItemDescriptionModule)).append("\n");
		sb.append("    tradeItemDisposalInformationModule: ")
				.append(toIndentedString(tradeItemDisposalInformationModule)).append("\n");
		sb.append("    tradeItemFeatureBenefitExtended: ").append(toIndentedString(tradeItemFeatureBenefitExtended))
				.append("\n");
		sb.append("    tradeItemHandlingModule: ").append(toIndentedString(tradeItemHandlingModule)).append("\n");
		sb.append("    tradeItemHierarchyModule: ").append(toIndentedString(tradeItemHierarchyModule)).append("\n");
		sb.append("    tradeItemHumidityInformationModule: ")
				.append(toIndentedString(tradeItemHumidityInformationModule)).append("\n");
		sb.append("    tradeItemLicensingModule: ").append(toIndentedString(tradeItemLicensingModule)).append("\n");
		sb.append("    tradeItemLifespanModuleGroup: ").append(toIndentedString(tradeItemLifespanModuleGroup))
				.append("\n");
		sb.append("    tradeItemMeasurementsModule: ").append(toIndentedString(tradeItemMeasurementsModule))
				.append("\n");
		sb.append("    tradeItemSizeModule: ").append(toIndentedString(tradeItemSizeModule)).append("\n");
		sb.append("    tradeItemTemperatureInformationModule: ")
				.append(toIndentedString(tradeItemTemperatureInformationModule)).append("\n");
		sb.append("    transportationHazardousClassificationModule: ")
				.append(toIndentedString(transportationHazardousClassificationModule)).append("\n");
		sb.append("    variableTradeItemInformationModule: ")
				.append(toIndentedString(variableTradeItemInformationModule)).append("\n");
		sb.append("    videoDisplayDeviceInformationModule: ")
				.append(toIndentedString(videoDisplayDeviceInformationModule)).append("\n");
		sb.append("    warrantyInformationModule: ").append(toIndentedString(warrantyInformationModule)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
