/*
 * 1WorldSync Content1 API
 * Content1 will provide access to accurate, trusted product data sourced directly from the Brand Owners through 1WorldSync’s APIs. This full set of product information is readily available to you through a set of web services, allowing you to get up-to-date, complete product information. <br/><br/>The following APIs are available<ul><li>Product Search API - Performs a search against the product data published in ContentNOW to find products that meet the supplied criteria. For each search result displayed, a basic set of information about the product is provided. While performing a product search only a subset from the entire list of attributes for an item will be returned.</li><li>Product Fetch API - Once a Product Search has been performed, the full set of atrribute information on a given product can be retrieved using the Product Fetch API and the item reference id (obtained through the search).</li></ul><p>This tool features a fully functional form which will call the Content1 API in real time.  To unlock the API call, you must have your client secret key provided through <a href=\"#\" onclick=\"openWindow('https://developer.1worldsync.com', 'Content1')\">developer.1worldsync.com</a>. Enter that key in the top right of this page to unlock the API calls used below.</p><p>Don't have a key but want to read the documenation? Go ahead! Basic API documentation is provided below.</p><div style=\"border: 1px solid transparent;color:#fff;background-color: #00ACC8;padding-left: 10px;height:30px;font-weight:bold;font-size:1.3em;margin:0;font-family: ProximaNova;padding-top:10px\">Search and Fetch Model Schemas</div><ul><li><a href=\"../doc/1WorldSync_Content1_Product_Search_Model_Schema_Guide_v3.1.6.1.pdf\" target=\"_blank\">Search Model Schema</a></li><li><a href=\"../doc/1WorldSync_Content1_Product_Fetch_Model_Schema_Guide_v3.1.6.6.pdf\" target=\"_blank\">Fetch Model Schema</a> </li></ul>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.foodauthent.oneworldsync.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.foodauthent.oneworldsync.client.model.CodifiedValue;
import org.foodauthent.oneworldsync.client.model.ManufacturerTakeBackProgram;
import org.foodauthent.oneworldsync.client.model.TradeItemWasteManagement;

/**
 * TradeItemDisposalInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-25T20:10:55.785Z")
public class TradeItemDisposalInformation {
	@JsonProperty("areHazardousComponentsRemovable")
	private CodifiedValue areHazardousComponentsRemovable = null;

	@JsonProperty("componentsLabeledForDisassemblyRecyclingPercent")
	private String componentsLabeledForDisassemblyRecyclingPercent = null;

	@JsonProperty("doesTradeItemHaveRefuseObligations")
	private CodifiedValue doesTradeItemHaveRefuseObligations = null;

	@JsonProperty("isTradeItemConsumerUpgradeableOrMaintainable")
	private CodifiedValue isTradeItemConsumerUpgradeableOrMaintainable = null;

	@JsonProperty("isTradeItemDesignedForEasyDisassembly")
	private CodifiedValue isTradeItemDesignedForEasyDisassembly = null;

	@JsonProperty("isTradeItemUniversalWaste")
	private CodifiedValue isTradeItemUniversalWaste = null;

	@JsonProperty("manufacturerTakeBackProgram")
	private ManufacturerTakeBackProgram manufacturerTakeBackProgram = null;

	@JsonProperty("tradeItemWasteManagement")
	private List<TradeItemWasteManagement> tradeItemWasteManagement = null;

	public TradeItemDisposalInformation areHazardousComponentsRemovable(CodifiedValue areHazardousComponentsRemovable) {
		this.areHazardousComponentsRemovable = areHazardousComponentsRemovable;
		return this;
	}

	/**
	 * Get areHazardousComponentsRemovable
	 * 
	 * @return areHazardousComponentsRemovable
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getAreHazardousComponentsRemovable() {
		return areHazardousComponentsRemovable;
	}

	public void setAreHazardousComponentsRemovable(CodifiedValue areHazardousComponentsRemovable) {
		this.areHazardousComponentsRemovable = areHazardousComponentsRemovable;
	}

	public TradeItemDisposalInformation componentsLabeledForDisassemblyRecyclingPercent(
			String componentsLabeledForDisassemblyRecyclingPercent) {
		this.componentsLabeledForDisassemblyRecyclingPercent = componentsLabeledForDisassemblyRecyclingPercent;
		return this;
	}

	/**
	 * Get componentsLabeledForDisassemblyRecyclingPercent
	 * 
	 * @return componentsLabeledForDisassemblyRecyclingPercent
	 **/
	@ApiModelProperty(value = "")
	public String getComponentsLabeledForDisassemblyRecyclingPercent() {
		return componentsLabeledForDisassemblyRecyclingPercent;
	}

	public void setComponentsLabeledForDisassemblyRecyclingPercent(
			String componentsLabeledForDisassemblyRecyclingPercent) {
		this.componentsLabeledForDisassemblyRecyclingPercent = componentsLabeledForDisassemblyRecyclingPercent;
	}

	public TradeItemDisposalInformation doesTradeItemHaveRefuseObligations(
			CodifiedValue doesTradeItemHaveRefuseObligations) {
		this.doesTradeItemHaveRefuseObligations = doesTradeItemHaveRefuseObligations;
		return this;
	}

	/**
	 * Get doesTradeItemHaveRefuseObligations
	 * 
	 * @return doesTradeItemHaveRefuseObligations
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getDoesTradeItemHaveRefuseObligations() {
		return doesTradeItemHaveRefuseObligations;
	}

	public void setDoesTradeItemHaveRefuseObligations(CodifiedValue doesTradeItemHaveRefuseObligations) {
		this.doesTradeItemHaveRefuseObligations = doesTradeItemHaveRefuseObligations;
	}

	public TradeItemDisposalInformation isTradeItemConsumerUpgradeableOrMaintainable(
			CodifiedValue isTradeItemConsumerUpgradeableOrMaintainable) {
		this.isTradeItemConsumerUpgradeableOrMaintainable = isTradeItemConsumerUpgradeableOrMaintainable;
		return this;
	}

	/**
	 * Get isTradeItemConsumerUpgradeableOrMaintainable
	 * 
	 * @return isTradeItemConsumerUpgradeableOrMaintainable
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemConsumerUpgradeableOrMaintainable() {
		return isTradeItemConsumerUpgradeableOrMaintainable;
	}

	public void setIsTradeItemConsumerUpgradeableOrMaintainable(
			CodifiedValue isTradeItemConsumerUpgradeableOrMaintainable) {
		this.isTradeItemConsumerUpgradeableOrMaintainable = isTradeItemConsumerUpgradeableOrMaintainable;
	}

	public TradeItemDisposalInformation isTradeItemDesignedForEasyDisassembly(
			CodifiedValue isTradeItemDesignedForEasyDisassembly) {
		this.isTradeItemDesignedForEasyDisassembly = isTradeItemDesignedForEasyDisassembly;
		return this;
	}

	/**
	 * Get isTradeItemDesignedForEasyDisassembly
	 * 
	 * @return isTradeItemDesignedForEasyDisassembly
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemDesignedForEasyDisassembly() {
		return isTradeItemDesignedForEasyDisassembly;
	}

	public void setIsTradeItemDesignedForEasyDisassembly(CodifiedValue isTradeItemDesignedForEasyDisassembly) {
		this.isTradeItemDesignedForEasyDisassembly = isTradeItemDesignedForEasyDisassembly;
	}

	public TradeItemDisposalInformation isTradeItemUniversalWaste(CodifiedValue isTradeItemUniversalWaste) {
		this.isTradeItemUniversalWaste = isTradeItemUniversalWaste;
		return this;
	}

	/**
	 * Get isTradeItemUniversalWaste
	 * 
	 * @return isTradeItemUniversalWaste
	 **/
	@ApiModelProperty(value = "")
	public CodifiedValue getIsTradeItemUniversalWaste() {
		return isTradeItemUniversalWaste;
	}

	public void setIsTradeItemUniversalWaste(CodifiedValue isTradeItemUniversalWaste) {
		this.isTradeItemUniversalWaste = isTradeItemUniversalWaste;
	}

	public TradeItemDisposalInformation manufacturerTakeBackProgram(
			ManufacturerTakeBackProgram manufacturerTakeBackProgram) {
		this.manufacturerTakeBackProgram = manufacturerTakeBackProgram;
		return this;
	}

	/**
	 * Get manufacturerTakeBackProgram
	 * 
	 * @return manufacturerTakeBackProgram
	 **/
	@ApiModelProperty(value = "")
	public ManufacturerTakeBackProgram getManufacturerTakeBackProgram() {
		return manufacturerTakeBackProgram;
	}

	public void setManufacturerTakeBackProgram(ManufacturerTakeBackProgram manufacturerTakeBackProgram) {
		this.manufacturerTakeBackProgram = manufacturerTakeBackProgram;
	}

	public TradeItemDisposalInformation tradeItemWasteManagement(
			List<TradeItemWasteManagement> tradeItemWasteManagement) {
		this.tradeItemWasteManagement = tradeItemWasteManagement;
		return this;
	}

	public TradeItemDisposalInformation addTradeItemWasteManagementItem(
			TradeItemWasteManagement tradeItemWasteManagementItem) {
		if (this.tradeItemWasteManagement == null) {
			this.tradeItemWasteManagement = new ArrayList<TradeItemWasteManagement>();
		}
		this.tradeItemWasteManagement.add(tradeItemWasteManagementItem);
		return this;
	}

	/**
	 * Get tradeItemWasteManagement
	 * 
	 * @return tradeItemWasteManagement
	 **/
	@ApiModelProperty(value = "")
	public List<TradeItemWasteManagement> getTradeItemWasteManagement() {
		return tradeItemWasteManagement;
	}

	public void setTradeItemWasteManagement(List<TradeItemWasteManagement> tradeItemWasteManagement) {
		this.tradeItemWasteManagement = tradeItemWasteManagement;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		TradeItemDisposalInformation tradeItemDisposalInformation = (TradeItemDisposalInformation) o;
		return Objects.equals(this.areHazardousComponentsRemovable,
				tradeItemDisposalInformation.areHazardousComponentsRemovable)
				&& Objects.equals(this.componentsLabeledForDisassemblyRecyclingPercent,
						tradeItemDisposalInformation.componentsLabeledForDisassemblyRecyclingPercent)
				&& Objects.equals(this.doesTradeItemHaveRefuseObligations,
						tradeItemDisposalInformation.doesTradeItemHaveRefuseObligations)
				&& Objects.equals(this.isTradeItemConsumerUpgradeableOrMaintainable,
						tradeItemDisposalInformation.isTradeItemConsumerUpgradeableOrMaintainable)
				&& Objects.equals(this.isTradeItemDesignedForEasyDisassembly,
						tradeItemDisposalInformation.isTradeItemDesignedForEasyDisassembly)
				&& Objects.equals(this.isTradeItemUniversalWaste,
						tradeItemDisposalInformation.isTradeItemUniversalWaste)
				&& Objects.equals(this.manufacturerTakeBackProgram,
						tradeItemDisposalInformation.manufacturerTakeBackProgram)
				&& Objects.equals(this.tradeItemWasteManagement, tradeItemDisposalInformation.tradeItemWasteManagement);
	}

	@Override
	public int hashCode() {
		return Objects.hash(areHazardousComponentsRemovable, componentsLabeledForDisassemblyRecyclingPercent,
				doesTradeItemHaveRefuseObligations, isTradeItemConsumerUpgradeableOrMaintainable,
				isTradeItemDesignedForEasyDisassembly, isTradeItemUniversalWaste, manufacturerTakeBackProgram,
				tradeItemWasteManagement);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class TradeItemDisposalInformation {\n");

		sb.append("    areHazardousComponentsRemovable: ").append(toIndentedString(areHazardousComponentsRemovable))
				.append("\n");
		sb.append("    componentsLabeledForDisassemblyRecyclingPercent: ")
				.append(toIndentedString(componentsLabeledForDisassemblyRecyclingPercent)).append("\n");
		sb.append("    doesTradeItemHaveRefuseObligations: ")
				.append(toIndentedString(doesTradeItemHaveRefuseObligations)).append("\n");
		sb.append("    isTradeItemConsumerUpgradeableOrMaintainable: ")
				.append(toIndentedString(isTradeItemConsumerUpgradeableOrMaintainable)).append("\n");
		sb.append("    isTradeItemDesignedForEasyDisassembly: ")
				.append(toIndentedString(isTradeItemDesignedForEasyDisassembly)).append("\n");
		sb.append("    isTradeItemUniversalWaste: ").append(toIndentedString(isTradeItemUniversalWaste)).append("\n");
		sb.append("    manufacturerTakeBackProgram: ").append(toIndentedString(manufacturerTakeBackProgram))
				.append("\n");
		sb.append("    tradeItemWasteManagement: ").append(toIndentedString(tradeItemWasteManagement)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
